/**
 * Utility functions for exporting report data to CSV and PDF
 */

import { formatCurrency } from "@/lib/utils";
import { LAST_RESORT_CURRENCY } from "@/lib/regions/last-resort-currency";

/** Generic report row shape for export formatters */
export type ReportRow = Record<string, unknown>;

/** Escape text for HTML print/PDF to avoid script injection and broken layout from `<` in values. */
export function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Format numeric amounts for CSV/PDF export rows (tenant currency from config bundle). */
export function fm(amount: unknown, currencyCode: string): string {
  const n =
    typeof amount === "number"
      ? amount
      : typeof amount === "string"
        ? parseFloat(amount)
        : Number(amount ?? 0);
  return formatCurrency(Number.isFinite(n) ? n : 0, currencyCode);
}

export function exportToCSV(data: Record<string, unknown>[], filename: string) {
  if (!data || data.length === 0) {
    alert("No data to export");
    return;
  }

  // Get headers from first object
  const headers = Object.keys(data[0]);
  
  // Create CSV content
  const csvContent = [
    // Headers
    headers.map((h) => `"${h}"`).join(","),
    // Data rows
    ...data.map((row) =>
      headers
        .map((header) => {
          const value = row[header];
          // Handle null/undefined
          if (value === null || value === undefined) return '""';
          // Handle dates
          if (value instanceof Date) {
            return `"${value.toISOString()}"`;
          }
          // Handle objects/arrays
          if (typeof value === "object") {
            return `"${JSON.stringify(value).replace(/"/g, '""')}"`;
          }
          // Handle strings with quotes
          return `"${String(value).replace(/"/g, '""')}"`;
        })
        .join(",")
    ),
  ].join("\n");

  // Create blob and download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${new Date().toISOString().split("T")[0]}.csv`);
  link.style.visibility = "hidden";
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

/**
 * Export report to PDF using browser print functionality
 * Can export either from a report element ID or from data array
 */
export function exportToPDF(reportIdOrData: string | unknown[], filename?: string, title: string = "Report") {
  // If first parameter is a string, it's a report ID - export the HTML element
  if (typeof reportIdOrData === "string") {
    const reportElement = document.getElementById(reportIdOrData);
    if (!reportElement) {
      alert("Report element not found");
      return;
    }

    // Clone the element to avoid modifying the original
    const clonedElement = reportElement.cloneNode(true) as HTMLElement;
    
    // Create HTML document
    const safeTitle = escapeHtml(title);
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${safeTitle}</title>
          <style>
            @media print {
              @page { margin: 1cm; }
              body { margin: 0; }
            }
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
              max-width: 1000px;
              color: #111;
            }
            h1 {
              margin-bottom: 20px;
              color: #333;
            }
            .footer {
              margin-top: 30px;
              font-size: 12px;
              color: #666;
              text-align: center;
            }
            * {
              box-sizing: border-box;
            }
            #reportRoot table {
              width: 100%;
              border-collapse: collapse;
              margin: 0.5rem 0;
            }
            #reportRoot th,
            #reportRoot td {
              border: 1px solid #ccc;
              padding: 6px 8px;
              text-align: left;
              font-size: 12px;
              color: #111;
              background: #fff;
            }
            #reportRoot img { max-width: 100% !important; }
          </style>
        </head>
        <body>
          <h1>${safeTitle}</h1>
          <p>Generated: ${escapeHtml(new Date().toLocaleString())}</p>
          <div id="reportRoot">${clonedElement.outerHTML}</div>
          <div class="footer">
            <p>Report generated by Beautonomi</p>
          </div>
        </body>
      </html>
    `;

    // Open in new window and print
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert("Please allow popups to export PDF");
      return;
    }
    
    printWindow.document.write(html);
    printWindow.document.close();
    
    // Wait for content to load, then print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 250);
    };
    return;
  }

  // Otherwise, treat as data array (legacy support)
  const data = reportIdOrData;
  if (!data || data.length === 0) {
    alert("No data to export");
    return;
  }

  // Get headers from first object
  const headers = Object.keys(data[0]);
  
  // Create HTML table
  const tableRows = data.map((row) => {
    const cells = headers.map((header) => {
      const value = row[header];
      let displayValue = "";
      
      if (value === null || value === undefined) {
        displayValue = "";
      } else if (value instanceof Date) {
        displayValue = value.toLocaleDateString();
      } else if (typeof value === "object") {
        displayValue = JSON.stringify(value);
      } else {
        displayValue = String(value);
      }
      
      return `<td>${displayValue}</td>`;
    }).join("");
    
    return `<tr>${cells}</tr>`;
  }).join("");

  const headerCells = headers.map((h) => `<th>${h}</th>`).join("");

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @media print {
            @page { margin: 1cm; }
            body { margin: 0; }
          }
          body {
            font-family: Arial, sans-serif;
            padding: 20px;
          }
          h1 {
            margin-bottom: 20px;
            color: #333;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
          }
          th {
            background-color: #f5f5f5;
            font-weight: bold;
          }
          tr:nth-child(even) {
            background-color: #f9f9f9;
          }
          .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #666;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(title)}</h1>
        <p>Generated: ${escapeHtml(new Date().toLocaleString())}</p>
        <table>
          <thead>
            <tr>${headerCells}</tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        <div class="footer">
          <p>Report generated by Beautonomi</p>
        </div>
      </body>
    </html>
  `;

  // Open in new window and print
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert("Please allow popups to export PDF");
    return;
  }
  
  printWindow.document.write(html);
  printWindow.document.close();
  
  // Wait for content to load, then print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
}

export function formatReportDataForExport(
  data: ReportRow,
  reportType: string,
  currencyCode: string = LAST_RESORT_CURRENCY
): Record<string, unknown>[] {
  switch (reportType) {
    case "booking-summary":
      return [
        { Metric: "Total Bookings", Value: data.totalBookings || 0 },
        { Metric: "Total Revenue", Value: fm((data.totalRevenue as number), currencyCode) },
        { Metric: "Average Booking Value", Value: fm((data.averageBookingValue as number), currencyCode) },
        ...((data.statusBreakdown as ReportRow[]) || []).map((status) => ({
          Status: status.status,
          Count: status.count,
          Revenue: fm((status.revenue as number), currencyCode),
          Percentage: `${(status.percentage as number)?.toFixed(1) || 0}%`,
        })),
        ...((data.dailyBookings as ReportRow[]) || []).map((day) => ({
          Date: day.date,
          Bookings: day.count,
          Revenue: fm((day.revenue as number), currencyCode),
        })),
        ...((data.topServices as ReportRow[]) || []).map((service) => ({
          Service: service.serviceName,
          Bookings: service.bookings,
          Revenue: fm((service.revenue as number), currencyCode),
        })),
      ];

    case "business-dashboard": {
      const today = data.today as Record<string, unknown> | undefined;
      const week = data.week as Record<string, unknown> | undefined;
      const month = data.month as Record<string, unknown> | undefined;
      return [
        { Metric: "Today's Revenue", Value: fm((today?.revenue as number), currencyCode) },
        { Metric: "Today's Bookings", Value: (today?.bookings as number) || 0 },
        { Metric: "Today's Completed", Value: (today?.completed as number) || 0 },
        { Metric: "Week Revenue", Value: fm((week?.revenue as number), currencyCode) },
        { Metric: "Week Bookings", Value: (week?.bookings as number) || 0 },
        { Metric: "Month Revenue", Value: fm((month?.revenue as number), currencyCode) },
        { Metric: "Month Bookings", Value: (month?.bookings as number) || 0 },
        { Metric: "Month Clients", Value: (month?.clients as number) || 0 },
        ...((data.upcomingBookings as ReportRow[]) || []).map((booking) => ({
          "Upcoming Booking": new Date((booking.scheduled_at as string) || 0).toLocaleString(),
          Status: booking.status,
          Amount: fm(Number(booking.total_amount || 0), currencyCode),
        })),
        ...((data.recentBookings as ReportRow[]) || []).map((booking) => ({
          "Recent Booking": new Date((booking.scheduled_at as string) || 0).toLocaleString(),
          Status: booking.status,
          Amount: fm(Number(booking.total_amount || 0), currencyCode),
        })),
      ];
    }
    
    case "sales-summary":
      return [
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        { Metric: "Total Bookings", Value: data.totalBookings || 0 },
        { Metric: "Average Booking Value", Value: fm(data.averageBookingValue, currencyCode) },
        ...((data.revenueByDay as ReportRow[]) || []).map((item) => ({
          Date: item.date,
          Revenue: fm((item.revenue as number), currencyCode),
          Bookings: item.bookings || 0,
        })),
      ];

    case "staff-performance":
      return ((data.staffMembers as ReportRow[]) || []).map((staff) => ({
        "Staff Name": staff.staffName,
        "Total Bookings": staff.totalBookings,
        "Total Revenue": fm((staff.totalRevenue || 0), currencyCode),
        "Hours Worked": `${Number(staff.totalHours ?? 0).toFixed(1)}h`,
        "Average Rating": staff.averageRating != null ? Number(staff.averageRating).toFixed(1) : "N/A",
        "Commission": fm((staff.commissionEarned || 0), currencyCode),
      }));
    
    case "client-summary":
      return [
        { Metric: "Total Clients", Value: data.totalClients || 0 },
        { Metric: "New Clients", Value: data.newClients || 0 },
        { Metric: "Returning Clients", Value: data.returningClients || 0 },
        { Metric: "Average Lifetime Value", Value: fm(data.averageLifetimeValue, currencyCode) },
        ...((data.topClients as ReportRow[]) || []).map((client) => ({
          "Client Name": client.clientName,
          "Total Bookings": client.totalBookings,
          "Total Spent": fm((client.totalSpent as number), currencyCode),
          "Last Visit": client.lastVisit,
        })),
      ];

    case "booking-status":
      return [
        { Metric: "Total Bookings", Value: data.totalBookings || 0 },
        { Metric: "Completion Rate", Value: `${Number(data.completionRate ?? 0).toFixed(1)}%` },
        { Metric: "Cancellation Rate", Value: `${Number(data.cancellationRate ?? 0).toFixed(1)}%` },
        { Metric: "No-Show Rate", Value: `${Number(data.noShowRate ?? 0).toFixed(1)}%` },
        ...((data.bookingsByStatus as ReportRow[]) || []).map((status) => ({
          Status: status.status,
          Count: status.count,
          Percentage: `${(status.percentage as number)?.toFixed(1) || 0}%`,
          Revenue: fm((status.revenue as number), currencyCode),
        })),
      ];

    case "service-performance":
      return [
        { Metric: "Total Services", Value: data.totalServices || 0 },
        { Metric: "Total Bookings", Value: data.totalBookings || 0 },
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        ...((data.topServices as ReportRow[]) || (data.allServices as ReportRow[]) || []).map((s) => ({
          Service: s.serviceName,
          Category: s.category,
          Bookings: s.bookings,
          Revenue: fm((s.revenue as number), currencyCode),
          "Avg Price": fm((s.averagePrice as number), currencyCode),
        })),
      ];

    case "revenue-trends":
      return [
        { Metric: "Period", Value: data.period || "" },
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        { Metric: "Total Bookings", Value: data.totalBookings || 0 },
        { Metric: "Revenue Growth", Value: `${Number(data.revenueGrowth ?? 0).toFixed(1)}%` },
        ...((data.trends as ReportRow[]) || []).map((t) => ({
          Period: t.period,
          Revenue: fm((t.revenue as number), currencyCode),
          Bookings: t.bookings || 0,
        })),
      ];

    case "business-overview":
      return [
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        { Metric: "Net Revenue", Value: fm(data.netRevenue, currencyCode) },
        { Metric: "Total Bookings", Value: data.totalBookings || 0 },
        { Metric: "Unique Clients", Value: data.uniqueClients || 0 },
        { Metric: "Completion Rate", Value: `${Number(data.completionRate ?? 0).toFixed(1)}%` },
        { Metric: "Revenue Growth", Value: `${Number(data.revenueGrowth ?? 0).toFixed(1)}%` },
      ];

    case "business-comparison": {
      const current = data.current as Record<string, unknown> | undefined;
      const previous = data.previous as Record<string, unknown> | undefined;
      const growth = data.growth as Record<string, unknown> | undefined;
      return [
        { Metric: "Current Revenue", Value: fm((current?.revenue as number), currencyCode) },
        { Metric: "Previous Revenue", Value: fm((previous?.revenue as number), currencyCode) },
        { Metric: "Revenue Growth", Value: `${Number(growth?.revenue ?? 0).toFixed(1)}%` },
      ];
    }

    case "gift-card-sales":
      return [
        { Metric: "Total Redemptions", Value: data.totalGiftCardsSold || 0 },
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        ...((data.giftCardSales as ReportRow[]) || []).map((item) => ({
          Amount: fm(Number(item.amount || 0), currencyCode),
          Count: item.count || 0,
          Revenue: fm(Number(item.revenue || 0), currencyCode),
        })),
      ];

    case "gift-card-redemptions":
      return [
        { Metric: "Total Redemptions", Value: data.totalRedemptions || 0 },
        { Metric: "Total Redeemed Value", Value: fm(data.totalRedeemedValue, currencyCode) },
        ...((data.redemptions as ReportRow[]) || []).map((r) => ({
          Amount: fm(Number(r.amount || 0), currencyCode),
          Date: r.captured_at,
        })),
      ];

    case "cancellations":
      return [
        { Metric: "Total Cancelled", Value: data.totalCancelled || 0 },
        { Metric: "Cancellation Rate", Value: `${Number(data.cancellationRate ?? 0).toFixed(1)}%` },
        { Metric: "Lost Revenue", Value: fm(data.lostRevenue, currencyCode) },
        ...((data.cancellationReasons as ReportRow[]) || []).map((r) => ({
          Reason: r.reason,
          Count: r.count,
          Percentage: `${((r.percentage as number) || 0).toFixed(1)}%`,
        })),
      ];

    case "no-shows":
      return [
        { Metric: "Total No-Shows", Value: data.totalNoShows || 0 },
        { Metric: "Lost Revenue", Value: fm(data.lostRevenue, currencyCode) },
        ...((data.repeatOffenders as ReportRow[]) || []).map((r) => ({
          Name: r.name,
          Count: r.count,
          Revenue: fm(Number(r.revenue || 0), currencyCode),
        })),
      ];

    case "product-sales":
      return [
        { Metric: "Total Products Sold", Value: data.totalProductsSold || 0 },
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        { Metric: "Total Cost", Value: fm((data.totalCost ?? 0), currencyCode) },
        { Metric: "Total Profit", Value: fm((data.totalProfit ?? 0), currencyCode) },
        ...((data.topProducts as ReportRow[]) || []).map((p) => ({
          Product: p.productName,
          "Quantity Sold": p.quantitySold || 0,
          Revenue: fm(((p.revenue as number) || 0), currencyCode),
          Cost: fm(((p.cost as number) ?? 0), currencyCode),
          Profit: fm(((p.profit as number) ?? 0), currencyCode),
        })),
        ...((data.productsByCategory as ReportRow[]) || []).map((p) => ({
          Category: p.category,
          "Quantity Sold": p.quantitySold || 0,
          Revenue: fm(((p.revenue as number) || 0), currencyCode),
          Profit: fm(((p.profit as number) ?? 0), currencyCode),
        })),
      ];

    case "payment-summary":
      return [
        { Metric: "Total Payments", Value: data.totalPayments || 0 },
        { Metric: "Gross Booked Value", Value: fm(data.grossBookedValue ?? data.totalAmount, currencyCode) },
        { Metric: "Settled Ledger Amount", Value: fm(data.settledLedgerAmount ?? data.totalCollected, currencyCode) },
        { Metric: "Customer Payments by Method Total", Value: fm(data.customerPaymentsByMethodTotal, currencyCode) },
        { Metric: "Provider Earnings", Value: fm(data.providerEarnings, currencyCode) },
        { Metric: "Provider Net Activity", Value: fm(data.providerNetActivity ?? data.netAmount, currencyCode) },
        { Metric: "Refunded Amount", Value: fm(data.refundedAmount, currencyCode) },
        { Metric: "Refund Rate", Value: `${Number(data.refundRate ?? 0).toFixed(1)}%` },
        ...((data.paymentsByMethod as ReportRow[]) || []).map((p) => ({
          Method: p.method,
          Count: p.count,
          Amount: fm(((p.amount as number) || 0), currencyCode),
        })),
      ];

    case "new-clients":
      return [
        { Metric: "Total New Clients", Value: data.totalNewClients || 0 },
        { Metric: "Return Rate", Value: `${Number(data.returnRate ?? 0).toFixed(1)}%` },
        ...((data.newClients as ReportRow[]) || []).map((c) => ({
          "Client Name": c.clientName,
          "First Visit": c.firstVisit,
          "Total Spent": fm(((c.totalSpent as number) || 0), currencyCode),
          Returned: c.hasReturned ? "Yes" : "No",
        })),
      ];

    case "client-retention":
      return [
        { Metric: "Retention Rate", Value: `${Number(data.overallRetentionRate ?? 0).toFixed(1)}%` },
        ...((data.retentionByPeriod as ReportRow[]) || (data.periods as ReportRow[]) || []).map((p) => ({
          Period: p.period,
          "Retention Rate": `${((p.retentionRate as number) ?? (p.retention_rate as number) ?? 0).toFixed(1)}%`,
          Clients: (p.clients as number) ?? (p.clientCount as number) ?? 0,
        })),
      ];

    case "lifetime-value":
      return [
        { Metric: "Total Clients", Value: data.totalClients || 0 },
        { Metric: "Average LTV", Value: fm(data.averageLTV, currencyCode) },
        ...((data.topClients as ReportRow[]) || (data.clientLTV as ReportRow[]) || []).slice(0, 50).map((c) => ({
          Client: c.clientName ?? c.customerId,
          "Total Spent": fm(((c.totalSpent as number) || 0), currencyCode),
          Bookings: c.totalBookings || 0,
        })),
      ];

    case "package-usage":
      return [
        { Metric: "Total Packages Used", Value: data.totalPackagesUsed || 0 },
        { Metric: "Unique Clients", Value: data.totalUniqueClients || 0 },
        ...((data.packageUsage as ReportRow[]) || []).map((p) => ({
          Package: p.packageName ?? p.name,
          "Times Used": p.totalUsage || 0,
          "Unique Clients": p.uniqueClientsCount || 0,
        })),
      ];

    case "package-sales":
      return [
        { Metric: "Total Packages Sold", Value: data.totalPackagesSold || 0 },
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        ...((data.packageSales as ReportRow[]) || []).map((p) => ({
          Package: p.packageName ?? p.name,
          Bookings: p.bookings || 0,
          Revenue: fm(((p.revenue as number) || 0), currencyCode),
        })),
      ];

    case "payouts":
      return [
        { Metric: "Total Payouts", Value: data.totalPayouts || 0 },
        { Metric: "Total Payout Amount", Value: fm((data.totalPayoutAmount || 0), currencyCode) },
        { Metric: "Gross Booked Value", Value: fm(data.totalBookedAmount ?? data.bookedAmount ?? data.totalGrossAmount, currencyCode) },
        { Metric: "Booked Net of Refunds", Value: fm(data.totalBookedNetOfRefunds ?? data.bookedNetOfRefunds, currencyCode) },
        { Metric: "Platform Fees", Value: fm(data.totalPlatformFees, currencyCode) },
        ...((data.monthlyBreakdown as ReportRow[]) || []).map((m) => ({
          Month: m.month,
          Count: m.count || 0,
          Amount: fm(((m.amount as number) || 0), currencyCode),
        })),
        ...((data.recentPayouts as ReportRow[]) || []).map((p) => ({
          Date: p.createdAt,
          "Booked Amount": fm(((p.bookedAmount as number) ?? (p.grossAmount as number) ?? 0), currencyCode),
          "Booked Net of Refunds": fm(((p.bookedNetOfRefunds as number) ?? (p.netAmount as number) ?? 0), currencyCode),
          "Platform Fee": fm(((p.platformFee as number) ?? 0), currencyCode),
          Amount: fm(((p.payoutAmount as number) ?? (p.amount as number) ?? 0), currencyCode),
        })),
      ];

    case "top-products":
      return [
        { Metric: "Total Products Sold", Value: data.totalProductsSold || 0 },
        { Metric: "Total Revenue", Value: fm(data.totalRevenue, currencyCode) },
        ...((data.topProducts as ReportRow[]) || []).map((p) => ({
          Product: p.productName ?? p.name,
          "Quantity Sold": p.totalQuantity ?? p.quantitySold ?? 0,
          Revenue: fm(((p.totalRevenue as number) ?? (p.revenue as number) ?? 0), currencyCode),
        })),
      ];

    case "payment-methods":
      return ((data.methods as ReportRow[]) || []).map((m) => ({
        Method: m.method,
        "Total Count": m.totalCount || 0,
        "Total Amount": fm((m.totalAmount || 0), currencyCode),
      }));

    case "refunds":
      return [
        { Metric: "Total Refunds", Value: data.totalRefunds || 0 },
        { Metric: "Total Refund Amount", Value: fm(data.totalRefundAmount, currencyCode) },
        ...((data.methodBreakdown as ReportRow[]) || (data.refunds as ReportRow[]) || []).map((r) => ({
          Method: r.method,
          Count: r.count || 0,
          Amount: fm(((r.amount as number) || 0), currencyCode),
        })),
      ];

    case "yoco-reconciliation": {
      const summary = data.summary as Record<string, unknown> | undefined;
      return [
        { Metric: "Total Yoco payments", Value: (summary?.total as number) ?? 0 },
        { Metric: "With booking", Value: (summary?.with_booking as number) ?? 0 },
        { Metric: "Synced to booking", Value: (summary?.synced as number) ?? 0 },
        { Metric: "Not synced", Value: (summary?.not_synced as number) ?? 0 },
        ...((data.payments as ReportRow[]) || []).map((p) => ({
          Date: p.created_at,
          "Yoco ID": p.yoco_payment_id,
          Amount: `${((p.amount as number) / 100).toFixed(2)} ${p.currency}`,
          Status: p.status,
          "Has booking": p.appointment_id ? "Yes" : "No",
          "Booking synced": p.appointment_id ? (p.booking_synced ? "Yes" : "No") : "—",
        })),
      ];
    }

    case "inventory":
      return [
        { Metric: "Total Products", Value: data.totalProducts || 0 },
        { Metric: "Stock Value", Value: fm((data.totalStockValue || 0), currencyCode) },
        ...((data.lowStockProducts as ReportRow[]) || (data.allProducts as ReportRow[]) || []).map((p) => {
          const qty = Number((p.quantity as number) ?? (p.stock_quantity as number) ?? 0);
          const lineRetail =
            typeof p.retail_line_value === "number"
              ? p.retail_line_value
              : qty * Number((p.price as number) ?? (p.retail_price as number) ?? 0);
          const displayPrice = Number((p.price as number) ?? (p.retail_price as number) ?? 0);
          return {
            Product: p.name ?? p.productName,
            Stock: qty,
            "Retail Price": fm(displayPrice, currencyCode),
            Value: fm(lineRetail, currencyCode),
          };
        }),
      ];

    case "commission":
      return ((data.staffCommissions as ReportRow[]) || (data.commissionData as ReportRow[]) || []).map((s) => ({
        "Staff Name": s.staffName ?? s.name,
        "Total Revenue": fm(((s.totalRevenue as number) || 0), currencyCode),
        "Commission": fm(((s.totalCommission as number) ?? (s.commissionEarned as number) ?? 0), currencyCode),
      }));

    case "staff-hours":
      return ((data.staffHours as ReportRow[]) || (data.hoursData as ReportRow[]) || []).map((s) => ({
        "Staff Name": s.staffName ?? s.name,
        "Total Hours": ((s.totalHours as number) || 0).toFixed(1),
        Bookings: (s.completedBookings as number) ?? (s.totalBookings as number) ?? 0,
      }));

    case "occupancy": {
      const byDate = (data.byDate as ReportRow[]) || [];
      const byStaff = (data.byStaff as ReportRow[]) || [];
      return [
        ...byDate.map((row) => ({
          View: "by_date",
          "Staff name": "",
          Date: row.date,
          "Available (min)": row.totalAvailable,
          "Booked (min)": row.totalBooked,
          "Occupancy %": row.occupancyPercent,
        })),
        ...byStaff.flatMap((staff) => {
          const s = staff as ReportRow;
          return ((s.byDate as ReportRow[]) || []).map((row) => ({
            View: "by_staff",
            "Staff name": s.staffName,
            Date: row.date,
            "Available (min)": row.availableMinutes,
            "Booked (min)": row.bookedMinutes,
            "Occupancy %": row.occupancyPercent,
          }));
        }),
      ];
    }

    case "end-of-day": {
      const d = data as ReportRow;
      const byM = (d.byPaymentMethod as Record<string, number> | undefined) || {};
      return [
        { Field: "Date", Value: String(d.date ?? "") },
        { Field: "Booking count", Value: d.bookingCount },
        { Field: "Total", Value: fm((d.total as number) || 0, currencyCode) },
        { Field: "Booking payments total", Value: fm((d.bookingPaymentsTotal as number) || 0, currencyCode) },
        { Field: "Wallet total", Value: fm((d.walletTotal as number) || 0, currencyCode) },
        { Field: "Sales total", Value: fm((d.salesTotal as number) || 0, currencyCode) },
        { Field: "Tips total", Value: fm((d.tipsTotal as number) || 0, currencyCode) },
        { Field: "Cancellation fees", Value: fm((d.cancellationFeesTotal as number) || 0, currencyCode) },
        { Field: "Note", Value: String(d.note ?? "") },
        ...Object.keys(byM).map((k) => ({
          Field: `Payment: ${k}`,
          Value: fm((byM[k] as number) || 0, currencyCode),
        })),
      ];
    }

    default:
      if (Array.isArray(data)) {
        return data as Record<string, unknown>[];
      }
      const arrayKeys = Object.keys(data).filter((key) => Array.isArray(data[key]));
      if (arrayKeys.length > 0) {
        return (data[arrayKeys[0]] as Record<string, unknown>[]) ?? [];
      }
      return [data];
  }
}
