/**
 * Provider report navigation — mirrors `apps/web` provider reports hub.
 * Use native stacks where we ship a screen; otherwise open the matching web report in the browser portal.
 */
import Ionicons from "@expo/vector-icons/Ionicons";

export type ReportIon = keyof typeof Ionicons.glyphMap;

export type ProviderReportItem = {
  id: string;
  name: string;
  description: string;
  icon: ReportIon;
  color: string;
  bg: string;
} & (
  | { target: "native"; screen: string }
  | { target: "portal"; webPath: string }
  | { target: "route"; route: string }
);

export type ProviderReportCategory = { title: string; reports: ProviderReportItem[] };

/** `webPath` is absolute on the Next app, e.g. `/provider/reports/sales/summary`. */
export const PROVIDER_REPORT_CATEGORIES: ProviderReportCategory[] = [
  {
    title: "Sales",
    reports: [
      {
        id: "sales-summary",
        name: "Sales Summary",
        description: "Revenue, bookings, and service mix",
        icon: "stats-chart-outline",
        color: "#16a34a",
        bg: "#dcfce7",
        target: "portal",
        webPath: "/provider/reports/sales/summary",
      },
      {
        id: "service-performance",
        name: "Service Performance",
        description: "Which services drive revenue",
        icon: "cut-outline",
        color: "#d97706",
        bg: "#fef3c7",
        target: "native",
        screen: "services",
      },
      {
        id: "product-sales",
        name: "Product Sales",
        description: "Retail product revenue",
        icon: "bag-outline",
        color: "#4f46e5",
        bg: "#e0e7ff",
        target: "portal",
        webPath: "/provider/reports/products/sales",
      },
      {
        id: "revenue-trends",
        name: "Revenue Trends",
        description: "Trends over time",
        icon: "trending-up-outline",
        color: "#059669",
        bg: "#d1fae5",
        target: "portal",
        webPath: "/provider/reports/sales/trends",
      },
    ],
  },
  {
    title: "Staff",
    reports: [
      {
        id: "staff-performance",
        name: "Staff Performance",
        description: "Hours, commissions, bookings",
        icon: "person-outline",
        color: "#4f46e5",
        bg: "#eef2ff",
        target: "native",
        screen: "staff",
      },
      {
        id: "staff-commission",
        name: "Commission Reports",
        description: "Commission breakdown by staff",
        icon: "cash-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "portal",
        webPath: "/provider/reports/staff/commission",
      },
      {
        id: "staff-hours",
        name: "Hours & Attendance",
        description: "Worked hours and attendance",
        icon: "time-outline",
        color: "#0369a1",
        bg: "#e0f2fe",
        target: "portal",
        webPath: "/provider/reports/staff/hours",
      },
    ],
  },
  {
    title: "Bookings",
    reports: [
      {
        id: "booking-summary",
        name: "Booking Summary",
        description: "Volume, status mix, trends",
        icon: "calendar-outline",
        color: "#2563eb",
        bg: "#dbeafe",
        target: "native",
        screen: "bookings",
      },
      {
        id: "booking-status",
        name: "Booking Status",
        description: "Confirmed, completed, pending",
        icon: "pie-chart-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "portal",
        webPath: "/provider/reports/bookings/status",
      },
      {
        id: "occupancy",
        name: "Occupancy",
        description: "Capacity and utilization",
        icon: "bar-chart-outline",
        color: "#0d9488",
        bg: "#ccfbf1",
        target: "portal",
        webPath: "/provider/reports/occupancy",
      },
      {
        id: "cancellations",
        name: "Cancellations",
        description: "Cancelled bookings",
        icon: "close-circle-outline",
        color: "#dc2626",
        bg: "#fee2e2",
        target: "portal",
        webPath: "/provider/reports/bookings/cancellations",
      },
      {
        id: "no-shows",
        name: "No-Shows",
        description: "Missed appointments",
        icon: "alert-circle-outline",
        color: "#ea580c",
        bg: "#ffedd5",
        target: "portal",
        webPath: "/provider/reports/bookings/no-shows",
      },
    ],
  },
  {
    title: "Clients",
    reports: [
      {
        id: "client-summary",
        name: "Client Summary",
        description: "New vs returning, top spenders",
        icon: "people-outline",
        color: "#db2777",
        bg: "#fce7f3",
        target: "native",
        screen: "clients",
      },
      {
        id: "client-retention",
        name: "Client Retention",
        description: "Repeat visit rates",
        icon: "heart-outline",
        color: "#e11d48",
        bg: "#ffe4e6",
        target: "portal",
        webPath: "/provider/reports/clients/retention",
      },
      {
        id: "new-clients",
        name: "New Clients",
        description: "First-time customers",
        icon: "person-add-outline",
        color: "#0891b2",
        bg: "#cffafe",
        target: "portal",
        webPath: "/provider/reports/clients/new",
      },
      {
        id: "client-lifetime-value",
        name: "Lifetime Value",
        description: "CLV and spend bands",
        icon: "trophy-outline",
        color: "#ca8a04",
        bg: "#fef9c3",
        target: "portal",
        webPath: "/provider/reports/clients/lifetime-value",
      },
    ],
  },
  {
    title: "Payments",
    reports: [
      {
        id: "payment-summary",
        name: "Payment Summary",
        description: "Totals, methods, payouts",
        icon: "card-outline",
        color: "#0284c7",
        bg: "#e0f2fe",
        target: "native",
        screen: "payments",
      },
      {
        id: "end-of-day",
        name: "End of day",
        description: "Daily cash-up style summary",
        icon: "today-outline",
        color: "#4338ca",
        bg: "#e0e7ff",
        target: "portal",
        webPath: "/provider/reports/end-of-day",
      },
      {
        id: "refunds",
        name: "Refunds",
        description: "Refund volume and reasons",
        icon: "return-down-back-outline",
        color: "#b91c1c",
        bg: "#fee2e2",
        target: "portal",
        webPath: "/provider/reports/payments/refunds",
      },
      {
        id: "payment-methods",
        name: "Payment Methods",
        description: "Card, cash, wallet split",
        icon: "wallet-outline",
        color: "#0f766e",
        bg: "#ccfbf1",
        target: "portal",
        webPath: "/provider/reports/payments/methods",
      },
      {
        id: "payouts",
        name: "Payouts",
        description: "Provider payout history",
        icon: "arrow-redo-outline",
        color: "#65a30d",
        bg: "#ecfccb",
        target: "portal",
        webPath: "/provider/reports/payments/payouts",
      },
      {
        id: "yoco-reconciliation",
        name: "Yoco reconciliation",
        description: "Terminal sync debugging",
        icon: "phone-portrait-outline",
        color: "#6b21a8",
        bg: "#f3e8ff",
        target: "portal",
        webPath: "/provider/reports/payments/yoco-reconciliation",
      },
    ],
  },
  {
    title: "Products",
    reports: [
      {
        id: "product-analytics",
        name: "Product & Inventory",
        description: "Top sellers and stock",
        icon: "cube-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "native",
        screen: "products",
      },
      {
        id: "inventory",
        name: "Inventory",
        description: "Stock levels by SKU",
        icon: "layers-outline",
        color: "#6366f1",
        bg: "#e0e7ff",
        target: "portal",
        webPath: "/provider/reports/products/inventory",
      },
      {
        id: "top-products",
        name: "Top Products",
        description: "Best sellers",
        icon: "ribbon-outline",
        color: "#c026d3",
        bg: "#fae8ff",
        target: "portal",
        webPath: "/provider/reports/products/top",
      },
    ],
  },
  {
    title: "Gift cards",
    reports: [
      {
        id: "gift-card-report",
        name: "Gift Card Report",
        description: "Sales and redemptions",
        icon: "gift-outline",
        color: "#a855f7",
        bg: "#f3e8ff",
        target: "native",
        screen: "gift-cards",
      },
    ],
  },
  {
    title: "Packages",
    reports: [
      {
        id: "package-sales",
        name: "Package Sales",
        description: "Sold packages and revenue",
        icon: "pricetag-outline",
        color: "#0f766e",
        bg: "#ccfbf1",
        target: "portal",
        webPath: "/provider/reports/packages/sales",
      },
      {
        id: "package-usage",
        name: "Package Usage",
        description: "Redemptions and balances",
        icon: "analytics-outline",
        color: "#0e7490",
        bg: "#cffafe",
        target: "portal",
        webPath: "/provider/reports/packages/usage",
      },
      {
        id: "packages-native",
        name: "Packages overview",
        description: "Combined package analytics (app)",
        icon: "layers-outline",
        color: "#14b8a6",
        bg: "#ccfbf1",
        target: "native",
        screen: "packages",
      },
    ],
  },
  {
    title: "Business",
    reports: [
      {
        id: "business-overview",
        name: "Business Overview",
        description: "Key metrics dashboard",
        icon: "pie-chart-outline",
        color: "#6366f1",
        bg: "#eef2ff",
        target: "portal",
        webPath: "/provider/reports/business/overview",
      },
      {
        id: "performance-dashboard",
        name: "Performance Dashboard",
        description: "KPIs at a glance",
        icon: "flash-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "portal",
        webPath: "/provider/reports/business/dashboard",
      },
      {
        id: "comparison",
        name: "Period Comparison",
        description: "Compare two periods",
        icon: "git-compare-outline",
        color: "#2563eb",
        bg: "#dbeafe",
        target: "portal",
        webPath: "/provider/reports/business/comparison",
      },
      {
        id: "business-native",
        name: "Business insights (app)",
        description: "Native overview with filters",
        icon: "stats-chart-outline",
        color: "#4f46e5",
        bg: "#e0e7ff",
        target: "native",
        screen: "business",
      },
      {
        id: "revenue-native",
        name: "Revenue overview (app)",
        description: "Revenue trends in the app",
        icon: "cash-outline",
        color: "#22c55e",
        bg: "#dcfce7",
        target: "native",
        screen: "revenue",
      },
    ],
  },
  {
    title: "More in app",
    reports: [
      {
        id: "analytics-tab",
        name: "Analytics",
        description: "Performance and trends",
        icon: "analytics-outline",
        color: "#8b5cf6",
        bg: "#ede9fe",
        target: "route",
        route: "/(app)/(tabs)/more/analytics",
      },
      {
        id: "activity-tab",
        name: "Activity",
        description: "Recent business activity",
        icon: "pulse-outline",
        color: "#0d9488",
        bg: "#ccfbf1",
        target: "route",
        route: "/(app)/(tabs)/more/activity",
      },
    ],
  },
];
