/**
 * Provider report navigation — mirrors `apps/web` provider reports hub.
 * All reports open in-app: native screens call `/api/provider/reports/*` (same handlers as the web portal).
 */
import Ionicons from "@expo/vector-icons/Ionicons";

export type ReportIon = keyof typeof Ionicons.glyphMap;

export type ProviderReportItem = {
  id: string;
  name: string;
  description: string;
  icon: ReportIon;
  color: string;
  bg: string;
} & (
  | { target: "native"; screen: string }
  | { target: "detail"; reportId: string }
  | { target: "route"; route: string }
);

export type ProviderReportCategory = { title: string; reports: ProviderReportItem[] };

export const PROVIDER_REPORT_CATEGORIES: ProviderReportCategory[] = [
  {
    title: "Sales & revenue",
    reports: [
      {
        id: "sales-summary",
        name: "Sales Summary",
        description: "Ledger net vs recorded takings, bookings, and service mix",
        icon: "stats-chart-outline",
        color: "#16a34a",
        bg: "#dcfce7",
        target: "detail",
        reportId: "sales-summary",
      },
      {
        id: "service-performance",
        name: "Sales by service",
        description: "Ledger net allocated per offering",
        icon: "cut-outline",
        color: "#d97706",
        bg: "#fef3c7",
        target: "native",
        screen: "services",
      },
      {
        id: "revenue-trends",
        name: "Revenue trends",
        description: "Ledger net vs visits by period",
        icon: "trending-up-outline",
        color: "#059669",
        bg: "#d1fae5",
        target: "detail",
        reportId: "revenue-trends",
      },
    ],
  },
  {
    title: "Staff",
    reports: [
      {
        id: "staff-performance",
        name: "Staff Performance",
        description: "Bookings, ledger revenue, and ratings by staff member",
        icon: "person-outline",
        color: "#4f46e5",
        bg: "#eef2ff",
        target: "native",
        screen: "staff",
      },
      {
        id: "staff-commission",
        name: "Commission Reports",
        description: "Commission breakdown by staff",
        icon: "cash-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "detail",
        reportId: "staff-commission",
      },
      {
        id: "staff-hours",
        name: "Hours & Attendance",
        description: "Worked hours and attendance",
        icon: "time-outline",
        color: "#0369a1",
        bg: "#e0f2fe",
        target: "detail",
        reportId: "staff-hours",
      },
    ],
  },
  {
    title: "Bookings",
    reports: [
      {
        id: "booking-summary",
        name: "Booking Summary",
        description: "Volume, status mix, trends",
        icon: "calendar-outline",
        color: "#2563eb",
        bg: "#dbeafe",
        target: "native",
        screen: "bookings",
      },
      {
        id: "booking-status",
        name: "Booking Status",
        description: "Lifecycle counts and ledger net by status",
        icon: "pie-chart-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "detail",
        reportId: "booking-status",
      },
      {
        id: "occupancy",
        name: "Occupancy",
        description: "Booked time vs staff schedule minutes",
        icon: "bar-chart-outline",
        color: "#0d9488",
        bg: "#ccfbf1",
        target: "detail",
        reportId: "occupancy",
      },
      {
        id: "cancellations",
        name: "Cancellations",
        description: "Rate, reasons, and ledger net in range",
        icon: "close-circle-outline",
        color: "#dc2626",
        bg: "#fee2e2",
        target: "detail",
        reportId: "cancellations",
      },
      {
        id: "no-shows",
        name: "No-Shows",
        description: "Missed appointments",
        icon: "alert-circle-outline",
        color: "#ea580c",
        bg: "#ffedd5",
        target: "detail",
        reportId: "no-shows",
      },
    ],
  },
  {
    title: "Clients",
    reports: [
      {
        id: "client-summary",
        name: "Client Summary",
        description: "Distinct clients, first visits, repeat visits in range",
        icon: "people-outline",
        color: "#db2777",
        bg: "#fce7f3",
        target: "detail",
        reportId: "client-summary",
      },
      {
        id: "client-retention",
        name: "Client Retention",
        description: "Repeat share & period-over-period retention",
        icon: "heart-outline",
        color: "#e11d48",
        bg: "#ffe4e6",
        target: "detail",
        reportId: "client-retention",
      },
      {
        id: "new-clients",
        name: "New Clients",
        description: "First-time customers",
        icon: "person-add-outline",
        color: "#0891b2",
        bg: "#cffafe",
        target: "detail",
        reportId: "new-clients",
      },
      {
        id: "client-lifetime-value",
        name: "Lifetime Value",
        description: "CLV and spend bands",
        icon: "trophy-outline",
        color: "#ca8a04",
        bg: "#fef9c3",
        target: "detail",
        reportId: "client-lifetime-value",
      },
    ],
  },
  {
    title: "Payments",
    reports: [
      {
        id: "payment-summary",
        name: "Payment Summary",
        description: "Booked value vs settled ledger funds & methods",
        icon: "card-outline",
        color: "#0284c7",
        bg: "#e0f2fe",
        target: "detail",
        reportId: "payment-summary",
      },
      {
        id: "end-of-day",
        name: "End of day",
        description: "Recorded takings by capture date (till-style)",
        icon: "today-outline",
        color: "#4338ca",
        bg: "#e0e7ff",
        target: "detail",
        reportId: "end-of-day",
      },
      {
        id: "refunds",
        name: "Refunds",
        description: "Ledger refunds & provider earnings reversals",
        icon: "return-down-back-outline",
        color: "#b91c1c",
        bg: "#fee2e2",
        target: "detail",
        reportId: "refunds",
      },
      {
        id: "payment-methods",
        name: "Payment Methods",
        description: "Settlement-window mix: gateways, till logs, wallet splits",
        icon: "wallet-outline",
        color: "#0f766e",
        bg: "#ccfbf1",
        target: "detail",
        reportId: "payment-methods",
      },
      {
        id: "payouts",
        name: "Payout earnings (ledger)",
        description: "Ledger earnings by settlement date — not bank payout history",
        icon: "arrow-redo-outline",
        color: "#65a30d",
        bg: "#ecfccb",
        target: "detail",
        reportId: "payouts",
      },
      {
        id: "yoco-reconciliation",
        name: "Yoco reconciliation",
        description: "Terminal captures vs booking payments (webhook check)",
        icon: "phone-portrait-outline",
        color: "#6b21a8",
        bg: "#f3e8ff",
        target: "detail",
        reportId: "yoco-reconciliation",
      },
      {
        id: "paystack-terminal-reconciliation",
        name: "Paystack Terminal reconciliation",
        description: "Terminal captures, allocations, holds, and payout readiness",
        icon: "card-outline",
        color: "#0d9488",
        bg: "#ccfbf1",
        target: "detail",
        reportId: "paystack-terminal-reconciliation",
      },
    ],
  },
  {
    title: "Product & inventory",
    reports: [
      {
        id: "product-analytics",
        name: "Product & Inventory",
        description: "Native catalog: stock and velocity",
        icon: "cube-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "native",
        screen: "products",
      },
      {
        id: "product-sales",
        name: "Product Sales",
        description: "Retail lines: appointment add-ons + paid orders (mixed date rules)",
        icon: "bag-outline",
        color: "#4f46e5",
        bg: "#e0e7ff",
        target: "detail",
        reportId: "product-sales",
      },
      {
        id: "inventory",
        name: "Product & inventory",
        description: "Products + variants; retail value & low/out alerts per API rules",
        icon: "layers-outline",
        color: "#6366f1",
        bg: "#e0e7ff",
        target: "detail",
        reportId: "inventory",
      },
      {
        id: "top-products",
        name: "Top Products",
        description: "Ranked by retail line revenue (bookings + paid orders)",
        icon: "ribbon-outline",
        color: "#c026d3",
        bg: "#fae8ff",
        target: "detail",
        reportId: "top-products",
      },
    ],
  },
  {
    title: "Gift cards",
    reports: [
      {
        id: "gift-card-report",
        name: "Gift card redemptions",
        description: "Captured redemptions at your business — not platform card sales",
        icon: "gift-outline",
        color: "#a855f7",
        bg: "#f3e8ff",
        target: "native",
        screen: "gift-cards",
      },
    ],
  },
  {
    title: "Packages & memberships",
    reports: [
      {
        id: "package-sales",
        name: "Package Sales",
        description: "Booked package line value by catalog package (scheduled window)",
        icon: "pricetag-outline",
        color: "#0f766e",
        bg: "#ccfbf1",
        target: "detail",
        reportId: "package-sales",
      },
      {
        id: "package-usage",
        name: "Package Usage",
        description: "Usage events and distinct clients (incl. group participants)",
        icon: "analytics-outline",
        color: "#0e7490",
        bg: "#cffafe",
        target: "detail",
        reportId: "package-usage",
      },
      {
        id: "packages-native",
        name: "Packages overview",
        description: "Active catalog packages — bookings & booked value in period",
        icon: "layers-outline",
        color: "#14b8a6",
        bg: "#ccfbf1",
        target: "native",
        screen: "packages",
      },
      {
        id: "membership-sales",
        name: "Membership sales",
        description: "Gross sales (liability), recognized earnings, active subscribers",
        icon: "card-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "detail",
        reportId: "membership-sales",
      },
    ],
  },
  {
    title: "Business overview",
    reports: [
      {
        id: "business-overview",
        name: "Business Overview",
        description: "Ledger earnings + scheduled bookings (period to date) — see facts on screen",
        icon: "pie-chart-outline",
        color: "#6366f1",
        bg: "#eef2ff",
        target: "native",
        screen: "business",
      },
      {
        id: "performance-dashboard",
        name: "Performance Dashboard",
        description: "Today / week / month ledger + lists (same API as web)",
        icon: "flash-outline",
        color: "#7c3aed",
        bg: "#ede9fe",
        target: "detail",
        reportId: "performance-dashboard",
      },
      {
        id: "comparison",
        name: "Period Comparison",
        description: "Ledger + bookings: current window vs prior full period",
        icon: "git-compare-outline",
        color: "#2563eb",
        bg: "#dbeafe",
        target: "detail",
        reportId: "comparison",
      },
      {
        id: "revenue-native",
        name: "Revenue overview (app)",
        description: "Ledger net, booking vs product split, booking-linked service/staff mix — same API facts as web",
        icon: "cash-outline",
        color: "#22c55e",
        bg: "#dcfce7",
        target: "native",
        screen: "revenue",
      },
    ],
  },
  {
    title: "More in app",
    reports: [
      {
        id: "analytics-tab",
        name: "Analytics",
        description: "Ledger net, booking counts, catalog offering totals — same facts as web",
        icon: "analytics-outline",
        color: "#8b5cf6",
        bg: "#ede9fe",
        target: "route",
        route: "/(app)/(tabs)/more/analytics",
      },
      {
        id: "activity-tab",
        name: "Activity",
        description: "Rolling timeline: bookings created, ledger earnings & payouts, reviews — same feed as dashboard",
        icon: "pulse-outline",
        color: "#0d9488",
        bg: "#ccfbf1",
        target: "route",
        route: "/(app)/(tabs)/more/activity",
      },
    ],
  },
];
