import slide1 from "../../../../public/images/pexels-alipazani-2878375 - Copy (1).jpg";
import slide2 from "../../../../public/images/pexels-steinportraits-1898555.jpg";
import slide3 from "../../../../public/images/pexels-cottonbro-3998404 (1).jpg";
import slide4 from "../../../../public/images/pexels-john-diez-7389075.jpg";

export const cardsData = [
    {
      id: 1,
      lat: 51.5074,
      lng: -0.1278,
      price: 786,
      slides: [
        { src: slide1, alt: "Slide 1" },
        { src: slide2, alt: "Slide 2" },
        { src: slide3, alt: "Slide 3" },
        { src: slide4, alt: "Slide 4" },
      ],
      content: {
        title: "Cozy London Apartment",
        subtitle: "City Views",
        dates: "Available Now",
        amountstatus: "£786 Total",
        ratings: "4.89",
        ratingsVisible: "true",
        guestfav: "true",
        iconType: "share",
      },
    },
    {
      id: 2,
      lat: 51.5080,
      lng: -0.1290,
      price: 650,
      slides: [
        { src: slide1, alt: "Slide 1" },
        { src: slide2, alt: "Slide 2" },
        { src: slide3, alt: "Slide 3" },
        { src: slide4, alt: "Slide 4" },
      ],
      content: {
        title: "Modern Studio in Westminster",
        subtitle: "Near Big Ben",
        dates: "Next week",
        amountstatus: "£650 Total",
        ratings: "4.75",
        ratingsVisible: "true",
        guestfav: "false",
        iconType: "share",
      },
    },
    {
      id: 3,
      lat: 51.5065,
      lng: -0.1260,
      price: 920,
      slides: [
        { src: slide1, alt: "Slide 1" },
        { src: slide2, alt: "Slide 2" },
        { src: slide3, alt: "Slide 3" },
        { src: slide4, alt: "Slide 4" },
      ],
      content: {
        title: "Luxurious Penthouse",
        subtitle: "Panoramic Views",
        dates: "Book Now",
        amountstatus: "£920 Total",
        ratings: "4.95",
        ratingsVisible: "true",
        guestfav: "true",
        iconType: "share",
      },
    },
    {
      id: 4,
      lat: 51.5090,
      lng: -0.1270,
      price: 550,
      slides: [
        { src: slide1, alt: "Slide 1" },
        { src: slide2, alt: "Slide 2" },
        { src: slide3, alt: "Slide 3" },
        { src: slide4, alt: "Slide 4" },
      ],
      content: {
        title: "Charming Notting Hill Flat",
        subtitle: "Quiet Neighborhood",
        dates: "This weekend",
        amountstatus: "£550 Total",
        ratings: "4.80",
        ratingsVisible: "true",
        guestfav: "false",
        iconType: "share",
      },
    },
    {
      id: 5,
      lat: 51.5085,
      lng: -0.1295,
      price: 700,
      slides: [
        { src: slide1, alt: "Slide 1" },
        { src: slide2, alt: "Slide 2" },
        { src: slide3, alt: "Slide 3" },
        { src: slide4, alt: "Slide 4" },
      ],
      content: {
        title: "Stylish Soho Loft",
        subtitle: "Heart of London",
        dates: "Next month",
        amountstatus: "£700 Total",
        ratings: "4.85",
        ratingsVisible: "true",
        guestfav: "true",
        iconType: "share",
      },
    },
    {
      id: 6,
      lat: 51.5100,
      lng: -0.1310,
      price: 600,
      slides: [
        { src: slide1, alt: "Slide 1" },
        { src: slide2, alt: "Slide 2" },
        { src: slide3, alt: "Slide 3" },
        { src: slide4, alt: "Slide 4" },
      ],
      content: {
        title: "Cozy Camden Townhouse",
        subtitle: "Artistic Neighborhood",
        dates: "Available Now",
        amountstatus: "£600 Total",
        ratings: "4.70",
        ratingsVisible: "true",
        guestfav: "false",
        iconType: "share",
      },
    },
];