import { NextRequest } from "next/server";
import { getSupabaseServer } from "@/lib/supabase/server";
import { requireRoleInApi, successResponse, handleApiError } from "@/lib/supabase/api-helpers";

/**
 * GET /api/me/tax-documents
 * 
 * Get current user's tax documents by year
 */
export async function GET(request: NextRequest) {
  try {
    await requireRoleInApi(['customer', 'provider_owner', 'provider_staff', 'superadmin'], request);
    const _supabase = await getSupabaseServer();

    const { searchParams } = new URL(request.url);
    const year = searchParams.get("year");

    // For now, return empty array as tax documents would be generated by the system
    // In the future, this would query a tax_documents table or generate documents on demand
    const currentYear = new Date().getFullYear();
    const years = Array.from({ length: 5 }, (_, i) => currentYear - i);

    const documents = years.map((y) => ({
      year: y,
      document_url: null,
      issued_at: null,
      status: "not_issued",
    }));

    if (year) {
      const yearInt = parseInt(year);
      const filtered = documents.filter((d) => d.year === yearInt);
      return successResponse(filtered);
    }

    return successResponse(documents);
  } catch (error) {
    return handleApiError(error, "Failed to fetch tax documents");
  }
}
