"use client";

import React, { memo, useCallback } from "react";
import { Plus } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  DroppableTimeSlot,
} from "@/components/provider-portal/DragDropCalendar";
import { slotIsOutsideWeekly, type WeeklyHours } from "@beautonomi/utils";
import { HOUR_HEIGHT } from "./constants";
import { parseScheduledTime } from "./utils";

interface GestureLayerProps {
  timeSlots: string[];
  date: Date;
  dateStr: string;
  staffId: string;
  useMangomintMode: boolean;
  highContrast: boolean;
  workStart: number;
  workEnd: number;
  locationOperatingHours?: Record<string, { open: string; close: string; closed: boolean }> | null;
  staffWorkingHours?: Record<string, { open: string; close: string; closed?: boolean }> | null;
  onTimeSlotClick: (date: Date, time: string, staffId: string) => void;
}

function GestureLayerComponent({
  timeSlots,
  date,
  dateStr,
  staffId,
  useMangomintMode,
  highContrast,
  workStart,
  workEnd,
  locationOperatingHours,
  staffWorkingHours,
  onTimeSlotClick,
}: GestureLayerProps) {
  const handleSlotClick = useCallback(
    (time: string) => onTimeSlotClick(date, time, staffId),
    [date, staffId, onTimeSlotClick],
  );

  return (
    <>
      {timeSlots.map((time) => {
        // §Calendar-hours: pass the slot's full minute range so opens at
        // 09:30 (or sub-hour closes) are evaluated minute-accurately instead
        // of being bucketed to the hour. Slots generated by `generateTimeSlots`
        // are 1-hour blocks; use overlap-mode for shading so the 09:00 row
        // stays clickable when the business opens at 09:30.
        const { hour, minute } = parseScheduledTime(time);
        const slotStartMin = hour * 60 + minute;
        const slotEndMin = slotStartMin + 60;
        const outsideLocation = locationOperatingHours
          ? slotIsOutsideWeekly(
              date,
              slotStartMin,
              slotEndMin,
              locationOperatingHours as WeeklyHours,
              "overlap",
            )
          : false;
        const hasStaffSchedule =
          staffWorkingHours != null && Object.keys(staffWorkingHours).length > 0;
        const outsideStaff = hasStaffSchedule
          ? slotIsOutsideWeekly(
              date,
              slotStartMin,
              slotEndMin,
              staffWorkingHours as WeeklyHours,
              "overlap",
            )
          : false;
        // With an explicit weekly schedule, use staff hours; otherwise fall back to
        // location hours (or merged team hours passed from StaffColumn / DateColumn).
        const staffIsWorking = hasStaffSchedule ? !outsideStaff : !outsideLocation;
        const businessClosed = outsideLocation && !staffIsWorking;
        const staffOff = !businessClosed && outsideStaff;
        const isNonWorking = businessClosed;
        const isHighContrast = useMangomintMode && highContrast;
        const blockedPattern =
          isHighContrast
            ? "repeating-linear-gradient(135deg, #1f2937 0px, #1f2937 6px, #374151 6px, #374151 12px)"
            : "repeating-linear-gradient(135deg, #e5e7eb 0px, #e5e7eb 6px, #d1d5db 6px, #d1d5db 12px)";
        const staffOffPattern = "repeating-linear-gradient(135deg, #f0f0f0 0px, #f0f0f0 6px, #e8e8e8 6px, #e8e8e8 12px)";

        return (
          <DroppableTimeSlot
            key={time}
            date={dateStr}
            time={time}
            staffId={staffId}
            className={cn(
              "border-b border-gray-200 transition-colors relative group/slot",
              isNonWorking
                ? "cursor-not-allowed border-l-[5px] border-l-amber-500/90 bg-amber-50/40"
                : staffOff
                  ? "cursor-pointer border-l-[3px] border-l-gray-300 bg-gray-50/60"
                  : "cursor-pointer hover:bg-gray-50/70",
            )}
          >
            <div
              className="relative z-[1]"
              style={{
                height: `${HOUR_HEIGHT}px`,
                backgroundColor: isNonWorking && !isHighContrast ? "#f3f4f6" : staffOff ? "#fafafa" : undefined,
                backgroundImage: isNonWorking ? blockedPattern : staffOff ? staffOffPattern : undefined,
              }}
              onClick={isNonWorking ? undefined : () => handleSlotClick(time)}
            >
              {!isNonWorking && !staffOff && (
                <div className="absolute inset-0 opacity-0 group-hover/slot:opacity-100 transition-opacity pointer-events-none flex items-center justify-center">
                  <Plus className="w-5 h-5 text-gray-400" />
                </div>
              )}
              {staffOff && (
                <div className="absolute inset-0 opacity-0 group-hover/slot:opacity-100 transition-opacity pointer-events-none flex items-center justify-center">
                  <Plus className="w-5 h-5 text-gray-300" />
                </div>
              )}
              {isNonWorking && (
                <div className="absolute inset-0 pointer-events-none flex items-center justify-center">
                  <span className="text-[10px] font-bold uppercase tracking-wide text-amber-900/70 bg-white/85 px-1.5 py-0.5 rounded border border-amber-200 shadow-sm">
                    Closed
                  </span>
                </div>
              )}
            </div>
          </DroppableTimeSlot>
        );
      })}
    </>
  );
}

export const GestureLayer = memo(GestureLayerComponent, (prev, next) =>
  prev.dateStr === next.dateStr &&
  prev.staffId === next.staffId &&
  prev.workStart === next.workStart &&
  prev.workEnd === next.workEnd &&
  prev.highContrast === next.highContrast &&
  prev.useMangomintMode === next.useMangomintMode &&
  prev.timeSlots.length === next.timeSlots.length &&
  prev.locationOperatingHours === next.locationOperatingHours &&
  prev.staffWorkingHours === next.staffWorkingHours &&
  prev.onTimeSlotClick === next.onTimeSlotClick,
);

GestureLayer.displayName = "GestureLayer";
