-- Notification Templates Table
-- Stores reusable notification templates for the platform

CREATE TABLE IF NOT EXISTS public.notification_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  channels TEXT[] NOT NULL DEFAULT ARRAY['push']::TEXT[],
  -- Channel-specific content
  email_subject TEXT,
  email_body TEXT,
  sms_body TEXT,
  live_activities_config JSONB,
  -- Template metadata
  variables TEXT[] DEFAULT ARRAY[]::TEXT[],
  url TEXT,
  image TEXT,
  onesignal_template_id TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT valid_channels CHECK (
    channels <@ ARRAY['push', 'email', 'sms', 'live_activities']::TEXT[]
  )
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_notification_templates_key ON public.notification_templates(key);
CREATE INDEX IF NOT EXISTS idx_notification_templates_enabled ON public.notification_templates(enabled) WHERE enabled = true;

-- Updated_at trigger
DROP TRIGGER IF EXISTS update_notification_templates_updated_at ON public.notification_templates;
CREATE TRIGGER update_notification_templates_updated_at
  BEFORE UPDATE ON public.notification_templates
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Only superadmins can manage notification templates
DROP POLICY IF EXISTS "Superadmins can manage notification templates" ON public.notification_templates;
CREATE POLICY "Superadmins can manage notification templates"
  ON public.notification_templates FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role = 'superadmin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role = 'superadmin'
    )
  );

-- Preloaded Notification Templates for Beautonomi Platform
-- These templates cover common notification scenarios for a beauty services booking platform
-- Using INSERT ... ON CONFLICT to handle existing templates gracefully

INSERT INTO public.notification_templates (key, title, body, channels, email_subject, email_body, sms_body, variables, url, enabled, description) VALUES
-- Booking Confirmations
('booking_confirmed', 
 'Booking Confirmed', 
 'Your booking with {{provider_name}} on {{booking_date}} at {{booking_time}} has been confirmed!',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Booking Confirmed - {{provider_name}}',
 '<h2>Booking Confirmed</h2><p>Your booking has been confirmed!</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Services:</strong> {{services}}</p><p><strong>Total:</strong> {{total_amount}}</p><p>Booking Number: {{booking_number}}</p>',
 'Booking confirmed! {{provider_name}} on {{booking_date}} at {{booking_time}}. Total: {{total_amount}}. Booking #{{booking_number}}',
 ARRAY['provider_name', 'booking_date', 'booking_time', 'services', 'total_amount', 'booking_number']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when a booking is confirmed by the provider'),

('booking_reminder_24h',
 'Booking Reminder - Tomorrow',
 'Reminder: You have a booking with {{provider_name}} tomorrow at {{booking_time}}',
 ARRAY['push', 'email']::TEXT[],
 'Reminder: Booking Tomorrow - {{provider_name}}',
 '<h2>Booking Reminder</h2><p>This is a friendly reminder about your upcoming booking.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Location:</strong> {{location}}</p>',
 NULL,
 ARRAY['provider_name', 'booking_date', 'booking_time', 'location']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent 24 hours before a booking'),

('booking_reminder_2h',
 'Booking Reminder - In 2 Hours',
 'Your booking with {{provider_name}} is in 2 hours at {{booking_time}}',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 'Reminder: Booking with {{provider_name}} in 2 hours at {{booking_time}}. Location: {{location}}',
 ARRAY['provider_name', 'booking_time', 'location']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent 2 hours before a booking'),

-- Booking Changes
('booking_cancelled',
 'Booking Cancelled',
 'Your booking with {{provider_name}} on {{booking_date}} has been cancelled. {{refund_info}}',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Booking Cancelled - {{provider_name}}',
 '<h2>Booking Cancelled</h2><p>Your booking has been cancelled.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p>{{refund_info}}</p>',
 'Booking cancelled: {{provider_name}} on {{booking_date}}. {{refund_info}} Booking #{{booking_number}}',
 ARRAY['provider_name', 'booking_date', 'booking_number', 'refund_info']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when a booking is cancelled'),

('booking_rescheduled',
 'Booking Rescheduled',
 'Your booking with {{provider_name}} has been rescheduled to {{new_date}} at {{new_time}}',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Booking Rescheduled - {{provider_name}}',
 '<h2>Booking Rescheduled</h2><p>Your booking has been rescheduled.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>New Date:</strong> {{new_date}}</p><p><strong>New Time:</strong> {{new_time}}</p><p><strong>Previous:</strong> {{old_date}} at {{old_time}}</p>',
 'Booking rescheduled: {{provider_name}} now on {{new_date}} at {{new_time}} (was {{old_date}} {{old_time}})',
 ARRAY['provider_name', 'new_date', 'new_time', 'old_date', 'old_time']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when a booking is rescheduled'),

-- Payment Notifications
('payment_successful',
 'Payment Successful',
 'Your payment of {{amount}} for booking #{{booking_number}} has been processed successfully',
 ARRAY['push', 'email']::TEXT[],
 'Payment Successful - Booking #{{booking_number}}',
 '<h2>Payment Successful</h2><p>Your payment has been processed successfully.</p><p><strong>Amount:</strong> {{amount}}</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Payment Method:</strong> {{payment_method}}</p><p><strong>Transaction ID:</strong> {{transaction_id}}</p>',
 NULL,
 ARRAY['amount', 'booking_number', 'payment_method', 'transaction_id']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when a payment is successfully processed'),

('payment_failed',
 'Payment Failed',
 'Your payment of {{amount}} for booking #{{booking_number}} failed. Please update your payment method',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Payment Failed - Action Required',
 '<h2>Payment Failed</h2><p>We were unable to process your payment.</p><p><strong>Amount:</strong> {{amount}}</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Reason:</strong> {{failure_reason}}</p><p>Please update your payment method to complete your booking.</p>',
 'Payment failed for booking #{{booking_number}}. Amount: {{amount}}. Please update payment method.',
 ARRAY['amount', 'booking_number', 'failure_reason']::TEXT[],
 '/bookings/{{booking_id}}/payment',
 true,
 'Sent when a payment fails'),

('refund_processed',
 'Refund Processed',
 'A refund of {{amount}} for booking #{{booking_number}} has been processed and will appear in your account within 3-5 business days',
 ARRAY['push', 'email']::TEXT[],
 'Refund Processed - Booking #{{booking_number}}',
 '<h2>Refund Processed</h2><p>Your refund has been processed.</p><p><strong>Amount:</strong> {{amount}}</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Reason:</strong> {{refund_reason}}</p><p>The refund will appear in your account within 3-5 business days.</p>',
 NULL,
 ARRAY['amount', 'booking_number', 'refund_reason']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when a refund is processed'),

-- Provider Notifications
('provider_booking_request',
 'New Booking Request',
 'You have a new booking request from {{customer_name}} for {{booking_date}} at {{booking_time}}',
 ARRAY['push', 'email']::TEXT[],
 'New Booking Request - {{customer_name}}',
 '<h2>New Booking Request</h2><p>You have received a new booking request.</p><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Services:</strong> {{services}}</p><p><strong>Total:</strong> {{total_amount}}</p>',
 NULL,
 ARRAY['customer_name', 'booking_date', 'booking_time', 'services', 'total_amount']::TEXT[],
 '/provider/bookings/{{booking_id}}',
 true,
 'Sent to provider when a new booking is requested'),

('provider_payout_processed',
 'Payout Processed',
 'Your payout of {{amount}} has been processed and transferred to your account',
 ARRAY['push', 'email']::TEXT[],
 'Payout Processed - {{amount}}',
 '<h2>Payout Processed</h2><p>Your payout has been successfully processed.</p><p><strong>Amount:</strong> {{amount}}</p><p><strong>Payout Date:</strong> {{payout_date}}</p><p><strong>Transaction ID:</strong> {{transaction_id}}</p>',
 NULL,
 ARRAY['amount', 'payout_date', 'transaction_id']::TEXT[],
 '/provider/payouts',
 true,
 'Sent to provider when a payout is processed'),

-- Review Reminders
('review_reminder',
 'How was your service?',
 'How was your experience with {{provider_name}}? Share your feedback to help others!',
 ARRAY['push', 'email']::TEXT[],
 'Share Your Experience - {{provider_name}}',
 '<h2>How was your service?</h2><p>We''d love to hear about your experience with {{provider_name}}!</p><p>Your feedback helps other customers and helps {{provider_name}} improve their services.</p><p>Booking: {{booking_date}} - {{services}}</p>',
 NULL,
 ARRAY['provider_name', 'booking_date', 'services']::TEXT[],
 '/bookings/{{booking_id}}/review',
 true,
 'Sent after a completed booking to request a review'),

-- Account & Security
('password_reset',
 'Reset Your Password',
 'Click the link below to reset your password. This link will expire in 1 hour.',
 ARRAY['email']::TEXT[],
 'Reset Your Password - Beautonomi',
 '<h2>Reset Your Password</h2><p>You requested to reset your password. Click the button below to create a new password.</p><p>This link will expire in 1 hour.</p><p>If you didn''t request this, please ignore this email.</p>',
 NULL,
 ARRAY[]::TEXT[],
 '/reset-password?token={{reset_token}}',
 true,
 'Sent when user requests password reset'),

('email_verification',
 'Verify Your Email',
 'Please verify your email address to complete your account setup',
 ARRAY['email']::TEXT[],
 'Verify Your Email - Beautonomi',
 '<h2>Verify Your Email</h2><p>Thank you for signing up! Please verify your email address to complete your account setup.</p><p>Click the button below to verify your email.</p>',
 NULL,
 ARRAY[]::TEXT[],
 '/verify-email?token={{verification_token}}',
 true,
 'Sent when a new user signs up'),

('account_suspended',
 'Account Suspended',
 'Your account has been temporarily suspended. Please contact support for more information',
 ARRAY['email', 'push']::TEXT[],
 'Account Suspended - Action Required',
 '<h2>Account Suspended</h2><p>Your account has been temporarily suspended.</p><p><strong>Reason:</strong> {{suspension_reason}}</p><p>Please contact our support team if you have any questions.</p>',
 NULL,
 ARRAY['suspension_reason']::TEXT[],
 '/support',
 true,
 'Sent when an account is suspended'),

-- Promotional & Updates
('welcome_message',
 'Welcome to Beautonomi!',
 'Welcome to Beautonomi! Discover amazing beauty services and book your first appointment today',
 ARRAY['push', 'email']::TEXT[],
 'Welcome to Beautonomi!',
 '<h2>Welcome to Beautonomi!</h2><p>We''re excited to have you join our community!</p><p>Discover amazing beauty services, book appointments, and enjoy a seamless experience.</p><p>Get started by browsing our providers and booking your first service.</p>',
 NULL,
 ARRAY[]::TEXT[],
 '/search',
 true,
 'Sent to new users after signup'),

('promotion_available',
 'Special Offer Available',
 '{{promotion_title}}: {{promotion_description}}. Use code {{promo_code}} to save {{discount_amount}}!',
 ARRAY['push', 'email']::TEXT[],
 'Special Offer: {{promotion_title}}',
 '<h2>Special Offer</h2><p>{{promotion_description}}</p><p><strong>Promo Code:</strong> {{promo_code}}</p><p><strong>Discount:</strong> {{discount_amount}}</p><p>Valid until {{expiry_date}}</p>',
 NULL,
 ARRAY['promotion_title', 'promotion_description', 'promo_code', 'discount_amount', 'expiry_date']::TEXT[],
 '/promotions/{{promotion_id}}',
 true,
 'Sent when a new promotion is available'),

-- Service Updates
('service_completed',
 'Service Completed',
 'Your service with {{provider_name}} has been completed. Thank you for choosing Beautonomi!',
 ARRAY['push', 'email']::TEXT[],
 'Service Completed - {{provider_name}}',
 '<h2>Service Completed</h2><p>Thank you for choosing Beautonomi!</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Services:</strong> {{services}}</p><p>We hope you had a great experience. Don''t forget to leave a review!</p>',
 NULL,
 ARRAY['provider_name', 'services']::TEXT[],
 '/bookings/{{booking_id}}/review',
 true,
 'Sent when a service is marked as completed'),

('provider_new_review',
 'New Review Received',
 'You received a new {{rating}}-star review from {{customer_name}}',
 ARRAY['push', 'email']::TEXT[],
 'New Review - {{rating}} Stars',
 '<h2>New Review Received</h2><p>You received a new review!</p><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Rating:</strong> {{rating}} stars</p><p><strong>Review:</strong> {{review_text}}</p>',
 NULL,
 ARRAY['customer_name', 'rating', 'review_text']::TEXT[],
 '/provider/reviews',
 true,
 'Sent to provider when they receive a new review'),

-- Travel Fee Notifications
('travel_fee_applied',
 'Travel Fee Applied',
 'A travel fee of {{travel_fee}} has been added to your booking for {{distance}}km',
 ARRAY['push', 'email']::TEXT[],
 'Travel Fee Applied to Your Booking',
 '<h2>Travel Fee Applied</h2><p>A travel fee has been added to your booking.</p><p><strong>Travel Fee:</strong> {{travel_fee}}</p><p><strong>Distance:</strong> {{distance}}km</p><p><strong>Total Booking Amount:</strong> {{total_amount}}</p>',
 NULL,
 ARRAY['travel_fee', 'distance', 'total_amount']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when a travel fee is applied to a booking'),

-- Membership & Subscriptions
('membership_renewal_reminder',
 'Membership Renewal Reminder',
 'Your {{membership_name}} membership will renew on {{renewal_date}}. Total: {{renewal_amount}}',
 ARRAY['push', 'email']::TEXT[],
 'Membership Renewal Reminder',
 '<h2>Membership Renewal</h2><p>Your membership is set to renew soon.</p><p><strong>Membership:</strong> {{membership_name}}</p><p><strong>Renewal Date:</strong> {{renewal_date}}</p><p><strong>Amount:</strong> {{renewal_amount}}</p>',
 NULL,
 ARRAY['membership_name', 'renewal_date', 'renewal_amount']::TEXT[],
 '/membership',
 true,
 'Sent before membership renewal'),

('membership_activated',
 'Membership Activated',
 'Your {{membership_name}} membership has been activated! Enjoy your benefits',
 ARRAY['push', 'email']::TEXT[],
 'Membership Activated - {{membership_name}}',
 '<h2>Membership Activated</h2><p>Congratulations! Your membership has been activated.</p><p><strong>Membership:</strong> {{membership_name}}</p><p><strong>Benefits:</strong> {{benefits}}</p><p>Start enjoying your membership benefits today!</p>',
 NULL,
 ARRAY['membership_name', 'benefits']::TEXT[],
 '/membership',
 true,
 'Sent when a membership is activated'),

-- Gift Cards
('gift_card_purchased',
 'Gift Card Purchased',
 'You purchased a gift card worth {{gift_card_amount}} for {{recipient_name}}. Code: {{gift_card_code}}',
 ARRAY['push', 'email']::TEXT[],
 'Gift Card Purchased',
 '<h2>Gift Card Purchased</h2><p>Thank you for your purchase!</p><p><strong>Amount:</strong> {{gift_card_amount}}</p><p><strong>Recipient:</strong> {{recipient_name}}</p><p><strong>Gift Card Code:</strong> {{gift_card_code}}</p><p>The recipient will receive an email with instructions on how to use the gift card.</p>',
 NULL,
 ARRAY['gift_card_amount', 'recipient_name', 'gift_card_code']::TEXT[],
 '/gift-cards',
 true,
 'Sent when a gift card is purchased'),

('gift_card_received',
 'You Received a Gift Card!',
 '{{sender_name}} sent you a gift card worth {{gift_card_amount}}! Code: {{gift_card_code}}',
 ARRAY['push', 'email']::TEXT[],
 'You Received a Gift Card!',
 '<h2>You Received a Gift Card!</h2><p>{{sender_name}} has sent you a gift card!</p><p><strong>Amount:</strong> {{gift_card_amount}}</p><p><strong>Gift Card Code:</strong> {{gift_card_code}}</p><p><strong>Message:</strong> {{message}}</p><p>Use this code at checkout to redeem your gift card.</p>',
 NULL,
 ARRAY['sender_name', 'gift_card_amount', 'gift_card_code', 'message']::TEXT[],
 '/gift-cards/redeem',
 true,
 'Sent when a user receives a gift card'),

-- Support & Messages
('new_message',
 'New Message',
 'You have a new message from {{sender_name}}',
 ARRAY['push', 'email']::TEXT[],
 'New Message from {{sender_name}}',
 '<h2>New Message</h2><p>You have a new message from {{sender_name}}.</p><p><strong>Message:</strong> {{message_preview}}</p>',
 NULL,
 ARRAY['sender_name', 'message_preview']::TEXT[],
 '/messages/{{conversation_id}}',
 true,
 'Sent when a user receives a new message'),

('support_ticket_created',
 'Support Ticket Created',
 'Your support ticket #{{ticket_number}} has been created. We''ll get back to you soon',
 ARRAY['push', 'email']::TEXT[],
 'Support Ticket Created - #{{ticket_number}}',
 '<h2>Support Ticket Created</h2><p>Your support ticket has been created successfully.</p><p><strong>Ticket Number:</strong> {{ticket_number}}</p><p><strong>Subject:</strong> {{ticket_subject}}</p><p>We''ll review your request and get back to you as soon as possible.</p>',
 NULL,
 ARRAY['ticket_number', 'ticket_subject']::TEXT[],
 '/support/tickets/{{ticket_id}}',
 true,
 'Sent when a support ticket is created'),

('support_ticket_updated',
 'Support Ticket Update',
 'Your support ticket #{{ticket_number}} has been updated. {{update_message}}',
 ARRAY['push', 'email']::TEXT[],
 'Support Ticket Update - #{{ticket_number}}',
 '<h2>Support Ticket Update</h2><p>Your support ticket has been updated.</p><p><strong>Ticket Number:</strong> {{ticket_number}}</p><p><strong>Update:</strong> {{update_message}}</p>',
 NULL,
 ARRAY['ticket_number', 'update_message']::TEXT[],
 '/support/tickets/{{ticket_id}}',
 true,
 'Sent when a support ticket is updated'),

-- Provider Onboarding
('provider_onboarding_welcome',
 'Welcome to Beautonomi Provider Network',
 'Welcome! Complete your profile to start accepting bookings and growing your business',
 ARRAY['push', 'email']::TEXT[],
 'Welcome to Beautonomi Provider Network',
 '<h2>Welcome to Beautonomi!</h2><p>We''re excited to have you join our provider network!</p><p>Complete your profile setup to start accepting bookings and growing your business.</p><p>Next steps:</p><ul><li>Complete your profile</li><li>Add your services</li><li>Set your availability</li><li>Upload photos</li></ul>',
 NULL,
 ARRAY[]::TEXT[],
 '/provider/onboarding',
 true,
 'Sent to new providers after signup'),

('provider_profile_approved',
 'Profile Approved',
 'Congratulations! Your provider profile has been approved. You can now start accepting bookings',
 ARRAY['push', 'email']::TEXT[],
 'Profile Approved - Start Accepting Bookings',
 '<h2>Profile Approved</h2><p>Great news! Your provider profile has been approved.</p><p>You can now start accepting bookings from customers.</p><p>Make sure to:</p><ul><li>Keep your availability updated</li><li>Respond to booking requests promptly</li><li>Provide excellent service</li></ul>',
 NULL,
 ARRAY[]::TEXT[],
 '/provider/dashboard',
 true,
 'Sent when a provider profile is approved'),

('provider_profile_rejected',
 'Profile Review Required',
 'Your provider profile needs some updates before it can be approved. {{rejection_reason}}',
 ARRAY['push', 'email']::TEXT[],
 'Profile Review Required',
 '<h2>Profile Review Required</h2><p>Your provider profile needs some updates before it can be approved.</p><p><strong>Reason:</strong> {{rejection_reason}}</p><p>Please update your profile and resubmit for review.</p>',
 NULL,
 ARRAY['rejection_reason']::TEXT[],
 '/provider/profile/edit',
 true,
 'Sent when a provider profile is rejected and needs updates'),

-- At-Home Service Notifications
('provider_en_route_home',
 'Provider On The Way',
 '{{provider_name}} is on the way to your location. Estimated arrival: {{estimated_arrival_time}}',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 '{{provider_name}} is on the way! ETA: {{estimated_arrival_time}}. Please ensure someone is available at {{service_address}}',
 ARRAY['provider_name', 'estimated_arrival_time', 'service_address']::TEXT[],
 '/bookings/{{booking_id}}/track',
 true,
 'Sent when provider starts traveling to customer location (at-home service)'),

('provider_arriving_soon_home',
 'Provider Arriving Soon',
 '{{provider_name}} will arrive at your location in approximately {{minutes}} minutes',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 '{{provider_name}} arriving in {{minutes}} minutes at {{service_address}}. Please be ready!',
 ARRAY['provider_name', 'minutes', 'service_address']::TEXT[],
 '/bookings/{{booking_id}}/track',
 true,
 'Sent 15 minutes before provider arrival (at-home service)'),

('provider_arrived_home',
 'Provider Has Arrived',
 '{{provider_name}} has arrived at your location. Please let them in',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 '{{provider_name}} has arrived at {{service_address}}. Please let them in!',
 ARRAY['provider_name', 'service_address']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when provider arrives at customer location (at-home service)'),

('home_service_location_details',
 'Service Location Details',
 'Your at-home service with {{provider_name}} will be at {{service_address}}. Please ensure the location is accessible',
 ARRAY['push', 'email']::TEXT[],
 'Service Location Details - {{provider_name}}',
 '<h2>Service Location Details</h2><p>Your at-home service details:</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Address:</strong> {{service_address}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Special Instructions:</strong> {{special_instructions}}</p><p>Please ensure the location is accessible and someone will be available.</p>',
 NULL,
 ARRAY['provider_name', 'service_address', 'booking_date', 'booking_time', 'special_instructions']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when at-home service location is confirmed'),

('home_service_location_required',
 'Service Location Required',
 'Please provide your service address for your at-home booking with {{provider_name}} on {{booking_date}}',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Service Location Required - Action Needed',
 '<h2>Service Location Required</h2><p>To complete your at-home service booking, please provide your service address.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p>Please update your booking with the service address.</p>',
 'Please provide service address for {{provider_name}} on {{booking_date}} at {{booking_time}}. Update booking now.',
 ARRAY['provider_name', 'booking_date', 'booking_time']::TEXT[],
 '/bookings/{{booking_id}}/edit',
 true,
 'Sent when at-home booking needs service address'),

('home_service_location_changed',
 'Service Location Changed',
 'The service location for your booking with {{provider_name}} has been updated to {{new_address}}',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Service Location Changed',
 '<h2>Service Location Changed</h2><p>The service location for your booking has been updated.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>New Address:</strong> {{new_address}}</p><p><strong>Previous Address:</strong> {{old_address}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p>',
 'Service location changed: {{new_address}} (was {{old_address}}). {{provider_name}} on {{booking_date}} at {{booking_time}}',
 ARRAY['provider_name', 'new_address', 'old_address', 'booking_date', 'booking_time']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when at-home service location is changed'),

-- At-Salon Service Notifications
('salon_directions',
 'Directions to Salon',
 'Your appointment with {{provider_name}} is at {{salon_name}}. Address: {{salon_address}}. Directions: {{directions_url}}',
 ARRAY['push', 'email']::TEXT[],
 'Directions to {{salon_name}}',
 '<h2>Directions to Salon</h2><p>Your appointment details:</p><p><strong>Salon:</strong> {{salon_name}}</p><p><strong>Address:</strong> {{salon_address}}</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Parking:</strong> {{parking_info}}</p><p><a href="{{directions_url}}">Get Directions</a></p>',
 NULL,
 ARRAY['provider_name', 'salon_name', 'salon_address', 'booking_date', 'booking_time', 'parking_info', 'directions_url']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent with salon location and directions (at-salon service)'),

('salon_arrival_reminder',
 'Arrival Reminder - Salon',
 'Please arrive at {{salon_name}} 10 minutes before your {{booking_time}} appointment with {{provider_name}}',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 'Arrival reminder: {{salon_name}} at {{booking_time}} with {{provider_name}}. Please arrive 10 mins early. Address: {{salon_address}}',
 ARRAY['salon_name', 'booking_time', 'provider_name', 'salon_address']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent 1 hour before salon appointment'),

('customer_arrived_salon',
 'You Have Arrived',
 'Welcome to {{salon_name}}! {{provider_name}} will be with you shortly',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['salon_name', 'provider_name']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when customer checks in at salon'),

('salon_waiting_area',
 'Waiting Area Information',
 'You''re checked in at {{salon_name}}. Please wait in the {{waiting_area}}. {{provider_name}} will call you when ready',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['salon_name', 'waiting_area', 'provider_name']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when customer is in waiting area at salon'),

-- Service Status Updates
('service_started',
 'Service Started',
 'Your service with {{provider_name}} has started. Estimated duration: {{service_duration}}',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['provider_name', 'service_duration']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when service begins'),

('service_in_progress',
 'Service In Progress',
 'Your service with {{provider_name}} is in progress. We hope you''re enjoying your experience!',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['provider_name']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent during service (optional mid-service check-in)'),

('service_almost_done',
 'Service Almost Complete',
 'Your service with {{provider_name}} is almost complete. Estimated {{remaining_time}} remaining',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['provider_name', 'remaining_time']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when service is nearing completion'),

('service_extended',
 'Service Extended',
 'Your service with {{provider_name}} has been extended by {{extension_time}}. New end time: {{new_end_time}}',
 ARRAY['push', 'email']::TEXT[],
 'Service Extended - {{provider_name}}',
 '<h2>Service Extended</h2><p>Your service has been extended.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Extension:</strong> {{extension_time}}</p><p><strong>New End Time:</strong> {{new_end_time}}</p><p><strong>Additional Charge:</strong> {{additional_charge}}</p>',
 NULL,
 ARRAY['provider_name', 'extension_time', 'new_end_time', 'additional_charge']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when service duration is extended'),

-- Provider Status Updates
('provider_running_late',
 'Provider Running Late',
 '{{provider_name}} is running {{delay_minutes}} minutes late. We apologize for the inconvenience. New arrival time: {{new_arrival_time}}',
 ARRAY['push', 'sms']::TEXT[],
 'Provider Running Late - {{provider_name}}',
 '<h2>Service Update</h2><p>{{provider_name}} is running {{delay_minutes}} minutes late.</p><p><strong>Original Time:</strong> {{original_time}}</p><p><strong>New Arrival Time:</strong> {{new_arrival_time}}</p><p>We apologize for any inconvenience. Thank you for your patience.</p>',
 '{{provider_name}} running {{delay_minutes}} mins late. New arrival: {{new_arrival_time}}. Sorry for the delay!',
 ARRAY['provider_name', 'delay_minutes', 'new_arrival_time', 'original_time']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when provider is running late'),

('provider_arrived_early',
 'Provider Arrived Early',
 '{{provider_name}} has arrived early and is ready to start your service',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['provider_name']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when provider arrives early'),

('provider_location_shared',
 'Provider Location Shared',
 '{{provider_name}} has shared their live location. Track their arrival: {{tracking_url}}',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['provider_name', 'tracking_url']::TEXT[],
 '/bookings/{{booking_id}}/track',
 true,
 'Sent when provider shares live location (at-home service)'),

('provider_needs_directions',
 'Directions Requested',
 '{{provider_name}} needs directions to your location. Please confirm address: {{service_address}}',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 '{{provider_name}} needs directions. Please confirm: {{service_address}}. Reply with any special instructions.',
 ARRAY['provider_name', 'service_address']::TEXT[],
 '/bookings/{{booking_id}}/edit',
 true,
 'Sent when provider requests directions (at-home service)'),

-- Customer Status Updates
('customer_running_late',
 'Running Late Reminder',
 'You''re running late for your {{booking_time}} appointment with {{provider_name}} at {{location_name}}. Please update your arrival time',
 ARRAY['push', 'sms']::TEXT[],
 'Running Late - Update Your Arrival',
 '<h2>Running Late?</h2><p>We noticed you may be running late for your appointment.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Location:</strong> {{location_name}}</p><p>Please update your arrival time or contact {{provider_name}} directly.</p>',
 'Running late for {{booking_time}} with {{provider_name}} at {{location_name}}? Please update arrival time.',
 ARRAY['booking_time', 'provider_name', 'location_name']::TEXT[],
 '/bookings/{{booking_id}}/edit',
 true,
 'Sent when customer is detected as running late'),

('customer_no_show',
 'No-Show Notification',
 'You missed your appointment with {{provider_name}} on {{booking_date}} at {{booking_time}}. A no-show fee may apply',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Missed Appointment - No-Show Fee',
 '<h2>Missed Appointment</h2><p>You missed your appointment with {{provider_name}}.</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>No-Show Fee:</strong> {{no_show_fee}}</p><p>Please contact us if you had an emergency or would like to reschedule.</p>',
 'Missed appointment: {{provider_name}} on {{booking_date}} at {{booking_time}}. No-show fee: {{no_show_fee}}',
 ARRAY['provider_name', 'booking_date', 'booking_time', 'no_show_fee']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when customer doesn''t show up'),

-- Add-Ons & Extras
('addon_added',
 'Add-On Service Added',
 'An add-on service "{{addon_name}}" has been added to your booking. Additional charge: {{addon_price}}',
 ARRAY['push', 'email']::TEXT[],
 'Add-On Service Added',
 '<h2>Add-On Service Added</h2><p>An add-on service has been added to your booking.</p><p><strong>Service:</strong> {{addon_name}}</p><p><strong>Price:</strong> {{addon_price}}</p><p><strong>New Total:</strong> {{new_total}}</p><p><strong>Booking:</strong> {{booking_date}} with {{provider_name}}</p>',
 NULL,
 ARRAY['addon_name', 'addon_price', 'new_total', 'booking_date', 'provider_name']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when add-on service is added to booking'),

('addon_removed',
 'Add-On Service Removed',
 'The add-on service "{{addon_name}}" has been removed from your booking. Refund: {{refund_amount}}',
 ARRAY['push', 'email']::TEXT[],
 'Add-On Service Removed',
 '<h2>Add-On Service Removed</h2><p>An add-on service has been removed from your booking.</p><p><strong>Service:</strong> {{addon_name}}</p><p><strong>Refund:</strong> {{refund_amount}}</p><p><strong>New Total:</strong> {{new_total}}</p>',
 NULL,
 ARRAY['addon_name', 'refund_amount', 'new_total']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when add-on service is removed'),

('service_upgrade_offered',
 'Service Upgrade Available',
 'Upgrade your service with {{provider_name}}! Upgrade to "{{upgrade_name}}" for just {{upgrade_price}} more',
 ARRAY['push', 'email']::TEXT[],
 'Service Upgrade Available',
 '<h2>Service Upgrade Available</h2><p>Enhance your experience with a service upgrade!</p><p><strong>Upgrade:</strong> {{upgrade_name}}</p><p><strong>Additional Cost:</strong> {{upgrade_price}}</p><p><strong>Benefits:</strong> {{upgrade_benefits}}</p><p>Add this upgrade to your booking now!</p>',
 NULL,
 ARRAY['provider_name', 'upgrade_name', 'upgrade_price', 'upgrade_benefits']::TEXT[],
 '/bookings/{{booking_id}}/upgrade',
 true,
 'Sent when service upgrade is offered'),

-- Cancellation Details
('booking_cancelled_by_customer',
 'Booking Cancelled by You',
 'You have cancelled your booking with {{provider_name}} on {{booking_date}}. {{refund_info}}',
 ARRAY['push', 'email']::TEXT[],
 'Booking Cancelled',
 '<h2>Booking Cancelled</h2><p>You have cancelled your booking.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p>{{refund_info}}</p>',
 NULL,
 ARRAY['provider_name', 'booking_date', 'booking_number', 'refund_info']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when customer cancels their own booking'),

('booking_cancelled_by_provider',
 'Booking Cancelled by Provider',
 '{{provider_name}} has cancelled your booking on {{booking_date}}. {{refund_info}} We apologize for the inconvenience',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Booking Cancelled by Provider',
 '<h2>Booking Cancelled</h2><p>Unfortunately, {{provider_name}} has cancelled your booking.</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Reason:</strong> {{cancellation_reason}}</p><p>{{refund_info}}</p><p>We apologize for any inconvenience. Would you like to book with another provider?</p>',
 '{{provider_name}} cancelled your {{booking_date}} booking. {{refund_info}} Reason: {{cancellation_reason}}',
 ARRAY['provider_name', 'booking_date', 'booking_time', 'cancellation_reason', 'refund_info']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when provider cancels a booking'),

('booking_cancelled_emergency',
 'Emergency Cancellation',
 'Your booking with {{provider_name}} has been cancelled due to an emergency. {{refund_info}}',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Emergency Cancellation',
 '<h2>Emergency Cancellation</h2><p>Your booking has been cancelled due to an emergency situation.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Reason:</strong> {{emergency_reason}}</p><p>{{refund_info}}</p><p>We sincerely apologize for the inconvenience. Please contact us if you need assistance rescheduling.</p>',
 'Emergency: Booking with {{provider_name}} on {{booking_date}} cancelled. {{refund_info}}',
 ARRAY['provider_name', 'booking_date', 'emergency_reason', 'refund_info']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when booking is cancelled due to emergency'),

-- Time & Date Changes
('booking_time_changed',
 'Booking Time Changed',
 'Your booking time with {{provider_name}} has been changed from {{old_time}} to {{new_time}} on {{booking_date}}',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Booking Time Changed',
 '<h2>Booking Time Changed</h2><p>Your booking time has been updated.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Previous Time:</strong> {{old_time}}</p><p><strong>New Time:</strong> {{new_time}}</p>',
 'Booking time changed: {{provider_name}} on {{booking_date}} now at {{new_time}} (was {{old_time}})',
 ARRAY['provider_name', 'booking_date', 'old_time', 'new_time']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when booking time is changed'),

('booking_date_changed',
 'Booking Date Changed',
 'Your booking with {{provider_name}} has been moved from {{old_date}} to {{new_date}} at {{booking_time}}',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Booking Date Changed',
 '<h2>Booking Date Changed</h2><p>Your booking date has been updated.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Previous Date:</strong> {{old_date}}</p><p><strong>New Date:</strong> {{new_date}}</p><p><strong>Time:</strong> {{booking_time}}</p>',
 'Booking date changed: {{provider_name}} now on {{new_date}} at {{booking_time}} (was {{old_date}})',
 ARRAY['provider_name', 'old_date', 'new_date', 'booking_time']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when booking date is changed'),

-- Payment Additional Scenarios
('payment_pending',
 'Payment Pending',
 'Your payment of {{amount}} for booking #{{booking_number}} is pending. Please complete payment to confirm your booking',
 ARRAY['push', 'email']::TEXT[],
 'Payment Pending - Action Required',
 '<h2>Payment Pending</h2><p>Your payment is pending and needs to be completed.</p><p><strong>Amount:</strong> {{amount}}</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Payment Method:</strong> {{payment_method}}</p><p>Please complete your payment to confirm your booking.</p>',
 NULL,
 ARRAY['amount', 'booking_number', 'payment_method']::TEXT[],
 '/bookings/{{booking_id}}/payment',
 true,
 'Sent when payment is pending'),

('payment_method_expired',
 'Payment Method Expired',
 'Your payment method for booking #{{booking_number}} has expired. Please update to complete payment',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Payment Method Expired - Update Required',
 '<h2>Payment Method Expired</h2><p>Your payment method has expired and needs to be updated.</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Amount:</strong> {{amount}}</p><p>Please update your payment method to complete your booking.</p>',
 'Payment method expired for booking #{{booking_number}}. Amount: {{amount}}. Please update payment method.',
 ARRAY['booking_number', 'amount']::TEXT[],
 '/bookings/{{booking_id}}/payment',
 true,
 'Sent when payment method expires'),

('partial_payment_received',
 'Partial Payment Received',
 'Partial payment of {{partial_amount}} received for booking #{{booking_number}}. Remaining balance: {{remaining_balance}}',
 ARRAY['push', 'email']::TEXT[],
 'Partial Payment Received',
 '<h2>Partial Payment Received</h2><p>A partial payment has been received.</p><p><strong>Amount Paid:</strong> {{partial_amount}}</p><p><strong>Remaining Balance:</strong> {{remaining_balance}}</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p>Please complete the remaining payment.</p>',
 NULL,
 ARRAY['partial_amount', 'remaining_balance', 'booking_number']::TEXT[],
 '/bookings/{{booking_id}}/payment',
 true,
 'Sent when partial payment is received'),

('invoice_generated',
 'Invoice Generated',
 'Your invoice for booking #{{booking_number}} has been generated. Amount: {{total_amount}}',
 ARRAY['push', 'email']::TEXT[],
 'Invoice Generated - Booking #{{booking_number}}',
 '<h2>Invoice Generated</h2><p>Your invoice has been generated.</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Total Amount:</strong> {{total_amount}}</p><p><strong>Invoice Number:</strong> {{invoice_number}}</p><p>Download your invoice from the booking details.</p>',
 NULL,
 ARRAY['booking_number', 'total_amount', 'invoice_number']::TEXT[],
 '/bookings/{{booking_id}}/invoice',
 true,
 'Sent when invoice is generated'),

('receipt_sent',
 'Receipt Sent',
 'Your receipt for booking #{{booking_number}} has been sent. Total: {{total_amount}}',
 ARRAY['push', 'email']::TEXT[],
 'Receipt - Booking #{{booking_number}}',
 '<h2>Receipt</h2><p>Thank you for your booking!</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Total Amount:</strong> {{total_amount}}</p><p><strong>Payment Date:</strong> {{payment_date}}</p><p>Your receipt has been sent to your email.</p>',
 NULL,
 ARRAY['booking_number', 'total_amount', 'payment_date']::TEXT[],
 '/bookings/{{booking_id}}/receipt',
 true,
 'Sent when receipt is generated and sent'),

-- Provider Business Management
('provider_new_customer',
 'New Customer Booking',
 'New customer {{customer_name}} has booked with you! This is their first booking with your business',
 ARRAY['push', 'email']::TEXT[],
 'New Customer - {{customer_name}}',
 '<h2>New Customer Booking</h2><p>Congratulations! You have a new customer.</p><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Services:</strong> {{services}}</p><p>Make a great first impression!</p>',
 NULL,
 ARRAY['customer_name', 'booking_date', 'booking_time', 'services']::TEXT[],
 '/provider/bookings/{{booking_id}}',
 true,
 'Sent to provider when new customer books'),

('provider_recurring_customer',
 'Returning Customer',
 'Great news! {{customer_name}} has booked with you again. This is their {{visit_number}} visit',
 ARRAY['push', 'email']::TEXT[],
 'Returning Customer - {{customer_name}}',
 '<h2>Returning Customer</h2><p>{{customer_name}} has booked with you again!</p><p><strong>Visit Number:</strong> {{visit_number}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Services:</strong> {{services}}</p><p>Thank you for providing excellent service!</p>',
 NULL,
 ARRAY['customer_name', 'visit_number', 'booking_date', 'booking_time', 'services']::TEXT[],
 '/provider/bookings/{{booking_id}}',
 true,
 'Sent to provider when returning customer books'),

('provider_preferred_customer',
 'Preferred Customer Booking',
 'Your preferred customer {{customer_name}} has booked with you. They specifically requested you!',
 ARRAY['push', 'email']::TEXT[],
 'Preferred Customer - {{customer_name}}',
 '<h2>Preferred Customer</h2><p>{{customer_name}} specifically requested you for their booking!</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Services:</strong> {{services}}</p><p>This customer has booked with you {{total_bookings}} times before.</p>',
 NULL,
 ARRAY['customer_name', 'booking_date', 'booking_time', 'services', 'total_bookings']::TEXT[],
 '/provider/bookings/{{booking_id}}',
 true,
 'Sent when preferred customer books'),

('provider_availability_changed',
 'Availability Updated',
 'Your availability has been updated. Customers can now book during your new available times',
 ARRAY['push', 'email']::TEXT[],
 'Availability Updated',
 '<h2>Availability Updated</h2><p>Your availability has been successfully updated.</p><p><strong>Changes:</strong> {{availability_changes}}</p><p>Customers can now book during your new available times.</p>',
 NULL,
 ARRAY['availability_changes']::TEXT[],
 '/provider/availability',
 true,
 'Sent when provider updates their availability'),

('provider_holiday_mode',
 'Holiday Mode Activated',
 'Holiday mode has been activated. You will not receive new booking requests until {{return_date}}',
 ARRAY['push', 'email']::TEXT[],
 'Holiday Mode Activated',
 '<h2>Holiday Mode Activated</h2><p>You have activated holiday mode.</p><p><strong>Start Date:</strong> {{start_date}}</p><p><strong>Return Date:</strong> {{return_date}}</p><p>You will not receive new booking requests during this period. Existing bookings will remain active.</p>',
 NULL,
 ARRAY['start_date', 'return_date']::TEXT[],
 '/provider/settings',
 true,
 'Sent when provider activates holiday mode'),

('provider_holiday_mode_ending',
 'Holiday Mode Ending Soon',
 'Your holiday mode ends on {{return_date}}. You will start receiving booking requests again',
 ARRAY['push', 'email']::TEXT[],
 'Holiday Mode Ending Soon',
 '<h2>Holiday Mode Ending</h2><p>Your holiday mode will end soon.</p><p><strong>Return Date:</strong> {{return_date}}</p><p>You will start receiving booking requests again on this date. Make sure your availability is up to date!</p>',
 NULL,
 ARRAY['return_date']::TEXT[],
 '/provider/availability',
 true,
 'Sent 2 days before holiday mode ends'),

('provider_break_scheduled',
 'Break Scheduled',
 'You have scheduled a break from {{break_start}} to {{break_end}}. No bookings will be scheduled during this time',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['break_start', 'break_end']::TEXT[],
 '/provider/calendar',
 true,
 'Sent when provider schedules a break'),

-- Loyalty & Rewards
('loyalty_points_earned',
 'Loyalty Points Earned',
 'You earned {{points}} loyalty points for your booking with {{provider_name}}! Total points: {{total_points}}',
 ARRAY['push', 'email']::TEXT[],
 'Loyalty Points Earned',
 '<h2>Loyalty Points Earned</h2><p>Congratulations! You earned loyalty points.</p><p><strong>Points Earned:</strong> {{points}}</p><p><strong>Total Points:</strong> {{total_points}}</p><p><strong>Booking:</strong> {{booking_date}} with {{provider_name}}</p><p>Redeem your points for discounts on future bookings!</p>',
 NULL,
 ARRAY['points', 'total_points', 'provider_name', 'booking_date']::TEXT[],
 '/loyalty',
 true,
 'Sent when customer earns loyalty points'),

('loyalty_points_redeemed',
 'Loyalty Points Redeemed',
 'You redeemed {{points}} loyalty points for a {{discount_amount}} discount. Remaining points: {{remaining_points}}',
 ARRAY['push', 'email']::TEXT[],
 'Loyalty Points Redeemed',
 '<h2>Loyalty Points Redeemed</h2><p>You have successfully redeemed loyalty points.</p><p><strong>Points Redeemed:</strong> {{points}}</p><p><strong>Discount:</strong> {{discount_amount}}</p><p><strong>Remaining Points:</strong> {{remaining_points}}</p>',
 NULL,
 ARRAY['points', 'discount_amount', 'remaining_points']::TEXT[],
 '/loyalty',
 true,
 'Sent when customer redeems loyalty points'),

('loyalty_tier_upgraded',
 'Loyalty Tier Upgraded',
 'Congratulations! You''ve been upgraded to {{new_tier}}! Enjoy exclusive benefits and rewards',
 ARRAY['push', 'email']::TEXT[],
 'Loyalty Tier Upgraded - {{new_tier}}',
 '<h2>Loyalty Tier Upgraded</h2><p>Congratulations! You''ve reached a new loyalty tier.</p><p><strong>New Tier:</strong> {{new_tier}}</p><p><strong>Previous Tier:</strong> {{old_tier}}</p><p><strong>Benefits:</strong> {{tier_benefits}}</p><p>Thank you for being a loyal customer!</p>',
 NULL,
 ARRAY['new_tier', 'old_tier', 'tier_benefits']::TEXT[],
 '/loyalty',
 true,
 'Sent when customer upgrades loyalty tier'),

('referral_bonus_earned',
 'Referral Bonus Earned',
 'You earned a {{bonus_amount}} referral bonus! {{referred_name}} used your referral code',
 ARRAY['push', 'email']::TEXT[],
 'Referral Bonus Earned',
 '<h2>Referral Bonus Earned</h2><p>Great job! Someone used your referral code.</p><p><strong>Referred By:</strong> {{referred_name}}</p><p><strong>Bonus Amount:</strong> {{bonus_amount}}</p><p><strong>Your Referral Code:</strong> {{referral_code}}</p><p>Keep sharing to earn more bonuses!</p>',
 NULL,
 ARRAY['bonus_amount', 'referred_name', 'referral_code']::TEXT[],
 '/referrals',
 true,
 'Sent when referral bonus is earned'),

('referral_code_used',
 'Referral Code Used',
 '{{referrer_name}} used your referral code! You both received {{bonus_amount}} bonus',
 ARRAY['push', 'email']::TEXT[],
 'Referral Code Applied',
 '<h2>Referral Code Applied</h2><p>You used a referral code!</p><p><strong>Referred By:</strong> {{referrer_name}}</p><p><strong>Your Bonus:</strong> {{bonus_amount}}</p><p><strong>Their Bonus:</strong> {{bonus_amount}}</p><p>Thank you for joining Beautonomi!</p>',
 NULL,
 ARRAY['referrer_name', 'bonus_amount']::TEXT[],
 '/referrals',
 true,
 'Sent when someone uses a referral code'),

-- Service Packages
('service_package_purchased',
 'Service Package Purchased',
 'You purchased the {{package_name}} package! {{services_included}} services included. Valid until {{expiry_date}}',
 ARRAY['push', 'email']::TEXT[],
 'Service Package Purchased - {{package_name}}',
 '<h2>Service Package Purchased</h2><p>Congratulations on your package purchase!</p><p><strong>Package:</strong> {{package_name}}</p><p><strong>Services Included:</strong> {{services_included}}</p><p><strong>Total Value:</strong> {{package_value}}</p><p><strong>Valid Until:</strong> {{expiry_date}}</p><p>Start using your package services today!</p>',
 NULL,
 ARRAY['package_name', 'services_included', 'package_value', 'expiry_date']::TEXT[],
 '/packages/{{package_id}}',
 true,
 'Sent when service package is purchased'),

('service_package_expiring',
 'Service Package Expiring',
 'Your {{package_name}} package expires on {{expiry_date}}. Use your remaining {{remaining_services}} services soon!',
 ARRAY['push', 'email']::TEXT[],
 'Service Package Expiring Soon',
 '<h2>Package Expiring Soon</h2><p>Your service package is expiring soon.</p><p><strong>Package:</strong> {{package_name}}</p><p><strong>Expiry Date:</strong> {{expiry_date}}</p><p><strong>Remaining Services:</strong> {{remaining_services}}</p><p>Book your services before they expire!</p>',
 NULL,
 ARRAY['package_name', 'expiry_date', 'remaining_services']::TEXT[],
 '/packages/{{package_id}}',
 true,
 'Sent 7 days before package expires'),

('service_package_expired',
 'Service Package Expired',
 'Your {{package_name}} package has expired. {{unused_services}} services were unused',
 ARRAY['push', 'email']::TEXT[],
 'Service Package Expired',
 '<h2>Package Expired</h2><p>Your service package has expired.</p><p><strong>Package:</strong> {{package_name}}</p><p><strong>Expiry Date:</strong> {{expiry_date}}</p><p><strong>Unused Services:</strong> {{unused_services}}</p><p>Purchase a new package to continue enjoying our services!</p>',
 NULL,
 ARRAY['package_name', 'expiry_date', 'unused_services']::TEXT[],
 '/packages',
 true,
 'Sent when package expires'),

('service_package_used',
 'Service Package Used',
 'You used 1 service from your {{package_name}} package. {{remaining_services}} services remaining',
 ARRAY['push']::TEXT[],
 NULL,
 NULL,
 NULL,
 ARRAY['package_name', 'remaining_services']::TEXT[],
 '/packages/{{package_id}}',
 true,
 'Sent when service from package is used'),

-- Disputes & Complaints
('dispute_opened',
 'Dispute Opened',
 'A dispute has been opened for booking #{{booking_number}} with {{provider_name}}. We will review and respond within 48 hours',
 ARRAY['push', 'email']::TEXT[],
 'Dispute Opened - Booking #{{booking_number}}',
 '<h2>Dispute Opened</h2><p>A dispute has been opened regarding your booking.</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Issue:</strong> {{dispute_reason}}</p><p>Our team will review your dispute and respond within 48 hours.</p>',
 NULL,
 ARRAY['booking_number', 'provider_name', 'dispute_reason']::TEXT[],
 '/disputes/{{dispute_id}}',
 true,
 'Sent when dispute is opened'),

('dispute_resolved',
 'Dispute Resolved',
 'Your dispute for booking #{{booking_number}} has been resolved. {{resolution_details}}',
 ARRAY['push', 'email']::TEXT[],
 'Dispute Resolved - Booking #{{booking_number}}',
 '<h2>Dispute Resolved</h2><p>Your dispute has been resolved.</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Resolution:</strong> {{resolution_details}}</p><p><strong>Outcome:</strong> {{dispute_outcome}}</p>',
 NULL,
 ARRAY['booking_number', 'resolution_details', 'dispute_outcome']::TEXT[],
 '/disputes/{{dispute_id}}',
 true,
 'Sent when dispute is resolved'),

('complaint_filed',
 'Complaint Filed',
 'Your complaint regarding booking #{{booking_number}} has been received. We will investigate and get back to you',
 ARRAY['push', 'email']::TEXT[],
 'Complaint Received - Booking #{{booking_number}}',
 '<h2>Complaint Received</h2><p>Thank you for bringing this to our attention.</p><p><strong>Booking Number:</strong> {{booking_number}}</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Issue:</strong> {{complaint_description}}</p><p>We take all complaints seriously and will investigate this matter. We will get back to you within 24-48 hours.</p>',
 NULL,
 ARRAY['booking_number', 'provider_name', 'complaint_description']::TEXT[],
 '/support/complaints/{{complaint_id}}',
 true,
 'Sent when complaint is filed'),

('quality_issue_reported',
 'Quality Issue Reported',
 'A quality issue has been reported for your service with {{provider_name}}. We are investigating and will contact you soon',
 ARRAY['push', 'email']::TEXT[],
 'Quality Issue Reported',
 '<h2>Quality Issue Reported</h2><p>A quality issue has been reported regarding your service.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Booking:</strong> {{booking_date}}</p><p><strong>Issue:</strong> {{issue_description}}</p><p>We are investigating this matter and will contact you within 24 hours.</p>',
 NULL,
 ARRAY['provider_name', 'booking_date', 'issue_description']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when quality issue is reported'),

-- Safety & Security
('safety_check_in',
 'Safety Check-In',
 'Please confirm you are safe and satisfied with your service. Reply SAFE if everything is okay',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 'Safety check: Please reply SAFE if everything is okay with your service from {{provider_name}}',
 ARRAY['provider_name']::TEXT[],
 '/bookings/{{booking_id}}/safety',
 true,
 'Sent after at-home service for safety check-in'),

('safety_alert',
 'Safety Alert',
 'We noticed you haven''t confirmed your safety check-in. Are you okay? Please respond or contact emergency services if needed',
 ARRAY['push', 'sms']::TEXT[],
 NULL,
 NULL,
 'URGENT: Please confirm you are safe. Reply SAFE or contact emergency services if needed.',
 ARRAY[]::TEXT[],
 '/support/emergency',
 true,
 'Sent if safety check-in is not confirmed (at-home service)'),

-- Special Requests & Instructions
('special_instructions_added',
 'Special Instructions Added',
 'Special instructions have been added to your booking with {{provider_name}}: {{instructions}}',
 ARRAY['push', 'email']::TEXT[],
 'Special Instructions Added',
 '<h2>Special Instructions Added</h2><p>Special instructions have been added to your booking.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Instructions:</strong> {{instructions}}</p><p>Your provider has been notified of these instructions.</p>',
 NULL,
 ARRAY['provider_name', 'booking_date', 'instructions']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when special instructions are added'),

('allergy_alert_provider',
 'Allergy Alert - Provider',
 'IMPORTANT: Customer {{customer_name}} has allergies: {{allergies}}. Please take necessary precautions',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Allergy Alert - {{customer_name}}',
 '<h2>Allergy Alert</h2><p><strong>IMPORTANT:</strong> This customer has allergies that require special attention.</p><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Allergies:</strong> {{allergies}}</p><p><strong>Booking:</strong> {{booking_date}} at {{booking_time}}</p><p><strong>Services:</strong> {{services}}</p><p>Please review the allergy information and take necessary precautions.</p>',
 'ALERT: {{customer_name}} has allergies: {{allergies}}. Booking: {{booking_date}} {{booking_time}}. Review booking details.',
 ARRAY['customer_name', 'allergies', 'booking_date', 'booking_time', 'services']::TEXT[],
 '/provider/bookings/{{booking_id}}',
 true,
 'Sent to provider when customer has allergies'),

-- Weather & External Factors
('weather_alert',
 'Weather Alert',
 'Severe weather may affect your booking with {{provider_name}} on {{booking_date}}. We will keep you updated',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Weather Alert - Booking Update',
 '<h2>Weather Alert</h2><p>Severe weather conditions may affect your booking.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Weather Condition:</strong> {{weather_condition}}</p><p>We will monitor the situation and keep you updated. Your safety is our priority.</p>',
 'Weather alert: {{weather_condition}} may affect your {{booking_date}} booking with {{provider_name}}. We will update you.',
 ARRAY['provider_name', 'booking_date', 'booking_time', 'weather_condition']::TEXT[],
 '/bookings/{{booking_id}}',
 true,
 'Sent when severe weather may affect booking'),

-- Provider Earnings & Payouts
('provider_earnings_summary',
 'Weekly Earnings Summary',
 'Your earnings for this week: {{total_earnings}}. {{completed_bookings}} bookings completed. Payout scheduled for {{payout_date}}',
 ARRAY['push', 'email']::TEXT[],
 'Weekly Earnings Summary',
 '<h2>Weekly Earnings Summary</h2><p>Here''s your earnings summary for this week:</p><p><strong>Total Earnings:</strong> {{total_earnings}}</p><p><strong>Completed Bookings:</strong> {{completed_bookings}}</p><p><strong>Pending Payout:</strong> {{pending_payout}}</p><p><strong>Payout Date:</strong> {{payout_date}}</p><p>Keep up the great work!</p>',
 NULL,
 ARRAY['total_earnings', 'completed_bookings', 'pending_payout', 'payout_date']::TEXT[],
 '/provider/earnings',
 true,
 'Sent weekly earnings summary to provider'),

('provider_payout_scheduled',
 'Payout Scheduled',
 'Your payout of {{payout_amount}} has been scheduled for {{payout_date}}. It will be transferred to your account',
 ARRAY['push', 'email']::TEXT[],
 'Payout Scheduled - {{payout_amount}}',
 '<h2>Payout Scheduled</h2><p>Your payout has been scheduled.</p><p><strong>Amount:</strong> {{payout_amount}}</p><p><strong>Scheduled Date:</strong> {{payout_date}}</p><p><strong>Payment Method:</strong> {{payment_method}}</p><p>The funds will be transferred to your account on the scheduled date.</p>',
 NULL,
 ARRAY['payout_amount', 'payout_date', 'payment_method']::TEXT[],
 '/provider/payouts',
 true,
 'Sent when payout is scheduled'),

('provider_payout_failed',
 'Payout Failed',
 'Your payout of {{payout_amount}} failed. Reason: {{failure_reason}}. Please update your payout account details',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Payout Failed - Action Required',
 '<h2>Payout Failed</h2><p>Unfortunately, your payout could not be processed.</p><p><strong>Amount:</strong> {{payout_amount}}</p><p><strong>Reason:</strong> {{failure_reason}}</p><p>Please update your payout account details and we will retry the transfer.</p>',
 'Payout failed: {{payout_amount}}. Reason: {{failure_reason}}. Please update payout account details.',
 ARRAY['payout_amount', 'failure_reason']::TEXT[],
 '/provider/payouts/settings',
 true,
 'Sent when payout fails'),
 
-- Customer Experience Enhancements
('booking_waitlist_available',
 'Booking Slot Available',
 'A booking slot with {{provider_name}} has become available! Date: {{available_date}}, Time: {{available_time}}. Book now before it''s gone!',
 ARRAY['push', 'email', 'sms']::TEXT[],
 'Booking Slot Available - {{provider_name}}',
 '<h2>Booking Slot Available</h2><p>Great news! A booking slot has become available.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Date:</strong> {{available_date}}</p><p><strong>Time:</strong> {{available_time}}</p><p><strong>Services Available:</strong> {{services}}</p><p>This slot is in high demand. Book now to secure your appointment!</p>',
 'Slot available! {{provider_name}} on {{available_date}} at {{available_time}}. Book now!',
 ARRAY['provider_name', 'available_date', 'available_time', 'services']::TEXT[],
 '/bookings/new?provider={{provider_id}}&date={{available_date}}&time={{available_time}}',
 true,
 'Sent when waitlisted booking slot becomes available'),

('provider_recommendation',
 'Provider Recommendation',
 'Based on your preferences, we think you''ll love {{provider_name}}! Check out their services and book now',
 ARRAY['push', 'email']::TEXT[],
 'Recommended Provider - {{provider_name}}',
 '<h2>Provider Recommendation</h2><p>We have a great recommendation for you!</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Specialties:</strong> {{specialties}}</p><p><strong>Rating:</strong> {{rating}} stars</p><p><strong>Why We Recommend:</strong> {{recommendation_reason}}</p><p>Book with {{provider_name}} and enjoy a great experience!</p>',
 NULL,
 ARRAY['provider_name', 'specialties', 'rating', 'recommendation_reason']::TEXT[],
 '/providers/{{provider_id}}',
 true,
 'Sent when provider is recommended to customer'),

('service_suggestion',
 'Service Suggestion',
 'You might also like "{{suggested_service}}" from {{provider_name}}. Add it to your booking for just {{service_price}} more!',
 ARRAY['push', 'email']::TEXT[],
 'Service Suggestion - {{suggested_service}}',
 '<h2>Service Suggestion</h2><p>We have a service suggestion for you!</p><p><strong>Service:</strong> {{suggested_service}}</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Price:</strong> {{service_price}}</p><p><strong>Description:</strong> {{service_description}}</p><p>Add this service to enhance your experience!</p>',
 NULL,
 ARRAY['suggested_service', 'provider_name', 'service_price', 'service_description']::TEXT[],
 '/services/{{service_id}}',
 true,
 'Sent when service is suggested to customer'),

('booking_follow_up',
 'How Was Your Experience?',
 'We hope you enjoyed your service with {{provider_name}}! Your feedback helps us improve. Rate your experience',
 ARRAY['push', 'email']::TEXT[],
 'How Was Your Experience?',
 '<h2>How Was Your Experience?</h2><p>We hope you had a great experience with {{provider_name}}!</p><p><strong>Service:</strong> {{services}}</p><p><strong>Date:</strong> {{booking_date}}</p><p>Your feedback helps us improve and helps other customers make informed decisions.</p><p>Please take a moment to rate your experience.</p>',
 NULL,
 ARRAY['provider_name', 'services', 'booking_date']::TEXT[],
 '/bookings/{{booking_id}}/review',
 true,
 'Sent 2 hours after service completion for feedback'),

('thank_you_after_service',
 'Thank You!',
 'Thank you for choosing Beautonomi! We hope you loved your service with {{provider_name}}. Book again and save!',
 ARRAY['push', 'email']::TEXT[],
 'Thank You - {{provider_name}}',
 '<h2>Thank You!</h2><p>Thank you for choosing Beautonomi!</p><p>We hope you had an amazing experience with {{provider_name}}.</p><p><strong>Service:</strong> {{services}}</p><p><strong>Date:</strong> {{booking_date}}</p><p>Book again soon and enjoy exclusive member benefits!</p>',
 NULL,
 ARRAY['provider_name', 'services', 'booking_date']::TEXT[],
 '/search',
 true,
 'Sent after service completion as thank you message'),

-- Custom Offers
('customer_custom_offer',
 'Custom Offer Received',
 '{{provider_name}} sent you a custom service offer. Review and accept to proceed with your booking.',
 ARRAY['push', 'email']::TEXT[],
 'Custom Offer from {{provider_name}}',
 '<h2>Custom Offer Received</h2><p>Great news! {{provider_name}} has sent you a custom service offer.</p><p><strong>Provider:</strong> {{provider_name}}</p><p><strong>Price:</strong> {{currency}} {{price}}</p><p>This is a personalized offer based on your request. Review the details and accept to proceed with your booking.</p><p>Don''t wait too long - this offer may expire soon!</p>',
 'Custom offer from {{provider_name}}: {{currency}} {{price}}. Review and accept now.',
 ARRAY['provider_name', 'price', 'currency', 'request_id', 'offer_id']::TEXT[],
 '/account-settings/custom-requests?request={{request_id}}&offer={{offer_id}}',
 true,
 'Sent when a provider sends a custom offer to a customer')
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  channels = EXCLUDED.channels,
  email_subject = EXCLUDED.email_subject,
  email_body = EXCLUDED.email_body,
  sms_body = EXCLUDED.sms_body,
  variables = EXCLUDED.variables,
  url = EXCLUDED.url,
  enabled = EXCLUDED.enabled,
  description = EXCLUDED.description,
  updated_at = NOW();

-- Add comment about template usage
COMMENT ON TABLE public.notification_templates IS 'Reusable notification templates for the Beautonomi platform. Templates support variables using {{variable_name}} syntax.';
COMMENT ON COLUMN public.notification_templates.key IS 'Unique identifier for the template (e.g., booking_confirmed, payment_successful)';
COMMENT ON COLUMN public.notification_templates.variables IS 'Array of variable names that can be used in the template (e.g., provider_name, booking_date)';
COMMENT ON COLUMN public.notification_templates.channels IS 'Array of channels this template supports: push, email, sms, live_activities';
