-- ============================================================================
-- Migration 244: Add notification templates that code expects but were missing
-- ============================================================================
-- Ensures every template key used in the codebase exists in notification_templates
-- so sendTemplateNotification() does not fail with "Template X not found or disabled".
-- See docs/NOTIFICATION_ALIGNMENT.md for where each key is used.
-- ============================================================================

INSERT INTO public.notification_templates (key, title, body, channels, email_subject, email_body, sms_body, variables, url, enabled, description)
VALUES
  -- Appointment reminders (cron/job uses this key; 062 has booking_reminder_24h/2h)
  ('appointment_reminder', 'Appointment Reminder', 'Your appointment with {{provider_name}} is coming up on {{appointment_date}} at {{appointment_time}}. Services: {{services}}. {{hours_before}} hours until appointment.', ARRAY['push', 'email']::TEXT[], 'Appointment Reminder - {{provider_name}}', '<h2>Appointment Reminder</h2><p>Your appointment with <strong>{{provider_name}}</strong> is coming up.</p><p><strong>Date:</strong> {{appointment_date}}</p><p><strong>Time:</strong> {{appointment_time}}</p><p><strong>Services:</strong> {{services}}</p><p>Booking #{{booking_number}}</p>', NULL, ARRAY['provider_name', 'appointment_date', 'appointment_time', 'services', 'hours_before', 'booking_number', 'booking_id']::TEXT[], '/bookings/{{booking_id}}', true, 'Generic appointment reminder (cron/job); variables: provider_name, appointment_date, appointment_time, services, hours_before, booking_number, booking_id'),

  -- Provider notifications (customer changed time/date or dispute/special/weather)
  ('provider_booking_time_changed', 'Booking Time Changed by Customer', '{{customer_name}} changed their booking time to {{new_time}} on {{booking_date}} (was {{old_time}}).', ARRAY['push', 'email']::TEXT[], 'Booking Time Changed - {{customer_name}}', '<h2>Booking Time Changed</h2><p>{{customer_name}} has changed their booking time.</p><p><strong>New time:</strong> {{new_time}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Previous time:</strong> {{old_time}}</p><p>Booking ID: {{booking_id}}</p>', NULL, ARRAY['customer_name', 'booking_date', 'old_time', 'new_time', 'booking_id']::TEXT[], '/provider/bookings/{{booking_id}}', true, 'Sent to provider when customer changes booking time'),
  ('provider_booking_date_changed', 'Booking Date Changed by Customer', '{{customer_name}} changed their booking date to {{new_date}} at {{booking_time}} (was {{old_date}}).', ARRAY['push', 'email']::TEXT[], 'Booking Date Changed - {{customer_name}}', '<h2>Booking Date Changed</h2><p>{{customer_name}} has changed their booking date.</p><p><strong>New date:</strong> {{new_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Previous date:</strong> {{old_date}}</p><p>Booking ID: {{booking_id}}</p>', NULL, ARRAY['customer_name', 'old_date', 'new_date', 'booking_time', 'booking_id']::TEXT[], '/provider/bookings/{{booking_id}}', true, 'Sent to provider when customer changes booking date'),
  ('provider_dispute_opened', 'Dispute Opened by Customer', 'A dispute has been opened for booking #{{booking_number}} with {{customer_name}}. Reason: {{dispute_reason}}.', ARRAY['push', 'email']::TEXT[], 'Dispute Opened - Booking #{{booking_number}}', '<h2>Dispute Opened</h2><p>{{customer_name}} has opened a dispute for booking #{{booking_number}}.</p><p><strong>Reason:</strong> {{dispute_reason}}</p><p>Booking ID: {{booking_id}}</p>', NULL, ARRAY['booking_number', 'customer_name', 'dispute_reason', 'booking_id']::TEXT[], '/provider/bookings/{{booking_id}}', true, 'Sent to provider when customer opens a dispute'),
  ('provider_dispute_resolved', 'Dispute Resolved', 'The dispute for booking #{{booking_number}} has been resolved. {{resolution_details}}', ARRAY['push', 'email']::TEXT[], 'Dispute Resolved - Booking #{{booking_number}}', '<h2>Dispute Resolved</h2><p>The dispute for booking #{{booking_number}} has been resolved.</p><p><strong>Resolution:</strong> {{resolution_details}}</p><p><strong>Outcome:</strong> {{dispute_outcome}}</p>', NULL, ARRAY['booking_number', 'resolution_details', 'dispute_outcome', 'booking_id']::TEXT[], '/provider/bookings/{{booking_id}}', true, 'Sent to provider when a dispute is resolved'),
  ('provider_special_instructions', 'Special Instructions Added', '{{customer_name}} has added special instructions to their booking on {{booking_date}}: {{instructions}}', ARRAY['push', 'email']::TEXT[], 'Special Instructions Added - {{customer_name}}', '<h2>Special Instructions Added</h2><p>{{customer_name}} has added special instructions to their booking.</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Instructions:</strong> {{instructions}}</p><p>Booking ID: {{booking_id}}</p>', NULL, ARRAY['customer_name', 'booking_date', 'instructions', 'booking_id']::TEXT[], '/provider/bookings/{{booking_id}}', true, 'Sent to provider when customer adds special instructions'),
  ('provider_weather_alert', 'Weather Alert – Booking', 'Weather alert for your booking with {{customer_name}} on {{booking_date}} at {{booking_time}}. {{weather_condition}}. Please check in with the customer if needed.', ARRAY['push', 'email']::TEXT[], 'Weather Alert - Booking {{booking_date}}', '<h2>Weather Alert</h2><p>Severe weather may affect your booking.</p><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Date:</strong> {{booking_date}}</p><p><strong>Time:</strong> {{booking_time}}</p><p><strong>Condition:</strong> {{weather_condition}}</p><p>Booking ID: {{booking_id}}</p>', NULL, ARRAY['customer_name', 'booking_date', 'booking_time', 'weather_condition', 'booking_id']::TEXT[], '/provider/bookings/{{booking_id}}', true, 'Sent to provider when weather may affect booking'),

  -- Messaging (code uses separate keys for provider vs customer)
  ('provider_new_message', 'New Message from Customer', 'You have a new message from {{sender_name}}: {{message_preview}}', ARRAY['push', 'email']::TEXT[], 'New Message from {{sender_name}}', '<h2>New Message</h2><p>You have a new message from {{sender_name}}.</p><p>{{message_preview}}</p>', NULL, ARRAY['sender_name', 'message_preview', 'conversation_id']::TEXT[], '/provider/messaging', true, 'Sent to provider when customer sends a message'),
  ('customer_new_message', 'New Message from Provider', 'You have a new message from {{sender_name}}: {{message_preview}}', ARRAY['push', 'email']::TEXT[], 'New Message from {{sender_name}}', '<h2>New Message</h2><p>You have a new message from {{sender_name}}.</p><p>{{message_preview}}</p>', NULL, ARRAY['sender_name', 'message_preview', 'conversation_id']::TEXT[], '/account-settings/messages?conversation={{conversation_id}}', true, 'Sent to customer when provider sends a message'),

  -- Custom request (provider notified when customer submits)
  ('provider_custom_request', 'New Custom Request', '{{customer_name}} sent you a custom service request: {{description_preview}}', ARRAY['push', 'email']::TEXT[], 'New Custom Request from {{customer_name}}', '<h2>New Custom Request</h2><p>{{customer_name}} has sent you a custom service request.</p><p>{{description_preview}}</p><p>Request ID: {{request_id}}</p>', NULL, ARRAY['customer_name', 'description_preview', 'request_id', 'provider_id']::TEXT[], '/provider/custom-requests?request_id={{request_id}}', true, 'Sent to provider when customer submits a custom request'),

  -- Waitlist match (email and SMS)
  ('waitlist_match', 'Waitlist Match – Slot Available', 'Hi {{customer_name}}! A slot you wanted is now available. {{match_reason}} Slots: {{slots_list}}. Book now: {{booking_url}}', ARRAY['email']::TEXT[], 'A slot you wanted is now available', '<h2>Waitlist Match</h2><p>Hi {{customer_name}},</p><p>A slot you wanted is now available.</p><p>{{match_reason}}</p><p>Available slots: {{slots_list}}</p><p><a href="{{booking_url}}">Book now</a></p>', NULL, ARRAY['customer_name', 'match_reason', 'slots_list', 'booking_url']::TEXT[], NULL, true, 'Sent when a waitlist slot becomes available (email)'),
  ('waitlist_match_sms', 'Slot Available', 'Hi {{customer_name}}! Available appointment: {{slot_text}}{{more_text}}. Book: {{booking_url}}', ARRAY['sms']::TEXT[], NULL, NULL, 'Hi {{customer_name}}! Available: {{slot_text}}{{more_text}}. Book: {{booking_url}}', ARRAY['customer_name', 'slot_text', 'more_text', 'booking_url']::TEXT[], NULL, true, 'Sent when a waitlist slot becomes available (SMS)')
ON CONFLICT (key) DO UPDATE SET
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  channels = EXCLUDED.channels,
  email_subject = EXCLUDED.email_subject,
  email_body = EXCLUDED.email_body,
  sms_body = EXCLUDED.sms_body,
  variables = EXCLUDED.variables,
  url = EXCLUDED.url,
  description = EXCLUDED.description,
  updated_at = NOW();
