import sanitizeHtml from "sanitize-html";

/**
 * Richer than marketing CMS HTML: images, embeds, tables, code — still stripped of scripts/on* handlers.
 * Iframe src is restricted to known video hosts (YouTube, Vimeo).
 */
const LEARN_ARTICLE_SANITIZE: sanitizeHtml.IOptions = {
  allowedTags: [
    "p",
    "br",
    "strong",
    "b",
    "em",
    "i",
    "u",
    "s",
    "strike",
    "del",
    "ins",
    "a",
    "ul",
    "ol",
    "li",
    "span",
    "div",
    "section",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "blockquote",
    "sub",
    "sup",
    "hr",
    "img",
    "picture",
    "source",
    "figure",
    "figcaption",
    "iframe",
    "video",
    "audio",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "caption",
    "colgroup",
    "col",
    "code",
    "pre",
    "kbd",
    "abbr",
    "mark",
  ],
  allowedAttributes: {
    blockquote: ["cite"],
    a: ["href", "target", "rel", "title"],
    img: ["src", "alt", "title", "width", "height", "loading", "decoding"],
    picture: ["class"],
    source: ["src", "srcset", "sizes", "type", "media"],
    iframe: [
      "src",
      "width",
      "height",
      "title",
      "allow",
      "allowfullscreen",
      "loading",
      "referrerpolicy",
      "frameborder",
    ],
    video: ["src", "controls", "poster", "width", "height", "playsinline", "preload", "muted", "loop"],
    audio: ["src", "controls", "preload"],
    th: ["colspan", "rowspan", "scope", "abbr"],
    td: ["colspan", "rowspan"],
    col: ["span", "width"],
    div: ["data-learn-mockup", "data-caption"],
    "*": ["class", "id", "style"],
  },
  allowedSchemes: ["http", "https", "mailto"],
  allowedSchemesAppliedToAttributes: ["href", "src", "cite"],
  allowedIframeHostnames: [
    "www.youtube.com",
    "youtube.com",
    "www.youtube-nocookie.com",
    "youtube-nocookie.com",
    "player.vimeo.com",
  ],
  allowIframeRelativeUrls: false,
  disallowedTagsMode: "discard",
};

export function sanitizeLearnArticleHtml(raw: string): string {
  return sanitizeHtml(raw ?? "", LEARN_ARTICLE_SANITIZE);
}
