/**
 * Mobile Parity Contract – Source of truth for screen contracts between
 * apps/web (client portal) and apps/customer (React Native).
 *
 * Both platforms adhere to this contract for: routes, data, actions,
 * states, and analytics.
 */

export type ParityPlatform = "web" | "mobile";

export type FeatureFlag = "web_only" | "mobile_only" | "shared";

export interface ScreenContract {
  screen_id: string;
  web_route: string;
  mobile_route: string;
  required_queries: string[];
  actions: string[];
  empty_state_required: boolean;
  loading_state_required: boolean;
  error_state_required: boolean;
  analytics_events: string[];
  feature_flag?: FeatureFlag;
  auth_required?: boolean;
}

export const PARITY_SCREEN_IDS = [
  "home",
  "explore",
  "explore_post",
  "saved",
  "search",
  "partner_profile",
  "partner_gallery",
  "book",
  "book_continue",
  "bookings",
  "booking_detail",
  "booking_reschedule",
  "booking_review",
  "chats",
  "profile",
  "account_settings",
  "account_personal_info",
  "account_wishlists",
  "account_messages",
  "account_notifications",
  "account_payments",
  "account_addresses",
  "account_preferences",
  "account_reviews",
  "account_custom_requests",
  "account_membership",
  "account_loyalty",
  "account_referrals",
  "account_business",
  "gift_card",
  "login",
  "signup",
  "onboarding",
] as const;

export type ParityScreenId = (typeof PARITY_SCREEN_IDS)[number];

/** Human-readable contract – see PARITY_CONTRACT.md for full spec */
export const PARITY_CONTRACT: Record<ParityScreenId, Omit<ScreenContract, "screen_id">> = {
  home: {
    web_route: "/",
    mobile_route: "/(app)/(tabs)/home",
    required_queries: ["/api/public/home"],
    actions: [],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["home_view"],
    feature_flag: "shared",
    auth_required: false,
  },
  explore: {
    web_route: "/explore",
    mobile_route: "/(app)/(tabs)/explore",
    required_queries: ["/api/explore/posts", "/api/explore/events"],
    actions: [],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["explore_feed_view", "explore_post_impression", "explore_post_click"],
    feature_flag: "shared",
    auth_required: false,
  },
  explore_post: {
    web_route: "/explore/[id]",
    mobile_route: "/(app)/explore-post",
    required_queries: ["/api/explore/posts/[id]", "/api/explore/posts/[id]/comments"],
    actions: ["save", "unsave", "like", "comment"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["explore_post_click", "explore_save", "explore_unsave"],
    feature_flag: "shared",
    auth_required: false,
  },
  saved: {
    web_route: "/explore/saved",
    mobile_route: "/(app)/account-settings/wishlists",
    required_queries: ["/api/explore/saved"],
    actions: ["unsave"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  search: {
    web_route: "/search",
    mobile_route: "/(app)/(tabs)/search",
    required_queries: ["/api/public/search", "/api/public/search/suggestions"],
    actions: ["filter", "select_provider"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["search_view", "search_filters_applied", "search_result_impression", "search_result_click"],
    feature_flag: "shared",
    auth_required: false,
  },
  partner_profile: {
    web_route: "/partner-profile",
    mobile_route: "/(app)/partner-profile",
    required_queries: ["/api/public/providers/[slug]", "/api/public/providers/[slug]/services"],
    actions: ["book_now", "toggle_wishlist"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["provider_profile_view"],
    feature_flag: "shared",
    auth_required: false,
  },
  partner_gallery: {
    web_route: "/partner-profile/gallery",
    mobile_route: "/(app)/partner-profile",
    required_queries: [],
    actions: [],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: false,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: false,
  },
  book: {
    web_route: "/book/[slug]",
    mobile_route: "/(app)/book",
    required_queries: [
      "/api/public/providers/[slug]",
      "/api/public/providers/[slug]/services",
      "/api/public/providers/[slug]/availability",
      "/api/public/booking-holds",
      "/api/public/booking-holds/[id]/consume",
    ],
    actions: ["create_hold", "consume_hold", "create_booking"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: [
      "booking_start",
      "booking_hold_created",
      "booking_details_completed",
      "booking_confirmed",
      "checkout_start",
      "payment_initiated",
      "payment_success",
      "payment_failed",
    ],
    feature_flag: "shared",
    auth_required: true,
  },
  book_continue: {
    web_route: "/book/continue",
    mobile_route: "/(app)/book-checkout",
    required_queries: ["/api/public/booking-holds/[id]", "/api/public/booking-holds/[id]/consume"],
    actions: ["consume_hold", "create_booking"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["booking_details_completed"],
    feature_flag: "shared",
    auth_required: true,
  },
  bookings: {
    web_route: "/account-settings/bookings",
    mobile_route: "/(app)/(tabs)/bookings",
    required_queries: ["/api/me/bookings"],
    actions: ["reschedule", "cancel"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  booking_detail: {
    web_route: "/account-settings/bookings/[id]",
    mobile_route: "/(app)/booking-detail",
    required_queries: ["/api/me/bookings"],
    actions: ["pay", "reschedule", "cancel", "review"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["payment_initiated", "booking_cancelled", "booking_rescheduled"],
    feature_flag: "shared",
    auth_required: true,
  },
  booking_reschedule: {
    web_route: "/account-settings/bookings/[id]/reschedule",
    mobile_route: "/(app)/book",
    required_queries: ["/api/me/bookings/[id]", "/api/public/providers/[slug]/availability"],
    actions: ["reschedule"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["booking_rescheduled"],
    feature_flag: "shared",
    auth_required: true,
  },
  booking_review: {
    web_route: "/account-settings/bookings/[id]/review",
    mobile_route: "/(app)/review-write",
    required_queries: ["/api/bookings/[id]"],
    actions: ["submit_review"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["review_submitted"],
    feature_flag: "shared",
    auth_required: true,
  },
  chats: {
    web_route: "/inbox",
    mobile_route: "/(app)/(tabs)/chats",
    required_queries: ["messaging_conversations", "messaging_messages"],
    actions: ["send_message", "send_image"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["message_thread_open", "message_sent"],
    feature_flag: "shared",
    auth_required: true,
  },
  profile: {
    web_route: "/profile",
    mobile_route: "/(app)/(tabs)/profile",
    required_queries: ["/api/me/profile"],
    actions: ["update_profile", "upload_avatar"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_settings: {
    web_route: "/account-settings",
    mobile_route: "/(app)/account-settings",
    required_queries: ["/api/me/profile"],
    actions: [],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_personal_info: {
    web_route: "/account-settings/personal-info",
    mobile_route: "/(app)/account-settings/personal-info",
    required_queries: ["/api/me/profile"],
    actions: ["update_profile"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_wishlists: {
    web_route: "/account-settings/wishlists",
    mobile_route: "/(app)/account-settings/wishlists",
    required_queries: ["/api/me/wishlists"],
    actions: ["toggle_wishlist"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_messages: {
    web_route: "/account-settings/messages",
    mobile_route: "/(app)/account-settings/messages",
    required_queries: ["messaging_conversations"],
    actions: ["send_message"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["message_thread_open"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_notifications: {
    web_route: "/account-settings/notifications",
    mobile_route: "/(app)/account-settings/notifications",
    required_queries: ["notification_preferences"],
    actions: ["update_preferences", "mark_read"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_payments: {
    web_route: "/account-settings/payments",
    mobile_route: "/(app)/account-settings/payments",
    required_queries: ["/api/me/payments", "payment_methods"],
    actions: [],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_addresses: {
    web_route: "/account-settings/addresses",
    mobile_route: "/(app)/account-settings/addresses",
    required_queries: ["/api/me/addresses"],
    actions: ["add", "edit", "delete"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_preferences: {
    web_route: "/account-settings/preferences",
    mobile_route: "/(app)/account-settings/preferences",
    required_queries: ["/api/me/beauty-preferences"],
    actions: ["update_preferences"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_reviews: {
    web_route: "/account-settings/reviews",
    mobile_route: "/(app)/account-settings/reviews",
    required_queries: ["my_reviews"],
    actions: ["edit_review"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_custom_requests: {
    web_route: "/account-settings/custom-requests",
    mobile_route: "/(app)/account-settings/custom-requests",
    required_queries: ["/api/me/custom-requests"],
    actions: ["create_request"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_membership: {
    web_route: "/account-settings/membership",
    mobile_route: "/(app)/account-settings/membership",
    required_queries: ["/api/me/membership"],
    actions: ["subscribe", "cancel"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_loyalty: {
    web_route: "/account-settings/loyalty",
    mobile_route: "/(app)/account-settings/loyalty",
    required_queries: ["loyalty_api"],
    actions: ["redeem"],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_referrals: {
    web_route: "/account-settings/referrals",
    mobile_route: "/(app)/account-settings/referrals",
    required_queries: ["referrals_api"],
    actions: ["share"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  account_business: {
    web_route: "/account-settings/business",
    mobile_route: "/(app)/account-settings/business",
    required_queries: ["business_services"],
    actions: [],
    empty_state_required: true,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["page_view"],
    feature_flag: "shared",
    auth_required: true,
  },
  gift_card: {
    web_route: "/gift-card",
    mobile_route: "/(app)/gift-card-purchase",
    required_queries: ["gift_card_config"],
    actions: ["purchase"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["payment_initiated", "payment_success"],
    feature_flag: "shared",
    auth_required: true,
  },
  login: {
    web_route: "(modal)",
    mobile_route: "/(auth)/login",
    required_queries: [],
    actions: ["login", "otp", "oauth"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["login_success"],
    feature_flag: "shared",
    auth_required: false,
  },
  signup: {
    web_route: "/signup",
    mobile_route: "/(auth)/login",
    required_queries: [],
    actions: ["signup"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["signup_start", "signup_complete"],
    feature_flag: "shared",
    auth_required: false,
  },
  onboarding: {
    web_route: "/onboarding",
    mobile_route: "/(auth)/login",
    required_queries: ["/api/me/profile"],
    actions: ["complete_onboarding"],
    empty_state_required: false,
    loading_state_required: true,
    error_state_required: true,
    analytics_events: ["signup_complete"],
    feature_flag: "shared",
    auth_required: true,
  },
};
