import type { UserRole } from "@/types/beautonomi";
import {
  PROVIDER_OPS_ONBOARDING_ASSIGNABLE_ROLES,
  PROVIDER_OPS_RETENTION_ASSIGNABLE_ROLES,
  PROVIDER_OPS_SALES_ASSIGNABLE_ROLES,
} from "@/lib/provider-ops/ops-desk-roles";

/** Platform operators eligible for provider-lead assignment (sales desk). */
export const PROVIDER_OPS_ASSIGNABLE_ROLES: UserRole[] = PROVIDER_OPS_SALES_ASSIGNABLE_ROLES;

export const PROVIDER_OPS_SALES_ASSIGNABLE: UserRole[] = PROVIDER_OPS_SALES_ASSIGNABLE_ROLES;
export const PROVIDER_OPS_ONBOARDING_ASSIGNABLE: UserRole[] =
  PROVIDER_OPS_ONBOARDING_ASSIGNABLE_ROLES;
export const PROVIDER_OPS_RETENTION_ASSIGNABLE: UserRole[] =
  PROVIDER_OPS_RETENTION_ASSIGNABLE_ROLES;
