/**
 * Beautonomi control set. Each control maps to the framework requirements it satisfies.
 * Status is `implemented` only where the repository enforces the control today; owners confirm
 * or correct every status in the hub before the first audit.
 *
 * Requirement shorthand: "A.5.15" / "6.1.2" → ISO 27001, "PR.AA" → NIST CSF,
 * "POPIA:C7" / "POPIA:s22" → POPIA, "GDPR:Art.32" → GDPR.
 */
import type { CatalogControl, ControlFrequency, ControlStatus, OwnerTeam } from "./types";

function resolveRequirement(ref: string): string {
  if (ref.startsWith("POPIA:")) return `popia:${ref.slice(6)}`;
  if (ref.startsWith("GDPR:")) return `gdpr:${ref.slice(5)}`;
  if (/^[A-Z]{2}\.[A-Z]{2}$/.test(ref)) return `nist_csf:${ref}`;
  return `iso27001:${ref}`;
}

type Def = {
  id: string;
  title: string;
  team: OwnerTeam;
  freq: ControlFrequency;
  status?: ControlStatus;
  collector?: string;
  reqs: string[];
  what: string;
  how?: string;
  auditor: string;
  evidence: string;
};

const DEFS: Def[] = [
  // ─── Governance ───────────────────────────────────────────────────────────
  {
    id: "GOV-01", title: "ISMS scope, context and interested parties", team: "management", freq: "annual",
    reqs: ["4.1", "4.2", "4.3", "4.4", "GV.OC"],
    what: "A documented ISMS scope covering the customer web app, admin portal, provider and customer mobile apps, APIs and the Supabase data platform, with internal/external issues and interested-party requirements.",
    auditor: "Expect questions on why anything is out of scope and how interfaces with suppliers (Supabase, Vercel, payment providers) are handled.",
    evidence: "Approved ISMS Scope Statement; context and interested-parties register; management review minutes referencing scope.",
  },
  {
    id: "GOV-02", title: "Information security policy set approved and communicated", team: "security", freq: "annual",
    reqs: ["5.1", "5.2", "A.5.1", "A.5.36", "GV.PO"],
    what: "The Information Security Policy and topic-specific policies are approved by management, published in the hub, acknowledged by staff and reviewed at least yearly.",
    how: "Policies live in the Security & Compliance hub with versioning, approval by someone other than the author, and acknowledgement tracking.",
    auditor: "Auditors sample policies for approval date, approver independence, review date and staff acknowledgement.",
    evidence: "Document register export showing approved versions, approvers and next review dates; acknowledgement report.",
  },
  {
    id: "GOV-03", title: "Security roles, responsibilities and segregation of duties", team: "management", freq: "quarterly", status: "implemented",
    collector: "grc-role-inventory",
    reqs: ["5.3", "A.5.2", "A.5.3", "GV.RR"],
    what: "Named owners for the ISMS, risk, privacy, IT operations and architecture; GRC roles are granted with a reason, cannot be self-granted, and approval duties are separated from authoring duties.",
    how: "GRC role assignments (grc_role_assignments) with DB-enforced no-self-grant, and SoD checks in approval RPCs (migration 959).",
    auditor: "Auditors check that approvers are independent of authors and that role changes are logged.",
    evidence: "Weekly role inventory collector output; activity log entries for grants and revocations.",
  },
  {
    id: "GOV-04", title: "Management commitment and resourcing", team: "management", freq: "annual",
    reqs: ["5.1", "7.1", "A.5.4", "GV.OV"],
    what: "Management allocates budget and people for the ISMS and requires staff and contractors to follow security policy.",
    auditor: "Top-management interviews are standard at Stage 2; be ready to show decisions, budget and follow-up.",
    evidence: "Management review minutes with resourcing decisions; approved security budget or roadmap.",
  },
  {
    id: "GOV-05", title: "Security objectives and performance measurement", team: "security", freq: "quarterly",
    reqs: ["6.2", "9.1", "GV.OV"],
    what: "Measurable security objectives (e.g. admin MFA coverage, vulnerability SLA compliance, evidence freshness) tracked quarterly.",
    auditor: "Objectives must be measurable, owned and time-bound, with results evaluated.",
    evidence: "Objectives register with current values; hub overview snapshots in the audit pack.",
  },
  {
    id: "GOV-06", title: "Management review of the ISMS", team: "management", freq: "annual",
    reqs: ["9.3", "GV.OV"],
    what: "Top management reviews the ISMS at least yearly, covering the clause 9.3 inputs and recording decisions and actions.",
    how: "Minutes are recorded in the hub and signed off by a management approver who did not write them.",
    auditor: "Auditors check every clause 9.3 input is covered and that outputs include improvement decisions.",
    evidence: "Signed-off management review minutes; actions raised as corrective actions.",
  },
  {
    id: "GOV-07", title: "Internal audit programme", team: "security", freq: "annual",
    reqs: ["9.2", "A.5.35", "A.5.36", "GV.OV"],
    what: "An annual internal audit programme run by someone independent of the area audited, covering the ISMS and Annex A controls over the cycle.",
    auditor: "Auditors check auditor objectivity, programme coverage and that findings became corrective actions.",
    evidence: "Internal audit plan and reports; findings with closure evidence.",
  },
  {
    id: "GOV-08", title: "Nonconformity, corrective action and continual improvement", team: "security", freq: "quarterly",
    reqs: ["10.1", "10.2", "ID.IM"],
    what: "Nonconformities from audits, incidents, pentests and access reviews are logged as findings with owners, due dates by severity and root-cause corrective actions.",
    how: "Findings module with severity SLAs; closing high/critical findings requires retest evidence.",
    auditor: "Auditors sample closed findings for root cause, effectiveness check and timeliness.",
    evidence: "Findings register export; closure notes and retest evidence.",
  },
  {
    id: "GOV-09", title: "Control of documented information", team: "security", freq: "annual", status: "implemented",
    reqs: ["7.5", "A.5.37", "GV.PO"],
    what: "Policies, procedures and records are versioned, approved, access-controlled and retained.",
    how: "Hub documents are versioned; approved versions are immutable; approvals and changes are written to the hash-chained activity log.",
    auditor: "Auditors check version history, approval, distribution and protection against unintended change.",
    evidence: "Document version history; activity log extract.",
  },
  {
    id: "GOV-10", title: "Legal, regulatory and contractual requirements register", team: "privacy", freq: "annual",
    reqs: ["A.5.31", "A.5.32", "GV.OC", "POPIA:C1"],
    what: "A register of applicable laws and obligations (POPIA, GDPR where applicable, ECTA, consumer protection, PCI DSS obligations via payment providers, contracts) with owners.",
    auditor: "Expect a sample check that obligations map to controls.",
    evidence: "Approved legal register with review date.",
  },
  {
    id: "GOV-11", title: "Contact with authorities and special interest groups", team: "security", freq: "annual",
    reqs: ["A.5.5", "A.5.6", "GV.OC", "POPIA:s55"],
    what: "Contacts for the Information Regulator, SAPS cybercrime, CSIRTs, hosting providers and security communities are documented; the Information Officer is registered with the Regulator.",
    auditor: "Auditors ask who would contact the regulator in a breach and how quickly.",
    evidence: "Authority contact list; Information Regulator registration confirmation.",
  },
  {
    id: "GOV-12", title: "Security in projects and operational planning", team: "architecture", freq: "quarterly",
    reqs: ["8.1", "A.5.8", "GV.PO"],
    what: "New features with security or privacy impact get a security review (threat model or checklist) before build.",
    auditor: "Auditors sample recent projects for evidence of a security review.",
    evidence: "Design review notes or PR templates showing security sign-off.",
  },
  {
    id: "GOV-13", title: "Planned changes to the ISMS", team: "security", freq: "annual",
    reqs: ["6.3"],
    what: "Changes to ISMS scope, roles or processes are planned, approved and communicated.",
    auditor: "New in 2022; auditors ask how an ISMS change (e.g. new product) was planned.",
    evidence: "Change records or management review decisions on ISMS changes.",
  },
  {
    id: "GOV-14", title: "Security communication plan", team: "security", freq: "annual",
    reqs: ["7.3", "7.4", "PR.AT"],
    what: "Defines what is communicated about security, to whom, when and by whom (policy updates, incidents, awareness).",
    auditor: "Auditors ask staff whether they know the policy and how to report incidents.",
    evidence: "Communication plan; sample announcements.",
  },
  {
    id: "GOV-15", title: "Tamper-evident compliance records", team: "security", freq: "monthly", status: "implemented",
    collector: "grc-activity-chain",
    reqs: ["7.5", "A.5.33", "GV.OV"],
    what: "GRC decisions (approvals, reviews, acceptances, closures) are recorded in an append-only, SHA-256 hash-chained log verified automatically.",
    how: "grc_activity_log with advisory-locked chaining and grc_verify_activity_chain(); evidence rows are insert-only and content-addressed.",
    auditor: "Auditors value records that can't be edited after the fact; show the chain verification result.",
    evidence: "Collector output with chain verification result; audit pack manifest hashes.",
  },

  // ─── Risk ─────────────────────────────────────────────────────────────────
  {
    id: "RSK-01", title: "Risk assessment methodology and register", team: "risk", freq: "quarterly", status: "in_progress",
    reqs: ["6.1.1", "6.1.2", "8.2", "ID.RA", "GV.RM"],
    what: "A 5×5 likelihood × impact method with a defined appetite; risks have owners, inherent and residual scores and review dates, and are reassessed quarterly and on significant change.",
    how: "Risk register in the hub; above-appetite status is computed against the configured appetite score.",
    auditor: "Auditors check the method gives consistent, comparable results and that risk owners are named.",
    evidence: "Risk methodology document; risk register export with review dates.",
  },
  {
    id: "RSK-02", title: "Risk treatment plan and Statement of Applicability", team: "risk", freq: "semiannual", status: "in_progress",
    reqs: ["6.1.3", "8.3", "GV.RM"],
    what: "Every risk has a treatment decision; the Statement of Applicability lists all 93 Annex A controls with applicability, justification and implementation status, and is approved by someone other than its preparer.",
    how: "SoA drafts and publishing are handled in the hub with SoD between preparer and approver.",
    auditor: "The SoA is the single most-requested document; every exclusion needs a justification.",
    evidence: "Published SoA (PDF/CSV) and treatment plan.",
  },
  {
    id: "RSK-03", title: "Risk acceptance with dual approval above appetite", team: "risk", freq: "quarterly", status: "implemented",
    reqs: ["6.1.3", "GV.RM"],
    what: "Accepting a risk above appetite needs a risk manager's proposal and a different management approver's decision, with an expiry of at most 12 months.",
    how: "grc_propose_risk_acceptance / grc_decide_risk_acceptance enforce roles, SoD and expiry in the database.",
    auditor: "Auditors check residual risk was accepted by an authorised owner and that acceptances are time-bound.",
    evidence: "Acceptance records with proposer, approver and expiry.",
  },
  {
    id: "RSK-04", title: "Threat intelligence", team: "security", freq: "monthly",
    reqs: ["A.5.7", "ID.RA", "DE.AE"],
    what: "Monitor advisories (GitHub Security Advisories, Supabase/Vercel/Next.js/Expo security bulletins, CERT feeds) and record relevant threats and actions.",
    auditor: "New in 2022; show how intelligence changed a decision or control.",
    evidence: "Monthly threat log entries; findings raised from advisories.",
  },
  {
    id: "RSK-05", title: "Security exceptions register", team: "risk", freq: "quarterly", status: "in_progress",
    reqs: ["6.1.3", "GV.RM"],
    what: "Deviations from policy (e.g. CSP allowing unsafe-inline) are recorded with compensating controls, an owner and a review date.",
    auditor: "Auditors check exceptions are approved, time-bound and reviewed.",
    evidence: "Exceptions register with review history.",
  },

  // ─── Assets ───────────────────────────────────────────────────────────────
  {
    id: "AST-01", title: "Inventory of systems, data stores and services", team: "it_operations", freq: "quarterly", status: "in_progress",
    reqs: ["A.5.9", "ID.AM"],
    what: "Inventory of applications, data stores, repositories and third-party services with owners, criticality and data classification.",
    auditor: "Auditors trace a sample of real systems back to the inventory.",
    evidence: "Asset register export with owners and last review date.",
  },
  {
    id: "AST-02", title: "Acceptable use and return of assets", team: "people", freq: "annual",
    reqs: ["A.5.10", "A.5.11", "GV.PO"],
    what: "Staff and contractors accept the Acceptable Use Policy and return devices and access on leaving.",
    auditor: "Auditors sample leavers for asset return records.",
    evidence: "Acknowledgements; offboarding checklists.",
  },
  {
    id: "AST-03", title: "Information classification and handling", team: "privacy", freq: "annual",
    reqs: ["A.5.12", "A.5.13", "ID.AM", "PR.DS", "POPIA:C7"],
    what: "Four-level classification (Restricted, Confidential, Internal, Public) with handling rules; ID documents, payment references and health/consent forms are Restricted.",
    auditor: "Auditors ask staff how they would handle a Restricted record.",
    evidence: "Approved Data Classification Standard; asset register classifications.",
  },
  {
    id: "AST-04", title: "Architecture and data-flow documentation", team: "architecture", freq: "semiannual",
    reqs: ["A.5.14", "A.8.27", "ID.AM"],
    what: "Conceptual and technical architecture diagrams and personal-data flows (apps → API → Supabase → processors) are kept current.",
    auditor: "Auditors use diagrams to scope testing; out-of-date diagrams undermine credibility.",
    evidence: "Dated diagrams in docs/grc; data-flow records in the hub.",
  },
  {
    id: "AST-05", title: "Endpoint device security", team: "it_operations", freq: "quarterly",
    reqs: ["A.8.1", "A.7.9", "A.7.10", "PR.PS"],
    what: "Laptops used for admin or engineering work have disk encryption, screen lock, OS updates and endpoint protection.",
    auditor: "Auditors sample devices or MDM reports.",
    evidence: "MDM or device compliance export; signed device checklist for BYOD.",
  },
  {
    id: "AST-06", title: "Secure disposal and re-use", team: "it_operations", freq: "annual",
    reqs: ["A.7.14", "A.8.10", "PR.DS"],
    what: "Devices and media are wiped or destroyed before disposal or re-use, with a record.",
    auditor: "Auditors ask for disposal records for the period.",
    evidence: "Disposal certificates or wipe logs.",
  },

  // ─── Identity & access ────────────────────────────────────────────────────
  {
    id: "IAM-01", title: "Multi-factor authentication for admin users", team: "security", freq: "continuous", status: "in_progress",
    collector: "admin-mfa-coverage",
    reqs: ["A.8.5", "A.5.17", "PR.AA"],
    what: "Admin portal users authenticate with MFA (AAL2).",
    how: "requireAdminMfaIfRequired enforces AAL2 per platform security.two_factor settings; the GRC hub always requires AAL2 (API and RLS).",
    auditor: "Auditors expect MFA on all privileged access; coverage below 100% needs an exception.",
    evidence: "Daily MFA coverage collector output (verified factors per admin user).",
  },
  {
    id: "IAM-02", title: "Role-based access to the admin portal", team: "security", freq: "quarterly", status: "implemented",
    collector: "admin-access-inventory",
    reqs: ["A.5.15", "A.5.18", "A.8.3", "PR.AA"],
    what: "Admin users get section-scoped roles (support, finance, trust, operations, etc.) rather than blanket access.",
    how: "packages/admin-access section RBAC enforced by requireAdminSection on API routes.",
    auditor: "Auditors compare role definitions with job needs and sample users.",
    evidence: "Weekly admin access inventory collector output.",
  },
  {
    id: "IAM-03", title: "Privileged access management", team: "security", freq: "quarterly", status: "in_progress",
    collector: "admin-access-inventory",
    reqs: ["A.8.2", "A.8.18", "PR.AA"],
    what: "Superadmin, Supabase service-role, Vercel and GitHub admin access is limited to named people and reviewed quarterly.",
    auditor: "Auditors ask for the list of people with production database and hosting admin access.",
    evidence: "Privileged account list from Supabase, Vercel and GitHub; review sign-off.",
  },
  {
    id: "IAM-04", title: "Periodic access reviews", team: "it_operations", freq: "quarterly", status: "in_progress",
    reqs: ["A.5.18", "PR.AA"],
    what: "Quarterly review of all admin portal users and GRC roles; nobody reviews their own access; revocations are tracked as findings to closure.",
    how: "Access review workflow in the hub (grc_start_access_review / grc_decide_access_review_item).",
    auditor: "Auditors check completeness of the population, reviewer independence and that revocations happened.",
    evidence: "Completed access review with decisions and linked findings.",
  },
  {
    id: "IAM-05", title: "Joiners, movers and leavers", team: "people", freq: "quarterly",
    reqs: ["A.5.16", "A.5.11", "A.6.5", "PR.AA"],
    what: "Access is granted on approved request, changed on role change and removed within one working day of leaving.",
    auditor: "Auditors sample leavers and compare leave date with access removal date.",
    evidence: "Personnel events with access-removed timestamps.",
  },
  {
    id: "IAM-06", title: "Database row-level security", team: "engineering", freq: "continuous", status: "implemented",
    reqs: ["A.8.3", "PR.AA", "PR.DS"],
    what: "Supabase tables enforce row-level security so users only reach their own or their tenant's data.",
    how: "RLS policies in supabase/migrations; static RLS harness tests (apps/web/src/lib/security/__tests__/rls-harness.test.ts) run in CI.",
    auditor: "Pentesters and auditors will test for IDOR; show RLS coverage and tests.",
    evidence: "RLS harness test output; pentest results.",
  },
  {
    id: "IAM-07", title: "Source code access and protected branches", team: "engineering", freq: "quarterly", status: "in_progress",
    collector: "branch-protection",
    reqs: ["A.8.4", "A.8.32", "PR.PS"],
    what: "The default branch requires pull requests, passing checks and code-owner review; force pushes are blocked.",
    how: ".github/CODEOWNERS plus GitHub branch protection (see docs/grc/branch-protection.md).",
    auditor: "Auditors check that one person can't push unreviewed code to production.",
    evidence: "Weekly branch protection collector output.",
  },
  {
    id: "IAM-08", title: "Admin session limits", team: "security", freq: "quarterly", status: "implemented",
    collector: "platform-security-settings",
    reqs: ["A.8.5", "PR.AA"],
    what: "Admin sessions expire after a configured maximum age and require re-authentication.",
    how: "security.admin_session_max_age in platform settings, enforced by the admin API helpers.",
    auditor: "Auditors check session timeout values against policy.",
    evidence: "Platform security settings collector output.",
  },
  {
    id: "IAM-09", title: "Secrets management and secret scanning", team: "engineering", freq: "continuous", status: "implemented",
    collector: "ci-security-gates",
    reqs: ["A.5.17", "A.8.24", "PR.DS"],
    what: "Secrets live in Vercel/EAS environment settings, never in code; gitleaks scans every change.",
    how: "Secret Scan (gitleaks) job in .github/workflows/ci.yml with .gitleaks.toml.",
    auditor: "Auditors ask how a leaked key would be detected and rotated.",
    evidence: "CI run history for the secret scan job; key rotation records.",
  },

  // ─── Suppliers ────────────────────────────────────────────────────────────
  {
    id: "SUP-01", title: "Supplier register and risk tiering", team: "risk", freq: "annual", status: "in_progress",
    reqs: ["A.5.19", "A.5.21", "GV.SC"],
    what: "All suppliers that process data or run production services are listed with criticality, data processed and data location.",
    auditor: "Auditors trace suppliers seen in the architecture to the register.",
    evidence: "Vendor register export.",
  },
  {
    id: "SUP-02", title: "Supplier security and data processing agreements", team: "privacy", freq: "annual",
    reqs: ["A.5.20", "GV.SC", "POPIA:s21", "GDPR:Art.28"],
    what: "Every processor/operator has a signed agreement with security and data protection terms (POPIA s21, GDPR Art. 28).",
    auditor: "Auditors sample critical suppliers for signed DPAs.",
    evidence: "DPA status per vendor; signed agreements.",
  },
  {
    id: "SUP-03", title: "Supplier monitoring and review", team: "risk", freq: "annual",
    reqs: ["A.5.22", "GV.SC"],
    what: "Critical suppliers are reviewed yearly: certifications (SOC 2/ISO 27001), incidents, service changes.",
    auditor: "Auditors check certification reports are current, not just filed.",
    evidence: "Vendor assessments with outcome and certification expiry.",
  },
  {
    id: "SUP-04", title: "Cloud services and inherited physical controls", team: "it_operations", freq: "annual",
    reqs: ["A.5.23", "A.7.1", "A.7.2", "A.7.3", "A.7.4", "A.7.5", "A.7.8", "A.7.11", "A.7.12", "A.7.13", "GV.SC", "PR.IR"],
    what: "Production runs on Supabase and Vercel; data-centre physical and environmental controls are inherited from them and verified through their assurance reports. Cloud exit and region choices are documented.",
    auditor: "Where physical controls are inherited, the SoA should say so and the supplier reports must cover the period.",
    evidence: "Current Supabase and Vercel SOC 2 reports; cloud usage standard.",
  },
  {
    id: "SUP-05", title: "Outsourced development oversight", team: "engineering", freq: "annual",
    reqs: ["A.8.30", "GV.SC"],
    what: "Contract developers work in the same repository, under the same review and CI gates, with NDAs.",
    auditor: "Auditors ask how contractor code is reviewed.",
    evidence: "Contractor agreements; PR review history.",
  },

  // ─── Operations ───────────────────────────────────────────────────────────
  {
    id: "OPS-01", title: "Change management through pull requests and CI", team: "engineering", freq: "continuous", status: "implemented",
    collector: "ci-security-gates",
    reqs: ["A.8.32", "PR.PS"],
    what: "Production changes go through pull requests with typecheck, lint, tests, build and security jobs; database changes are numbered migrations with a hygiene check.",
    how: ".github/workflows/ci.yml (typecheck, lint, build, dependency audit, gitleaks, migration hygiene).",
    auditor: "Auditors sample production changes for review and passing checks.",
    evidence: "CI run history collector output; sample PRs.",
  },
  {
    id: "OPS-02", title: "Configuration management", team: "it_operations", freq: "quarterly", status: "in_progress",
    reqs: ["A.8.9", "PR.PS"],
    what: "Security-relevant configuration (headers, CSP, cron schedules, Supabase settings) is kept in code or documented baselines and reviewed.",
    auditor: "Auditors ask how configuration drift is detected.",
    evidence: "next.config.mjs, vercel.json and Supabase settings baseline with review dates.",
  },
  {
    id: "OPS-03", title: "Vulnerability management", team: "security", freq: "continuous", status: "implemented",
    collector: "dependabot-alerts",
    reqs: ["A.8.8", "ID.RA", "PR.PS"],
    what: "Dependabot and npm audit find vulnerable dependencies; open alerts become findings with severity-based due dates.",
    how: ".github/dependabot.yml (weekly) and the Dependency Audit CI job; collector syncs open alerts into findings.",
    auditor: "Auditors check SLA adherence for critical/high vulnerabilities.",
    evidence: "Findings from Dependabot with due and closed dates.",
  },
  {
    id: "OPS-04", title: "Protection against malware", team: "it_operations", freq: "quarterly",
    reqs: ["A.8.7", "PR.PS"],
    what: "Endpoints run up-to-date anti-malware; uploads are restricted by MIME type and size.",
    auditor: "Auditors sample endpoint protection status.",
    evidence: "Endpoint protection report; storage bucket MIME restrictions.",
  },
  {
    id: "OPS-05", title: "Security logging", team: "engineering", freq: "continuous", status: "implemented",
    collector: "admin-audit-activity",
    reqs: ["A.8.15", "DE.CM"],
    what: "Admin actions are written to audit_logs; errors go to Sentry; GRC actions are hash-chained.",
    auditor: "Auditors ask what is logged, how long it is kept and who can alter it.",
    evidence: "Daily admin audit activity collector output; log retention settings.",
  },
  {
    id: "OPS-06", title: "Monitoring and alerting", team: "it_operations", freq: "continuous", status: "in_progress",
    reqs: ["A.8.16", "DE.CM", "DE.AE"],
    what: "Sentry alerts on errors, and cron and payment health are monitored with on-call follow-up.",
    auditor: "Auditors ask for an example alert and the response to it.",
    evidence: "Alert rules; sample alert with ticket.",
  },
  {
    id: "OPS-07", title: "Clock synchronization", team: "it_operations", freq: "annual", status: "implemented",
    reqs: ["A.8.17", "PR.PS"],
    what: "Managed platforms (Supabase, Vercel) use provider-synchronised time; timestamps are stored in UTC (timestamptz).",
    auditor: "Usually satisfied by supplier assurance plus UTC storage.",
    evidence: "Supplier documentation; schema using timestamptz.",
  },
  {
    id: "OPS-08", title: "Capacity management", team: "it_operations", freq: "quarterly", status: "in_progress",
    reqs: ["A.8.6", "PR.IR"],
    what: "Database size, connection use and function limits are monitored; load tests run before major launches.",
    how: "load-test and scale-verification workflows in .github/workflows.",
    auditor: "Auditors ask how you know you have headroom.",
    evidence: "Capacity dashboard snapshot; load test results.",
  },
  {
    id: "OPS-09", title: "Backups and restore testing", team: "it_operations", freq: "quarterly",
    reqs: ["A.8.13", "PR.DS", "RC.RP"],
    what: "Supabase backups (and point-in-time recovery where enabled) are configured; restores are tested at least twice a year against a non-production project.",
    auditor: "An untested backup is treated as no backup; auditors want restore test records.",
    evidence: "Backup configuration screenshot; BC/DR test records with RTO/RPO achieved.",
  },
  {
    id: "OPS-10", title: "Redundancy and resilience", team: "architecture", freq: "annual",
    reqs: ["A.8.14", "PR.IR"],
    what: "Availability targets are defined and met through provider redundancy; single points of failure are recorded as risks.",
    auditor: "Auditors compare availability requirements with architecture.",
    evidence: "Architecture review; provider SLAs.",
  },
  {
    id: "OPS-11", title: "Network and transport security", team: "architecture", freq: "annual", status: "implemented",
    reqs: ["A.8.20", "A.8.21", "A.8.22", "PR.IR", "PR.DS"],
    what: "All traffic uses TLS with HSTS preload; security headers (CSP, frame-ancestors, Permissions-Policy) are set; database access uses Supabase's managed network.",
    how: "Headers in apps/web/next.config.mjs.",
    auditor: "Pentesters will check headers and TLS configuration.",
    evidence: "Header scan result; TLS report.",
  },
  {
    id: "OPS-12", title: "Web filtering", team: "it_operations", freq: "annual",
    reqs: ["A.8.23", "PR.PS"],
    what: "Staff devices use DNS or browser-based filtering against known malicious sites.",
    auditor: "New in 2022; a documented DNS filtering service is usually enough for a small team.",
    evidence: "Filtering service configuration.",
  },
  {
    id: "OPS-13", title: "Controlled software deployment to production", team: "engineering", freq: "continuous", status: "implemented",
    reqs: ["A.8.19", "PR.PS"],
    what: "Production code is only deployed as immutable builds from CI/Vercel; no manual installs on production systems.",
    auditor: "Auditors ask who can deploy and how.",
    evidence: "Vercel deployment history; release workflow.",
  },
  {
    id: "OPS-14", title: "Environment separation and test data", team: "engineering", freq: "annual", status: "in_progress",
    reqs: ["A.8.31", "A.8.33", "PR.DS"],
    what: "Development and staging use separate Supabase projects and keys; production personal data is not copied to test environments.",
    auditor: "Auditors ask whether real customer data is ever used in testing.",
    evidence: "Environment inventory; test data statement.",
  },
  {
    id: "OPS-15", title: "Abuse protection and rate limiting", team: "engineering", freq: "annual", status: "implemented",
    reqs: ["A.8.26", "A.8.20", "PR.PS"],
    what: "Authentication, OTP and payment endpoints are rate limited.",
    auditor: "Pentesters will try brute force against login and OTP.",
    evidence: "Rate limit configuration; pentest results.",
  },
  {
    id: "OPS-16", title: "Data retention and deletion", team: "privacy", freq: "monthly", status: "implemented",
    collector: "data-retention-purges",
    reqs: ["A.8.10", "PR.DS", "POPIA:C3", "GDPR:Art.5", "GDPR:Art.17"],
    what: "Personal information is deleted or anonymised when no longer needed, through scheduled purge jobs and audited compliance purges.",
    how: "Purge crons (purge-audit-logs, inactivity-retention, etc.) and compliance_purge_audit_log.",
    auditor: "Auditors compare the retention schedule with what the system actually deletes.",
    evidence: "Weekly data retention collector output; retention schedule.",
  },
  {
    id: "OPS-17", title: "Protection of systems during audit and penetration testing", team: "security", freq: "annual",
    reqs: ["A.8.34", "PR.PS"],
    what: "Tests on production are scoped, approved, time-boxed and use dedicated test accounts.",
    how: "docs/grc/pentest-runbook.md.",
    auditor: "Auditors ask for the signed rules of engagement.",
    evidence: "Signed pentest scope and rules of engagement.",
  },
  {
    id: "OPS-18", title: "Data masking and leakage prevention", team: "security", freq: "annual", status: "in_progress",
    reqs: ["A.8.11", "A.8.12", "PR.DS"],
    what: "Sensitive fields are encrypted at application level where needed; exports and audit packs redact personal data by default; logs avoid personal data.",
    how: "apps/web/src/lib/security/field-encryption.ts; audit pack redact_pii flag.",
    auditor: "New in 2022; auditors ask where masking is applied and why.",
    evidence: "Field encryption inventory; sample redacted export.",
  },

  // ─── Secure development ───────────────────────────────────────────────────
  {
    id: "DEV-01", title: "Secure development life cycle", team: "engineering", freq: "annual",
    reqs: ["A.8.25", "PR.PS"],
    what: "A documented SDLC covers design review, secure coding, code review, automated testing, security testing and release.",
    auditor: "Auditors compare the documented SDLC with real PRs.",
    evidence: "Approved Secure Development Policy; sample PRs.",
  },
  {
    id: "DEV-02", title: "Application security requirements", team: "architecture", freq: "annual",
    reqs: ["A.8.26", "PR.PS"],
    what: "Security requirements (authz, input validation with zod, output encoding, audit logging) are defined for new features and APIs.",
    auditor: "Auditors ask how security requirements are captured.",
    evidence: "Requirement checklist; design docs.",
  },
  {
    id: "DEV-03", title: "Secure coding and code review", team: "engineering", freq: "continuous", status: "in_progress",
    reqs: ["A.8.28", "PR.PS"],
    what: "Code is reviewed by a code owner before merge; secure coding guidance covers the OWASP Top 10 and Supabase/RLS pitfalls.",
    how: ".github/CODEOWNERS; branch protection requires code-owner review once enabled.",
    auditor: "Auditors sample merged PRs for independent review.",
    evidence: "PR review history.",
  },
  {
    id: "DEV-04", title: "Security testing in CI", team: "engineering", freq: "continuous", status: "in_progress",
    collector: "ci-security-gates",
    reqs: ["A.8.29", "ID.RA", "PR.PS"],
    what: "CI runs unit, integration, RLS harness, E2E, dependency audit and secret scanning; failures block merge.",
    auditor: "Auditors check tests actually gate releases.",
    evidence: "CI run history; required status checks.",
  },
  {
    id: "DEV-05", title: "Secure architecture principles", team: "architecture", freq: "annual",
    reqs: ["A.8.27", "PR.PS", "PR.IR"],
    what: "Principles: least privilege, defence in depth, secure defaults, server-side authorization, service role only on the server, tenant isolation.",
    auditor: "Auditors ask for documented principles and a recent design applying them.",
    evidence: "Architecture principles document; architecture diagrams.",
  },
  {
    id: "DEV-06", title: "Cryptography and key management", team: "security", freq: "annual", status: "implemented",
    reqs: ["A.8.24", "PR.DS"],
    what: "TLS in transit, provider encryption at rest, application-level field encryption for sensitive values, keys held in environment secrets and rotated on exposure.",
    how: "apps/web/src/lib/security/field-encryption.ts.",
    auditor: "Auditors ask which algorithms and where keys are stored.",
    evidence: "Cryptography Standard; key inventory.",
  },
  {
    id: "DEV-07", title: "Payment webhook integrity", team: "engineering", freq: "annual", status: "implemented",
    reqs: ["A.5.14", "A.8.26", "PR.DS"],
    what: "Payment provider webhooks are signature-verified and processed idempotently.",
    how: "Webhook routes under apps/web/src/app/api/payments with signature and idempotency tests.",
    auditor: "Pentesters will replay and forge webhooks.",
    evidence: "Webhook signature/idempotency tests; pentest results.",
  },
  {
    id: "DEV-08", title: "Independent penetration testing", team: "security", freq: "annual",
    reqs: ["A.8.29", "A.8.8", "A.5.35", "ID.RA"],
    what: "An independent, qualified tester assesses web, API and mobile apps yearly and after major changes; findings are imported and tracked to closure with retest evidence.",
    how: "docs/grc/pentest-runbook.md; findings import in the hub.",
    auditor: "Auditors want the report, the remediation evidence and retest confirmation.",
    evidence: "Pentest report; findings with retest evidence.",
  },

  // ─── Incident management & continuity ─────────────────────────────────────
  {
    id: "IR-01", title: "Incident response plan and roles", team: "security", freq: "annual",
    reqs: ["A.5.24", "RS.MA"],
    what: "A documented incident response plan with severity levels, roles, contacts and escalation, tested at least yearly (tabletop).",
    auditor: "Auditors ask for the plan and the last exercise.",
    evidence: "Approved Incident Response Plan; tabletop exercise record.",
  },
  {
    id: "IR-02", title: "Event triage and classification", team: "security", freq: "continuous",
    reqs: ["A.5.25", "DE.AE", "RS.AN"],
    what: "Security events are triaged and classified; personal-data involvement is assessed immediately.",
    auditor: "Auditors sample events that were not escalated and ask why.",
    evidence: "Incident register with classification.",
  },
  {
    id: "IR-03", title: "Incident response and containment", team: "security", freq: "continuous",
    reqs: ["A.5.26", "RS.MA", "RS.MI"],
    what: "Incidents are contained, eradicated and recovered following the plan, with timestamps recorded.",
    auditor: "Auditors check timelines against the plan.",
    evidence: "Incident records with contained and resolved times.",
  },
  {
    id: "IR-04", title: "Post-incident review", team: "security", freq: "continuous",
    reqs: ["A.5.27", "ID.IM", "RS.AN"],
    what: "Significant incidents get a blameless review with root cause and corrective actions.",
    auditor: "Auditors check lessons led to control changes.",
    evidence: "Root cause and lessons learned in incident records; linked findings.",
  },
  {
    id: "IR-05", title: "Evidence collection and preservation", team: "security", freq: "annual",
    reqs: ["A.5.28", "RS.AN"],
    what: "Logs and artefacts relevant to an incident are preserved with integrity (hash) and chain of custody.",
    auditor: "Auditors ask how you would preserve logs for law enforcement.",
    evidence: "Procedure; hashed evidence in the locker.",
  },
  {
    id: "IR-06", title: "Personal data breach notification", team: "privacy", freq: "continuous",
    reqs: ["A.5.26", "A.5.5", "RS.CO", "POPIA:s22", "GDPR:Art.33", "GDPR:Art.34"],
    what: "Breaches are notified to the Information Regulator and affected people as soon as reasonably possible (POPIA s22) and to EU authorities within 72 hours where GDPR applies.",
    how: "Incident records track breach flag, regulator notification and data-subject notification times.",
    auditor: "Auditors check notification decisions were documented, including decisions not to notify.",
    evidence: "Breach assessment and notification records.",
  },
  {
    id: "IR-07", title: "Staff security event reporting", team: "security", freq: "annual",
    reqs: ["A.6.8", "DE.AE", "RS.MA"],
    what: "Everyone knows how to report a suspected incident (security mailbox or channel) and is encouraged to do so.",
    auditor: "Auditors ask random staff how they would report an incident.",
    evidence: "Awareness material; reports received.",
  },
  {
    id: "BC-01", title: "Business continuity plan", team: "it_operations", freq: "annual",
    reqs: ["A.5.29", "RC.RP"],
    what: "A continuity plan covers loss of Supabase, Vercel, payment providers or key staff, with RTO/RPO targets, and keeps security in place during disruption.",
    auditor: "Auditors check the plan is realistic and security isn't dropped in a crisis.",
    evidence: "Approved Business Continuity & DR Plan.",
  },
  {
    id: "BC-02", title: "ICT readiness and disaster recovery testing", team: "it_operations", freq: "semiannual",
    reqs: ["A.5.30", "RC.RP", "PR.IR"],
    what: "DR tests (restore to a new project, failover of critical integrations) run twice a year; results are compared with RTO/RPO.",
    auditor: "Auditors want test records with achieved times, not just a plan.",
    evidence: "BC/DR test records with RTO/RPO achieved.",
  },
  {
    id: "BC-03", title: "Recovery communication", team: "management", freq: "annual",
    reqs: ["A.5.29", "RC.CO"],
    what: "Templates and owners for communicating with customers, providers and partners during and after an outage.",
    auditor: "Auditors ask who approves external communication.",
    evidence: "Communication templates; status page history.",
  },

  // ─── People ───────────────────────────────────────────────────────────────
  {
    id: "PPL-01", title: "Background screening", team: "people", freq: "annual",
    reqs: ["A.6.1", "GV.RR"],
    what: "Identity, reference and, for privileged roles, criminal record checks before access, in line with South African law.",
    auditor: "Auditors sample recent hires for screening records.",
    evidence: "Screening records (held by HR).",
  },
  {
    id: "PPL-02", title: "Employment terms and confidentiality agreements", team: "people", freq: "annual",
    reqs: ["A.6.2", "A.6.6", "GV.RR"],
    what: "Contracts and NDAs cover security and confidentiality duties, including after leaving.",
    auditor: "Auditors sample contracts for security clauses.",
    evidence: "Contract templates; signed NDAs.",
  },
  {
    id: "PPL-03", title: "Security and privacy awareness training", team: "people", freq: "quarterly",
    reqs: ["A.6.3", "7.2", "7.3", "PR.AT"],
    what: "Onboarding and yearly training on security, POPIA and phishing; completion tracked with expiry.",
    auditor: "Auditors check completion rates and that training is current.",
    evidence: "Training records with completion and expiry dates.",
  },
  {
    id: "PPL-04", title: "Disciplinary process", team: "people", freq: "annual",
    reqs: ["A.6.4"],
    what: "A communicated disciplinary process covers security policy violations.",
    auditor: "Usually satisfied by HR policy.",
    evidence: "HR disciplinary policy.",
  },
  {
    id: "PPL-05", title: "Remote working, clear desk and clear screen", team: "it_operations", freq: "annual",
    reqs: ["A.6.7", "A.7.6", "A.7.7", "A.7.9", "PR.AA"],
    what: "Remote workers lock screens, use secured networks, keep devices safe and don't leave Restricted information visible.",
    auditor: "Auditors ask remote staff about their setup.",
    evidence: "Approved Remote Working Policy; acknowledgements.",
  },
  {
    id: "PPL-06", title: "Competence of security roles", team: "people", freq: "annual",
    reqs: ["7.2", "PR.AT"],
    what: "People in GRC roles have documented competence (training, certifications, experience).",
    auditor: "Auditors ask for competence evidence for the ISMS manager and key roles.",
    evidence: "Competence matrix; certificates.",
  },

  // ─── Privacy ──────────────────────────────────────────────────────────────
  {
    id: "PRV-01", title: "Information Officer and privacy accountability", team: "privacy", freq: "annual",
    reqs: ["A.5.34", "POPIA:C1", "POPIA:s55", "GDPR:Art.37"],
    what: "An Information Officer (and deputies) is appointed and registered with the Information Regulator; a POPIA compliance framework is maintained.",
    auditor: "Auditors ask for registration and the compliance framework required by POPIA Regulation 4.",
    evidence: "Registration confirmation; privacy compliance framework.",
  },
  {
    id: "PRV-02", title: "Records of processing activities", team: "privacy", freq: "semiannual", status: "in_progress",
    reqs: ["A.5.34", "POPIA:C6", "GDPR:Art.30"],
    what: "A record of processing (purpose, lawful basis, categories, recipients, transfers, retention) is kept for each activity.",
    auditor: "Auditors compare the record with actual systems and processors.",
    evidence: "Processing register export.",
  },
  {
    id: "PRV-03", title: "Lawful basis and consent management", team: "privacy", freq: "annual",
    reqs: ["POPIA:C2", "GDPR:Art.6", "GDPR:Art.7"],
    what: "Each processing activity has a documented justification; consent is recorded and can be withdrawn.",
    auditor: "Auditors sample consent records.",
    evidence: "Consent records; processing register lawful basis column.",
  },
  {
    id: "PRV-04", title: "Purpose limitation and retention", team: "privacy", freq: "annual",
    reqs: ["POPIA:C3", "POPIA:C4", "GDPR:Art.5"],
    what: "Personal information is used only for stated or compatible purposes and kept only as long as the retention schedule allows.",
    auditor: "Auditors ask how new uses of data are assessed.",
    evidence: "Retention schedule; purpose assessments.",
  },
  {
    id: "PRV-05", title: "Information quality", team: "privacy", freq: "annual",
    reqs: ["POPIA:C5", "GDPR:Art.5"],
    what: "Users can update their profile data; provider details are verified during onboarding.",
    auditor: "Auditors ask how inaccurate data is corrected.",
    evidence: "Profile edit features; onboarding verification records.",
  },
  {
    id: "PRV-06", title: "Privacy notices", team: "privacy", freq: "annual",
    reqs: ["POPIA:C6", "GDPR:Art.13"],
    what: "Privacy notices in the apps and website state what is collected, why, who receives it and how to exercise rights.",
    auditor: "Auditors compare notices with the processing register.",
    evidence: "Published privacy notice with version history.",
  },
  {
    id: "PRV-07", title: "Data subject requests", team: "privacy", freq: "monthly",
    reqs: ["POPIA:C8", "GDPR:Art.15", "GDPR:Art.17", "GDPR:Art.20"],
    what: "Access, correction, deletion and portability requests are logged, identity-verified and answered within the target time.",
    how: "Data subject request log in the hub with due dates.",
    auditor: "Auditors sample requests for timeliness and identity verification.",
    evidence: "Request log with received, due and closed dates.",
  },
  {
    id: "PRV-08", title: "Privacy impact assessments", team: "privacy", freq: "annual",
    reqs: ["A.5.34", "POPIA:s55", "GDPR:Art.35"],
    what: "High-risk processing (ID verification, location tracking, health/consent forms) has a completed impact assessment before launch.",
    auditor: "Auditors ask for the PIA on identity verification and location features.",
    evidence: "Completed PIAs/DPIAs.",
  },
  {
    id: "PRV-09", title: "Privacy by design and default", team: "architecture", freq: "annual",
    reqs: ["A.5.34", "A.8.11", "GDPR:Art.25"],
    what: "New features minimise data, default to the most private settings, and restrict access by design.",
    auditor: "Auditors look for privacy review in design.",
    evidence: "Design review checklist with privacy questions.",
  },
  {
    id: "PRV-10", title: "Cross-border transfers", team: "privacy", freq: "annual",
    reqs: ["POPIA:s72", "GDPR:Art.44"],
    what: "Transfers to processors outside South Africa (and the EEA where relevant) rely on adequate protection or contractual safeguards, documented per vendor.",
    auditor: "Auditors check the data location of each processor.",
    evidence: "Vendor data locations; transfer safeguards.",
  },
  {
    id: "PRV-11", title: "Direct marketing consent", team: "privacy", freq: "annual",
    reqs: ["POPIA:s69", "GDPR:Art.7"],
    what: "Electronic marketing is sent only with opt-in consent or to existing customers with an opt-out in every message.",
    auditor: "Auditors sample marketing messages for opt-out.",
    evidence: "Consent records; message templates.",
  },
  {
    id: "PRV-12", title: "Security safeguards for personal information", team: "security", freq: "annual",
    reqs: ["A.5.34", "POPIA:C7", "POPIA:s19", "GDPR:Art.32"],
    what: "Risk-based technical and organisational safeguards protect personal information, and their effectiveness is tested regularly.",
    auditor: "Auditors link POPIA s19 to the ISMS risk assessment and testing.",
    evidence: "Risk register entries for personal data; test results.",
  },
  {
    id: "PRV-13", title: "Protection of records", team: "privacy", freq: "annual",
    reqs: ["A.5.33", "POPIA:C3"],
    what: "Business and compliance records are retained for their legal periods and protected from alteration.",
    auditor: "Auditors check retention periods for financial and compliance records.",
    evidence: "Records retention schedule.",
  },
];

export const CONTROLS: CatalogControl[] = DEFS.map((d) => ({
  id: d.id,
  title: d.title,
  description: d.what,
  owner_team: d.team,
  frequency: d.freq,
  status: d.status ?? "not_started",
  collector_key: d.collector ?? null,
  implementation_notes: d.how ?? "",
  auditor_note: d.auditor,
  example_evidence: d.evidence,
  requirement_ids: d.reqs.map(resolveRequirement),
}));
