/**
 * Framework requirement catalogue.
 *
 * ISO/IEC 27001:2022 clause and Annex A titles are the standard's short control names, used as
 * identifiers only; descriptions are original summaries, not text from the licensed standard.
 * Keep a licensed copy of ISO/IEC 27001:2022 and 27002:2022 for the full requirement wording.
 * NIST CSF 2.0 is a US Government work. POPIA (Act 4 of 2013) and GDPR (EU 2016/679) are legislation.
 */
import type { CatalogFramework, CatalogRequirement, RequirementCategory } from "./types";

export const FRAMEWORKS: CatalogFramework[] = [
  {
    id: "iso27001",
    name: "ISO/IEC 27001",
    version: "2022",
    description: "Information security management systems: clauses 4–10 (mandatory ISMS requirements) and Annex A (93 reference controls).",
  },
  {
    id: "nist_csf",
    name: "NIST Cybersecurity Framework",
    version: "2.0",
    description: "Six functions (Govern, Identify, Protect, Detect, Respond, Recover) and 22 categories of cybersecurity outcomes.",
  },
  {
    id: "popia",
    name: "Protection of Personal Information Act (South Africa)",
    version: "Act 4 of 2013",
    description: "Eight conditions for lawful processing plus operator, breach notification, Information Officer, direct marketing and trans-border rules.",
  },
  {
    id: "gdpr",
    name: "EU General Data Protection Regulation",
    version: "2016/679",
    description: "Applies where Beautonomi offers services to, or monitors, people in the EU (Art. 3(2)).",
  },
];

type Row = [ref: string, title: string, description: string];

function build(framework_id: string, category: RequirementCategory, rows: Row[], offset = 0): CatalogRequirement[] {
  return rows.map(([ref_code, title, description], i) => ({
    id: `${framework_id}:${ref_code}`,
    framework_id,
    ref_code,
    title,
    description,
    category,
    sort_order: offset + i,
  }));
}

const ISO_CLAUSES: Row[] = [
  ["4.1", "Understanding the organization and its context", "Identify internal and external issues that affect the ISMS outcomes."],
  ["4.2", "Needs and expectations of interested parties", "Identify interested parties, their security requirements, and which the ISMS addresses."],
  ["4.3", "Determining the scope of the ISMS", "Define and document ISMS boundaries, interfaces and dependencies."],
  ["4.4", "Information security management system", "Establish, implement, maintain and continually improve the ISMS."],
  ["5.1", "Leadership and commitment", "Top management demonstrates leadership: policy, resources, integration and direction."],
  ["5.2", "Policy", "Top management sets an information security policy that is documented and communicated."],
  ["5.3", "Organizational roles, responsibilities and authorities", "Security roles are assigned, communicated and reported on to top management."],
  ["6.1.1", "Actions to address risks and opportunities — general", "Plan actions to address risks and opportunities relevant to the ISMS."],
  ["6.1.2", "Information security risk assessment", "Define and apply a repeatable risk assessment process with acceptance criteria and risk owners."],
  ["6.1.3", "Information security risk treatment", "Select treatment options and controls, produce the Statement of Applicability, obtain owner approval of residual risk."],
  ["6.2", "Information security objectives and planning to achieve them", "Set measurable objectives, plans, owners and timelines."],
  ["6.3", "Planning of changes", "Changes to the ISMS are carried out in a planned manner."],
  ["7.1", "Resources", "Provide the resources needed for the ISMS."],
  ["7.2", "Competence", "Ensure people doing security work are competent and keep evidence of competence."],
  ["7.3", "Awareness", "People know the policy, their contribution and the implications of non-conformance."],
  ["7.4", "Communication", "Decide what, when, with whom and how to communicate about the ISMS."],
  ["7.5", "Documented information", "Create, update and control the documents and records the ISMS needs."],
  ["8.1", "Operational planning and control", "Plan, implement and control the processes needed to meet requirements, including outsourced processes."],
  ["8.2", "Information security risk assessment (operation)", "Perform risk assessments at planned intervals and on significant change; retain results."],
  ["8.3", "Information security risk treatment (operation)", "Implement the risk treatment plan and retain results."],
  ["9.1", "Monitoring, measurement, analysis and evaluation", "Decide what to measure, how and when, and evaluate performance and effectiveness."],
  ["9.2", "Internal audit", "Run an internal audit programme at planned intervals with objective auditors."],
  ["9.3", "Management review", "Top management reviews the ISMS at planned intervals with defined inputs and outputs."],
  ["10.1", "Continual improvement", "Continually improve the suitability, adequacy and effectiveness of the ISMS."],
  ["10.2", "Nonconformity and corrective action", "React to nonconformities, fix causes, and keep evidence of actions and results."],
];

const ISO_ANNEX_A: Row[] = [
  ["A.5.1", "Policies for information security", "Security policy and topic-specific policies are defined, approved, published, acknowledged and reviewed."],
  ["A.5.2", "Information security roles and responsibilities", "Security roles and responsibilities are defined and allocated."],
  ["A.5.3", "Segregation of duties", "Conflicting duties and areas of responsibility are separated."],
  ["A.5.4", "Management responsibilities", "Management requires personnel to apply security in line with policy."],
  ["A.5.5", "Contact with authorities", "Contact with relevant authorities is established and maintained."],
  ["A.5.6", "Contact with special interest groups", "Contact with security forums and professional associations is maintained."],
  ["A.5.7", "Threat intelligence", "Information about threats is collected and analysed to produce threat intelligence."],
  ["A.5.8", "Information security in project management", "Security is integrated into project management."],
  ["A.5.9", "Inventory of information and other associated assets", "An inventory of information and assets, with owners, is maintained."],
  ["A.5.10", "Acceptable use of information and other associated assets", "Rules for acceptable use and handling are identified, documented and implemented."],
  ["A.5.11", "Return of assets", "Personnel and others return organizational assets on change or termination."],
  ["A.5.12", "Classification of information", "Information is classified according to security needs."],
  ["A.5.13", "Labelling of information", "Procedures for labelling information follow the classification scheme."],
  ["A.5.14", "Information transfer", "Rules, procedures or agreements are in place for all types of information transfer."],
  ["A.5.15", "Access control", "Rules for physical and logical access are established based on business and security requirements."],
  ["A.5.16", "Identity management", "The full life cycle of identities is managed."],
  ["A.5.17", "Authentication information", "Allocation and management of authentication information is controlled."],
  ["A.5.18", "Access rights", "Access rights are provisioned, reviewed, modified and removed according to policy."],
  ["A.5.19", "Information security in supplier relationships", "Processes manage security risks of supplier products and services."],
  ["A.5.20", "Addressing information security within supplier agreements", "Security requirements are agreed with each supplier."],
  ["A.5.21", "Managing information security in the ICT supply chain", "Processes manage security risks in the ICT product and service supply chain."],
  ["A.5.22", "Monitoring, review and change management of supplier services", "Supplier security practices and service delivery are monitored, reviewed and changes managed."],
  ["A.5.23", "Information security for use of cloud services", "Acquisition, use, management and exit from cloud services follow security requirements."],
  ["A.5.24", "Information security incident management planning and preparation", "Incident management processes, roles and responsibilities are defined and communicated."],
  ["A.5.25", "Assessment and decision on information security events", "Security events are assessed and classified as incidents where appropriate."],
  ["A.5.26", "Response to information security incidents", "Incidents are responded to according to documented procedures."],
  ["A.5.27", "Learning from information security incidents", "Knowledge from incidents is used to strengthen controls."],
  ["A.5.28", "Collection of evidence", "Procedures for identifying, collecting and preserving evidence are established."],
  ["A.5.29", "Information security during disruption", "Security is maintained at an appropriate level during disruption."],
  ["A.5.30", "ICT readiness for business continuity", "ICT readiness is planned, implemented, maintained and tested against continuity objectives."],
  ["A.5.31", "Legal, statutory, regulatory and contractual requirements", "Relevant legal, regulatory and contractual requirements are identified, documented and kept up to date."],
  ["A.5.32", "Intellectual property rights", "Procedures protect intellectual property rights."],
  ["A.5.33", "Protection of records", "Records are protected from loss, destruction, falsification and unauthorized access or release."],
  ["A.5.34", "Privacy and protection of PII", "Requirements for privacy and PII protection are identified and met."],
  ["A.5.35", "Independent review of information security", "The approach to managing security is independently reviewed at planned intervals or on significant change."],
  ["A.5.36", "Compliance with policies, rules and standards for information security", "Compliance with the security policy and standards is regularly reviewed."],
  ["A.5.37", "Documented operating procedures", "Operating procedures are documented and available to those who need them."],
  ["A.6.1", "Screening", "Background checks on candidates are carried out before joining and on an ongoing basis where appropriate."],
  ["A.6.2", "Terms and conditions of employment", "Employment agreements state personnel and organizational security responsibilities."],
  ["A.6.3", "Information security awareness, education and training", "Personnel receive appropriate awareness, education, training and regular updates."],
  ["A.6.4", "Disciplinary process", "A formal, communicated disciplinary process exists for policy violations."],
  ["A.6.5", "Responsibilities after termination or change of employment", "Security duties that remain after termination or change are defined, communicated and enforced."],
  ["A.6.6", "Confidentiality or non-disclosure agreements", "Confidentiality agreements reflect protection needs and are signed and reviewed."],
  ["A.6.7", "Remote working", "Security measures protect information accessed, processed or stored outside the organization's premises."],
  ["A.6.8", "Information security event reporting", "Personnel have a way to report observed or suspected security events promptly."],
  ["A.7.1", "Physical security perimeters", "Perimeters are defined and used to protect areas containing information and assets."],
  ["A.7.2", "Physical entry", "Secure areas are protected by entry controls and access points."],
  ["A.7.3", "Securing offices, rooms and facilities", "Physical security for offices, rooms and facilities is designed and implemented."],
  ["A.7.4", "Physical security monitoring", "Premises are continuously monitored for unauthorized physical access."],
  ["A.7.5", "Protecting against physical and environmental threats", "Protection against natural disasters and other physical threats is designed and implemented."],
  ["A.7.6", "Working in secure areas", "Security measures for working in secure areas are designed and implemented."],
  ["A.7.7", "Clear desk and clear screen", "Clear desk and clear screen rules are defined and enforced."],
  ["A.7.8", "Equipment siting and protection", "Equipment is sited securely and protected."],
  ["A.7.9", "Security of assets off-premises", "Off-site assets are protected."],
  ["A.7.10", "Storage media", "Storage media are managed through their life cycle."],
  ["A.7.11", "Supporting utilities", "Facilities are protected from power failures and other utility disruptions."],
  ["A.7.12", "Cabling security", "Power and data cables are protected from interception, interference or damage."],
  ["A.7.13", "Equipment maintenance", "Equipment is maintained correctly to ensure availability, integrity and confidentiality."],
  ["A.7.14", "Secure disposal or re-use of equipment", "Sensitive data and licensed software are removed or securely overwritten before disposal or re-use."],
  ["A.8.1", "User endpoint devices", "Information on, processed by or accessible via endpoint devices is protected."],
  ["A.8.2", "Privileged access rights", "Allocation and use of privileged access is restricted and managed."],
  ["A.8.3", "Information access restriction", "Access to information and assets is restricted according to the access control policy."],
  ["A.8.4", "Access to source code", "Read and write access to source code, tools and libraries is managed."],
  ["A.8.5", "Secure authentication", "Secure authentication technologies and procedures are implemented based on access restrictions."],
  ["A.8.6", "Capacity management", "Resource use is monitored and adjusted to current and expected capacity needs."],
  ["A.8.7", "Protection against malware", "Protection against malware is implemented and supported by user awareness."],
  ["A.8.8", "Management of technical vulnerabilities", "Vulnerability information is obtained, exposure evaluated and measures taken."],
  ["A.8.9", "Configuration management", "Security configurations of hardware, software, services and networks are established, documented, monitored and reviewed."],
  ["A.8.10", "Information deletion", "Information is deleted when no longer required."],
  ["A.8.11", "Data masking", "Data masking is used according to access control policy and business and legal requirements."],
  ["A.8.12", "Data leakage prevention", "Data leakage prevention measures apply to systems, networks and devices handling sensitive information."],
  ["A.8.13", "Information backup", "Backups are maintained and regularly tested according to the backup policy."],
  ["A.8.14", "Redundancy of information processing facilities", "Processing facilities have enough redundancy to meet availability requirements."],
  ["A.8.15", "Logging", "Logs recording activities, exceptions, faults and events are produced, stored, protected and analysed."],
  ["A.8.16", "Monitoring activities", "Networks, systems and applications are monitored for anomalous behaviour and actions taken."],
  ["A.8.17", "Clock synchronization", "System clocks are synchronized to approved time sources."],
  ["A.8.18", "Use of privileged utility programs", "Utility programs that can override system and application controls are restricted and tightly controlled."],
  ["A.8.19", "Installation of software on operational systems", "Software installation on operational systems is securely managed."],
  ["A.8.20", "Networks security", "Networks and network devices are secured, managed and controlled."],
  ["A.8.21", "Security of network services", "Security mechanisms, service levels and requirements of network services are identified, implemented and monitored."],
  ["A.8.22", "Segregation of networks", "Groups of services, users and systems are segregated in networks."],
  ["A.8.23", "Web filtering", "Access to external websites is managed to reduce exposure to malicious content."],
  ["A.8.24", "Use of cryptography", "Rules for effective use of cryptography, including key management, are defined and implemented."],
  ["A.8.25", "Secure development life cycle", "Rules for secure development of software and systems are established and applied."],
  ["A.8.26", "Application security requirements", "Security requirements are identified, specified and approved when developing or acquiring applications."],
  ["A.8.27", "Secure system architecture and engineering principles", "Principles for engineering secure systems are established, documented, maintained and applied."],
  ["A.8.28", "Secure coding", "Secure coding principles are applied to software development."],
  ["A.8.29", "Security testing in development and acceptance", "Security testing processes are defined and implemented in the development life cycle."],
  ["A.8.30", "Outsourced development", "Outsourced development is directed, monitored and reviewed."],
  ["A.8.31", "Separation of development, test and production environments", "Development, testing and production environments are separated and secured."],
  ["A.8.32", "Change management", "Changes to processing facilities and systems follow change management procedures."],
  ["A.8.33", "Test information", "Test information is appropriately selected, protected and managed."],
  ["A.8.34", "Protection of information systems during audit testing", "Audit tests and assurance activities on operational systems are planned and agreed."],
];

const NIST_CATEGORIES: Row[] = [
  ["GV.OC", "Organizational Context", "Mission, stakeholder expectations, dependencies and legal requirements that shape cybersecurity risk decisions are understood."],
  ["GV.RM", "Risk Management Strategy", "Priorities, constraints, risk tolerance and appetite statements are established, communicated and used."],
  ["GV.RR", "Roles, Responsibilities, and Authorities", "Cybersecurity roles, responsibilities and authorities are established and communicated."],
  ["GV.PO", "Policy", "Cybersecurity policy is established, communicated and enforced."],
  ["GV.OV", "Oversight", "Results of risk management activities are used to inform, improve and adjust strategy."],
  ["GV.SC", "Cybersecurity Supply Chain Risk Management", "Supply chain risk management processes are identified, established, managed, monitored and improved."],
  ["ID.AM", "Asset Management", "Assets that enable the organization to achieve its purposes are identified and managed."],
  ["ID.RA", "Risk Assessment", "Cybersecurity risk to the organization, assets and individuals is understood."],
  ["ID.IM", "Improvement", "Improvements to risk management processes and activities are identified across all functions."],
  ["PR.AA", "Identity Management, Authentication, and Access Control", "Access to assets is limited to authorized users, services and hardware and managed to the assessed risk."],
  ["PR.AT", "Awareness and Training", "Personnel have the awareness and training to perform cybersecurity-related tasks."],
  ["PR.DS", "Data Security", "Data are managed consistent with the risk strategy to protect confidentiality, integrity and availability."],
  ["PR.PS", "Platform Security", "Hardware, software and services of platforms are managed consistent with the risk strategy."],
  ["PR.IR", "Technology Infrastructure Resilience", "Security architectures are managed to protect asset confidentiality, integrity, availability and resilience."],
  ["DE.CM", "Continuous Monitoring", "Assets are monitored to find anomalies, indicators of compromise and other potentially adverse events."],
  ["DE.AE", "Adverse Event Analysis", "Anomalies, indicators of compromise and other adverse events are analysed to characterize events and detect incidents."],
  ["RS.MA", "Incident Management", "Responses to detected incidents are managed."],
  ["RS.AN", "Incident Analysis", "Investigations are conducted to ensure effective response and support forensics and recovery."],
  ["RS.CO", "Incident Response Reporting and Communication", "Response activities are coordinated with internal and external stakeholders as required by laws, regulations or policies."],
  ["RS.MI", "Incident Mitigation", "Activities are performed to prevent expansion of an event and mitigate its effects."],
  ["RC.RP", "Incident Recovery Plan Execution", "Restoration activities are performed to ensure operational availability of affected systems and services."],
  ["RC.CO", "Incident Recovery Communication", "Restoration activities are coordinated with internal and external parties."],
];

const POPIA_CONDITIONS: Row[] = [
  ["C1", "Condition 1 — Accountability (s8)", "The responsible party ensures the conditions for lawful processing are met."],
  ["C2", "Condition 2 — Processing limitation (s9–12)", "Processing is lawful, minimal, based on consent or another justification, and collected directly where possible."],
  ["C3", "Condition 3 — Purpose specification (s13–14)", "Collected for a specific, explicitly defined purpose; records retained no longer than necessary."],
  ["C4", "Condition 4 — Further processing limitation (s15)", "Further processing is compatible with the original purpose."],
  ["C5", "Condition 5 — Information quality (s16)", "Reasonable steps ensure information is complete, accurate, not misleading and updated."],
  ["C6", "Condition 6 — Openness (s17–18)", "Documentation of processing operations is maintained and data subjects are notified when information is collected."],
  ["C7", "Condition 7 — Security safeguards (s19–22)", "Appropriate, reasonable technical and organisational measures protect integrity and confidentiality."],
  ["C8", "Condition 8 — Data subject participation (s23–25)", "Data subjects can access, correct and request deletion of their personal information."],
];

const POPIA_SECTIONS: Row[] = [
  ["s19", "Section 19 — Security measures on integrity and confidentiality", "Identify foreseeable risks, establish and maintain safeguards, verify they are effective and update them."],
  ["s21", "Section 21 — Security measures regarding information processed by operator", "A written contract requires operators to maintain the s19 security measures."],
  ["s22", "Section 22 — Notification of security compromises", "Notify the Information Regulator and affected data subjects as soon as reasonably possible after discovering a compromise."],
  ["s55", "Section 55 — Duties and responsibilities of Information Officer", "The Information Officer encourages compliance, handles requests and works with the Regulator; must be registered with the Regulator."],
  ["s69", "Section 69 — Direct marketing by electronic communication", "Electronic direct marketing requires consent or an existing customer relationship with an opt-out."],
  ["s72", "Section 72 — Transfers of personal information outside the Republic", "Cross-border transfers only where the recipient is bound by adequate protection, consent or another s72 ground."],
];

const GDPR_ARTICLES: Row[] = [
  ["Art.5", "Article 5 — Principles relating to processing", "Lawfulness, fairness, transparency, purpose limitation, minimisation, accuracy, storage limitation, integrity and accountability."],
  ["Art.6", "Article 6 — Lawfulness of processing", "Processing needs a lawful basis such as consent, contract, legal obligation or legitimate interests."],
  ["Art.7", "Article 7 — Conditions for consent", "Consent is demonstrable, distinguishable, and as easy to withdraw as to give."],
  ["Art.13", "Article 13 — Information to be provided (collected from the data subject)", "Privacy notice content at the time of collection."],
  ["Art.15", "Article 15 — Right of access", "Data subjects can obtain confirmation, a copy and information about processing."],
  ["Art.17", "Article 17 — Right to erasure", "Personal data is erased without undue delay where a ground applies."],
  ["Art.20", "Article 20 — Right to data portability", "Data subjects receive their data in a structured, machine-readable format."],
  ["Art.25", "Article 25 — Data protection by design and by default", "Technical and organisational measures implement data protection principles from design."],
  ["Art.28", "Article 28 — Processor", "Processors give sufficient guarantees and are bound by a contract with the Art. 28(3) terms."],
  ["Art.30", "Article 30 — Records of processing activities", "Controllers maintain a record of processing activities."],
  ["Art.32", "Article 32 — Security of processing", "Appropriate technical and organisational measures, including regular testing of their effectiveness."],
  ["Art.33", "Article 33 — Notification of a personal data breach to the supervisory authority", "Notify the supervisory authority without undue delay and, where feasible, within 72 hours."],
  ["Art.34", "Article 34 — Communication of a personal data breach to the data subject", "Tell affected data subjects without undue delay when the breach is likely to result in high risk."],
  ["Art.35", "Article 35 — Data protection impact assessment", "Assess high-risk processing before it starts."],
  ["Art.37", "Article 37 — Designation of the data protection officer", "Designate a DPO where required; publish contact details."],
  ["Art.44", "Article 44 — General principle for transfers", "Transfers outside the EEA only under the conditions of Chapter V."],
];

export const REQUIREMENTS: CatalogRequirement[] = [
  ...build("iso27001", "clause", ISO_CLAUSES, 0),
  ...build("iso27001", "annex_a", ISO_ANNEX_A, 100),
  ...build("nist_csf", "category", NIST_CATEGORIES, 0),
  ...build("popia", "condition", POPIA_CONDITIONS, 0),
  ...build("popia", "section", POPIA_SECTIONS, 100),
  ...build("gdpr", "article", GDPR_ARTICLES, 0),
];
