-- 311_learning_center_overview_content.sql
-- Replace stub overview article bodies with platform-accurate content (public categories only).
-- Idempotent: safe to run multiple times.

-- General: Getting Started
UPDATE public.learning_articles SET summary = 'Get started with Beautonomi: create an account, explore as customer or provider, and find the right guides.', body = '<p>Beautonomi connects customers with beauty and wellness providers. You can use the platform to book services as a customer or to offer services as a provider. Creating an account is free: sign up with email, phone, or a social login, and complete any requested verification.</p><p>As a customer, you can discover providers on Home and Explore, book services, pay securely, and manage appointments and messages. As a provider, you get a full toolkit for scheduling, payments, payouts, clients, and more. Start with the guides in this section and use the Learning Center sidebar to jump to topics that match your role.</p>' WHERE slug = 'getting-started-overview';

-- General: Account & Profile
UPDATE public.learning_articles SET summary = 'Manage your account and profile: personal info, profile details, login and security, identity verification, addresses, and privacy.', body = '<p>Your account settings let you control your personal information, profile details, and how you sign in. Update your name, photo, email, and phone in Personal info. Use Profile details to set beauty preferences and interests. In Login and security you can change your password and manage account protection.</p><p>Identity verification may be required for certain actions; we do not share verification documents with providers. You can add and manage saved addresses (home, work, etc.) for bookings and delivery. Privacy and sharing settings let you control how your data is used and visible on the platform.</p>' WHERE slug = 'account-profile-overview';

-- General: Security & Privacy
UPDATE public.learning_articles SET summary = 'Keep your account secure and understand how we handle your data and privacy.', body = '<p>Beautonomi takes security and privacy seriously. We use encrypted connections and do not store raw card numbers or full bank details; payments are processed through Paystack with saved authorization tokens. Keep your account secure by using a strong password and not sharing your login details.</p><p>We collect only what is needed to run the platform and provide support. Your verification documents are not shared with providers. For full details on what we collect and how we use it, see our Privacy Policy and Terms. If you notice anything suspicious on your account, contact support and change your password.</p>' WHERE slug = 'security-privacy-overview';

-- General: Notifications & Messaging
UPDATE public.learning_articles SET summary = 'Configure how you receive notifications (email, SMS, push) and use in-app messaging.', body = '<p>You can choose how you receive updates: by email, SMS, and push notifications. In your account notification preferences you can turn these on or off for booking reminders, messages, promotions, and other updates. Push notifications require enabling them in your device settings for the app.</p><p>Messaging on Beautonomi lets you chat with providers before and after a booking. Conversations are available in the Chats tab (customer) or under More → Messaging (provider). You can use messages to confirm details, ask questions, or receive custom offers. Notifications can alert you when you receive a new message.</p>' WHERE slug = 'notifications-messaging-overview';

-- General: Troubleshooting & FAQ
UPDATE public.learning_articles SET summary = 'Common questions and how to resolve typical issues on the platform.', body = '<p>Many issues can be resolved quickly by checking your account settings, payment methods, or booking details. If a payment fails, ensure your card is valid and has sufficient funds, or try another saved payment method. For booking problems, use the booking detail screen to reschedule or cancel, or to pay any outstanding additional charges.</p><p>If you cannot sign in, use the forgot-password flow or ensure you are using the correct app (customer vs provider). For problems that are not covered in the Learning Center, submit a support ticket from the Help Centre. We will get back to you and can help with account, booking, payment, or dispute issues.</p>' WHERE slug = 'troubleshooting-faq-overview';

-- General: Platform Updates
UPDATE public.learning_articles SET summary = 'Latest release notes, new features, and improvements.', body = '<p>Beautonomi is updated regularly with new features, improvements, and fixes. Platform updates are published here so you can see what has changed on the customer app, provider app, and web. Check this section for release notes and announcements.</p><p>Major changes may also be communicated by email or in-app notifications. If you have suggestions or feedback, you can submit them through the Help Centre or the feedback link on the help page.</p>' WHERE slug = 'platform-updates-overview';

-- General: Pricing & Subscriptions
UPDATE public.learning_articles SET summary = 'Understand Beautonomi pricing and subscription plans for providers.', body = '<p>Providers on Beautonomi can choose a plan that fits their business size and needs. Pricing and subscription options are available in the provider app under More → Settings → Subscription, and on the web. Plans may include different limits or features such as staff, locations, or recurring appointments.</p><p>Your subscription can be upgraded, renewed, or cancelled according to the terms of your plan. Billing and invoice history are available in the Finance area. For exact pricing and current offers, check the in-app subscription screen or the Beautonomi website.</p>' WHERE slug = 'pricing-subscriptions-overview';

-- General: Policies
UPDATE public.learning_articles SET summary = 'Cancellations, refunds, disputes, safety, and community standards.', body = '<p>Beautonomi has clear policies for cancellations, refunds, and disputes. Cancellation windows and refund rules depend on when you cancel and on the provider’s policy. If your provider cancels, we will help you rebook or receive a refund. Disputes can be raised through support and are reviewed fairly.</p><p>We expect both customers and providers to follow our community standards: accurate listings, respectful communication, and compliance with local laws. Safety is important: we support verification, secure payments, and a safety panic option where applicable. For full terms, see our Terms of Service and related policy pages.</p>' WHERE slug = 'policies-overview';

-- Customer: Booking & Checkout
UPDATE public.learning_articles SET summary = 'How to discover providers, choose a service, and complete booking and checkout.', body = '<p>To book a service, start from Home or Explore: find a provider, open their profile, and tap Book. Choose your service, venue (if they have multiple locations), preferred staff member, date, and time. You can add add-ons before checkout. The flow then takes you to book-checkout where you confirm details, add a payment method if needed, and complete the booking.</p><p>At checkout you can choose to pay now or, where offered, use a hold. You can also opt for on-demand booking: request a provider without picking one, and accept an offer when a provider responds. After booking you will see your appointment in Bookings and can open the booking detail to reschedule, cancel, pay, or verify arrival.</p>' WHERE slug = 'booking-checkout-overview';

-- Customer: Payments
UPDATE public.learning_articles SET summary = 'How payments work: Paystack, saved cards, when you''re charged, and receipts.', body = '<p>Beautonomi uses Paystack for payments. At checkout you can pay with a new card or bank method, or use a saved payment method. If you opt to save your card, we store a secure token (not your full card number) so you can pay quickly next time. Paystack may place a small temporary charge to verify the card and then reverse it.</p><p>You are charged when you complete checkout for a booking (or when you pay for an existing booking or additional charges). If payment fails, you can try again or use another method. Receipts and payment history are available in your account under Payments and in booking details. You can add, remove, or set a default payment method in account settings.</p>' WHERE slug = 'payments-customer-overview';

-- Customer: Wallet, Gift Cards & Coupons
UPDATE public.learning_articles SET summary = 'Use your wallet balance, gift cards, and promo codes.', body = '<p>Your wallet holds any balance you have received from refunds, credits, or promotions. You can use this balance toward future bookings where allowed. Wallet and transaction history are available in account settings under Wallet.</p><p>Gift cards can be purchased for a provider from their profile and used when booking with them. You can also redeem promo codes or coupons at checkout if the provider or platform has offered them. Apply a coupon in the checkout flow to see the discounted total.</p>' WHERE slug = 'wallet-gift-cards-coupons-overview';

-- Customer: Loyalty & Rewards
UPDATE public.learning_articles SET summary = 'Earn and redeem loyalty points and rewards.', body = '<p>Some providers offer loyalty programs: you earn points for bookings and can redeem them for discounts or perks. Your points and rewards are visible in account settings under Loyalty. Rules and redemption options depend on each provider’s program.</p><p>You may also earn or use rewards through platform-wide promotions or referrals. Check your account and notifications for the latest offers and how to earn and redeem.</p>' WHERE slug = 'loyalty-rewards-overview';

-- Customer: Reviews & Ratings
UPDATE public.learning_articles SET summary = 'How to leave reviews and understand ratings.', body = '<p>After a completed booking you can leave a review and rating for the provider. Reviews help other customers and help providers build their reputation. You can submit a review from the booking detail screen. Be honest and respectful; reviews are subject to our community guidelines.</p><p>Provider profiles show their average rating and recent reviews. You can read reviews before booking to decide if a provider is right for you. Providers can respond to reviews, and you can see both sides in the review section.</p>' WHERE slug = 'reviews-ratings-overview';

-- Customer: Messaging Providers
UPDATE public.learning_articles SET summary = 'Message your provider before or after a booking.', body = '<p>You can message a provider from their profile (e.g. Chat button) or from a booking or conversation list. Use messages to ask questions, confirm details, or discuss custom requests. Conversations are in the Chats tab (app) or in account Messages (web).</p><p>Providers may send you custom offers or booking links via message. Keep important details in the thread so both sides have a record. Notifications can alert you when you receive a new message.</p>' WHERE slug = 'messaging-providers-overview';

-- Customer: Managing Bookings
UPDATE public.learning_articles SET summary = 'Reschedule, cancel, verify arrival, pay additional charges, and write reviews from your booking.', body = '<p>Open any upcoming or past booking from the Bookings tab to see its detail. From there you can reschedule (request a new date or time), cancel (subject to cancellation policy), or pay any outstanding amount. If the provider added additional charges after the booking (e.g. extra service or product at the visit), you can pay them online via the Pay button; the link may open in the in-app browser for Paystack.</p><p>When you arrive, you may be asked to verify arrival (e.g. OTP or button). After the appointment you can write a review and book again. If your provider cancels, we will notify you and help with rebooking or a refund; see the article on provider cancellations for more.</p>' WHERE slug = 'managing-bookings-overview';

-- Customer: At-Home Services
UPDATE public.learning_articles SET summary = 'How at-home services, travel fees, and safety work.', body = '<p>Many providers offer at-home services: they travel to you. When you book, you choose or confirm your address. Travel fees may apply depending on distance and the provider’s settings; these are shown at booking or checkout. Your saved addresses can be used so the provider knows where to go.</p><p>Beautonomi encourages safety for both parties: verified providers, clear booking details, and secure payments. If you have concerns, contact support. For providers, the platform supports service zones and travel fee configuration so they can set where they travel and how much they charge.</p>' WHERE slug = 'at-home-services-overview';

-- Customer: Support Tickets & Disputes
UPDATE public.learning_articles SET summary = 'Get help via support tickets and how disputes are handled.', body = '<p>If you need help, go to the Help Centre and submit a support ticket. Describe your issue (booking, payment, account, or other) and we will respond. You can view and reply to your tickets under My tickets. For urgent safety issues, use the safety resources and panic option where available.</p><p>Disputes (e.g. over a refund or service) can be raised through support. We review both sides and our policies to reach a fair outcome. Refunds, when approved, are processed according to how you paid (e.g. back to your card or wallet).</p>' WHERE slug = 'support-tickets-disputes-overview';

-- Provider: Onboarding
UPDATE public.learning_articles SET summary = 'Get verified and set up your business on Beautonomi.', body = '<p>After signing up as a provider, you will go through onboarding: verification and business setup. We may ask for identity and business details to keep the platform safe and compliant. Complete the steps in the order requested; you can often finish verification in the app or via the web link we send.</p><p>Setup status shows what is left to do: business name and description, services, availability, locations, payment and payout settings, and so on. You can complete setup in the app or use the in-app browser for web-only steps. Once verified and set up, you can accept bookings and get paid.</p>' WHERE slug = 'provider-onboarding-overview';

-- Provider: Services & Catalogue
UPDATE public.learning_articles SET summary = 'Add and manage services, add-ons, and your catalogue.', body = '<p>Your catalogue is the list of services you offer. Add services with name, duration, price, and description. You can organise them by category (e.g. Hair, Nails) and attach them to locations and staff. Add-ons let customers book extras (e.g. deep conditioning) at checkout or during the visit.</p><p>Services can be edited or deactivated when your offering changes. Accurate listings help customers choose and reduce disputes. You can also manage packages (multi-session or bundled services) where your plan supports it, often via the web portal linked from the app.</p>' WHERE slug = 'services-catalogue-overview';

-- Provider: Calendar & Scheduling
UPDATE public.learning_articles SET summary = 'Set availability, time blocks, days off, and recurring appointments.', body = '<p>Your calendar drives when customers can book. Set your availability by day and time, and assign it to locations and staff as needed. Use time blocks to mark when you are busy (e.g. lunch or private events) and days off for holidays or leave. The calendar view shows bookings and availability so you can manage your schedule.</p><p>You can create and edit bookings from the calendar or from More → Bookings. Recurring appointments (e.g. weekly) are supported: the system can create the next occurrence automatically. Group bookings and resources (rooms, equipment) are available where your plan includes them.</p>' WHERE slug = 'calendar-scheduling-overview';

-- Provider: Clients (CRM)
UPDATE public.learning_articles SET summary = 'Client list, notes, tags, and history.', body = '<p>The Clients tab (or More → Team/Client list depending on app) gives you a list of clients who have booked or messaged you. You can search, filter, and mark favorites. Open a client to see their booking history, notes you have added, and tags. Use notes to remember preferences or important details for future visits.</p><p>Client data helps you personalise service and manage follow-ups. You can start a message or a new booking from the client profile. If you have staff, you can control who sees client data based on permissions.</p>' WHERE slug = 'clients-crm-overview';

-- Provider: Payments & Checkout
UPDATE public.learning_articles SET summary = 'Accept payments, send payment links, deposits, tips, and refunds.', body = '<p>Customers pay online via Paystack when they book or when you send a payment link from a booking. You can request payment for the main booking or for additional charges (e.g. add-ons or products sold at the visit). Sending the link opens Paystack for the customer; when they pay, the booking is updated and you see the payment in your finance view.</p><p>For in-person payments (cash or card at your venue), you can mark the booking or additional charge as paid; that amount is recorded for reporting but does not go through the platform balance. You can process refunds for eligible payments from the booking or from your finance/refund tools. Tips, if enabled, are handled according to your tip distribution settings.</p>' WHERE slug = 'payments-checkout-provider-overview';

-- Provider: Yoco Terminal
UPDATE public.learning_articles SET summary = 'Set up and use the Yoco terminal for in-person payments.', body = '<p>If you use a Yoco device for in-person card payments, you can link it in Settings under payments or Yoco devices. Once set up, you can take payments at the counter for walk-in sales or for marking a booking or additional charge as paid by card. The transaction is recorded so your sales and reports stay accurate.</p><p>If the terminal is not connecting or a payment fails, check the device, app, and network. Support documentation from Yoco and from Beautonomi (see Learning Center) can help with setup and troubleshooting.</p>' WHERE slug = 'yoco-terminal-overview';

-- Provider: Payouts & Earnings
UPDATE public.learning_articles SET summary = 'Request payouts and view earnings and statements.', body = '<p>Your earnings from bookings and sales that were paid through the platform (e.g. Paystack) make up your available payout balance. Earnings from payments you took in person (cash or Yoco at your venue) are not included in that balance because the platform never held those funds. Your finance view shows both: payoutable earnings and walk-in or other revenue for reporting.</p><p>When you are ready, request a payout from the Payouts area. You need a connected payout account (e.g. bank). Payout requests are processed according to your region and our schedule. You can view payout history and statements for your records and tax purposes.</p>' WHERE slug = 'payouts-earnings-overview';

-- Provider: Staff & Permissions
UPDATE public.learning_articles SET summary = 'Add staff, roles, permissions, shifts, and commissions.', body = '<p>If you have a team, you can add staff in the Team area: name, email, phone, role, and which locations and services they can do. Each team member can have permissions (e.g. view bookings, manage calendar, process payments) so they see only what they need. You can set up shifts and days off per staff member.</p><p>Commissions let you share revenue with staff (e.g. per service or percentage). Configure commission rules in team or finance settings. Staff may log in to the provider app with their own account and see their schedule and clients according to the permissions you set.</p>' WHERE slug = 'staff-permissions-overview';

-- Provider: Locations & Service Areas
UPDATE public.learning_articles SET summary = 'Set up locations, service zones, and travel fees.', body = '<p>Add the places where you work: salon or studio address, or at-home (you travel to the customer). For each location you can set hours and which services and staff are available there. If you offer at-home services, define your service zone (e.g. radius or custom area on a map) and travel fee rules so customers see accurate pricing when they enter their address.</p><p>Service zones are often powered by map data (e.g. Mapbox). Keep your zones and travel fees up to date so customers are not surprised by extra charges and so your availability is correct. You can have multiple locations and switch between them in the calendar and booking flow.</p>' WHERE slug = 'locations-service-areas-overview';

-- Provider: Marketing & Automations
UPDATE public.learning_articles SET summary = 'Campaigns, promo codes, and marketing integrations.', body = '<p>You can run campaigns and create promo codes to attract and retain customers. Set discounts (e.g. percentage or fixed amount) and validity dates. Share codes on your profile, in messages, or in your own marketing. Customers enter the code at checkout to get the discount.</p><p>Marketing integrations (e.g. email or SMS) can be connected in settings so you can send reminders or offers through your preferred channels. Automations (e.g. booking confirmation or follow-up) can be configured in the appointment or notification settings so common tasks run without manual work.</p>' WHERE slug = 'marketing-automations-overview';

-- Provider: Reviews Management
UPDATE public.learning_articles SET summary = 'Respond to reviews and build your reputation.', body = '<p>Customer reviews appear in your Reviews area (e.g. under Engagement or More). You can filter by status and respond to reviews. A thoughtful response shows you care and can address concerns. Reviews and your average rating are visible on your profile and help new customers choose you.</p><p>Encourage satisfied customers to leave a review after their appointment. If you receive an unfair or inappropriate review, you can reply publicly and, if it violates policies, contact support. Building a strong reputation takes time but helps you get more bookings.</p>' WHERE slug = 'reviews-management-overview';

-- Provider: Inventory & Products
UPDATE public.learning_articles SET summary = 'Manage products and inventory.', body = '<p>If you sell products (retail or professional), you can add them in the Products area. Set name, price, and optionally stock levels. Products can be linked to bookings as additional charges or sold via the shop and cart. Walk-in sales let you record in-person product sales quickly.</p><p>Keep inventory updated so you do not oversell and so reports are accurate. You can manage suppliers and product categories where the plan supports it. Orders and returns from customers are handled in the Orders and Returns sections so you can process refunds or exchanges.</p>' WHERE slug = 'inventory-products-overview';

-- Provider: Reports & Analytics
UPDATE public.learning_articles SET summary = 'Dashboards, reports, and VAT.', body = '<p>Your dashboard and finance views show key metrics: revenue, bookings, completion rate, no-show rate, rating, and appointments over time. Use reports to see breakdowns by service, staff, client, payment type, or product. Export or view data for a date range to understand your business performance.</p><p>VAT reports and tax configuration are available where applicable so you can meet local tax obligations. Billing history and invoices are in the Finance area. Use these tools to stay on top of your numbers and to prepare for tax season.</p>' WHERE slug = 'reports-analytics-overview';

-- Provider: Online Booking & Direct Links
UPDATE public.learning_articles SET summary = 'Booking links and embed options.', body = '<p>Your booking link lets customers book you directly without searching the app. You can share the link on social media, your website, or in messages. In settings you can customise the link and, where supported, embed a booking widget on your site so customers can choose a time and pay without leaving your page.</p><p>Express booking is for quick at-counter or phone bookings: you or your staff can create a booking and send a payment link. Manage these links from the app or the web portal linked in the app so your booking and payment flows stay consistent.</p>' WHERE slug = 'online-booking-links-overview';

-- Provider: Waitlist & Waiting Room
UPDATE public.learning_articles SET summary = 'Waitlist and front-desk waiting room.', body = '<p>The waitlist holds customers who want a slot when one becomes available. You can see waitlist entries by date and service and offer them openings when you have availability. When they accept, you convert the waitlist entry into a booking. This helps fill last-minute gaps.</p><p>The waiting room (front desk) view shows who has arrived or is waiting for their appointment. You can check clients in, see who is next, and manage the flow so the day runs smoothly. Combined with the calendar and bookings list, you have a clear view of the day’s appointments.</p>' WHERE slug = 'waitlist-waiting-room-overview';

-- Provider: On-demand Requests
UPDATE public.learning_articles SET summary = 'Accept or decline on-demand service requests.', body = '<p>On-demand lets customers request a provider without choosing one. When a request matches your services and area, you may receive an incoming request (e.g. in the app or via notification). You can accept or decline. If you accept, the booking is created and the customer is notified; you can then see it in your calendar and manage it like any other booking.</p><p>You can enable or disable on-demand in your settings and set which services and areas you want to receive. Response time and availability affect how often you get requests. Safety and clarity (e.g. location and service) are important; the platform supports verification and clear booking details for both sides.</p>' WHERE slug = 'on-demand-requests-overview';

-- Provider: Integrations
UPDATE public.learning_articles SET summary = 'Calendars, Mapbox, OneSignal, and other integrations.', body = '<p>Beautonomi can connect to external tools you already use. Calendar integration can sync your availability and bookings with another calendar so you avoid double-booking. Mapbox powers service zones and maps for at-home and location features. OneSignal and similar services power push notifications so your device receives alerts.</p><p>Email and SMS (e.g. Twilio) integrations can be set up for notifications and marketing. Configure these in the relevant settings (notifications, marketing, or integrations). If an integration stops working, check the connection and credentials; support or the Learning Center may have troubleshooting steps.</p>' WHERE slug = 'integrations-overview';
